### ISSUE TITLE
[WFRP4e Core] Incorrect run speed calculation for Sprinter Talent 

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1033]
Sprinter talent is adding a "4" at the end of run speed and not adding +4<br/>**From**: Steven Evans#8842<br/>foundry: 9.249<br/>wfrp4e: 5.1.0<br/>wfrp4e-archives1: 2.4.0<br/>wfrp4e-core: 2.4.0<br/>wfrp4e-dotr: 2.3.0<br/>wfrp4e-eis: 2.3.0<br/>wfrp4e-middenheim: 2.4.0<br/>wfrp4e-pbtt: 2.2.0<br/>wfrp4e-rnhd: 2.4.0<br/>wfrp4e-starter-set: 2.3.0<br/>wfrp4e-ua1: 2.3.0

**Comment by Txus5012** [comment]
This only happens if Auto-calculate Run Speed is unchecked.

**Comment by moo-man** [comment]
Not currently fixable, I recommend disabling the effect if you're doing manual, as the point of manual is entering a specific value
