### ISSUE TITLE
[WFRP4e Core] Damage multiplication for 2 or more steps larger creatures is multiplied by twice as much

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1038]
https://youtu.be/qqayotmNZuY <-- Evidence

The damage from from Monstrous to Average sized creatures the damage is multiplied by 6 instead of 3 as it should be.
Enourmous to Average is 4 times as much. <br/>**From**: Perkuns#9523<br/>foundry: 9.249<br/>wfrp4e: 5.1.0<br/>wfrp4e-archives1: 2.4.0<br/>wfrp4e-core: 2.4.0<br/>wfrp4e-dotr: 2.3.0<br/>wfrp4e-eis: 2.3.0<br/>wfrp4e-middenheim: 2.4.0<br/>wfrp4e-pbtt: 2.2.0<br/>wfrp4e-rnhd: 2.4.0<br/>wfrp4e-starter-set: 2.3.0<br/>wfrp4e-ua1: 2.3.0

**Comment by moo-man** [comment]
Not a bug, calculation is correct

7 (Damaging) + 7 (Impact) + 10 (Strength) = 24 -> 24 * 3 = 72

**Comment by SimonasBanys** [comment]
![image](https://user-images.githubusercontent.com/31985858/154158528-46f13b9a-b0a6-4b9e-afd2-99256312a126.png)

Rules for damage multiplication which is currently calculated as twice as much
