### ISSUE TITLE
[WFRP4e Core] Incorrect damage reduction calculation for 2 or more steps larger creature damage

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1039]
https://youtu.be/qqayotmNZuY <-- Evidence

Armour and toughness for damage reduction from 2 or more steps larger creatures is applied after damage multiplication rather than before as it should be.<br/>**From**: Perkuns#9523<br/>foundry: 9.249<br/>wfrp4e: 5.1.0<br/>wfrp4e-archives1: 2.4.0<br/>wfrp4e-core: 2.4.0<br/>wfrp4e-dotr: 2.3.0<br/>wfrp4e-eis: 2.3.0<br/>wfrp4e-middenheim: 2.4.0<br/>wfrp4e-pbtt: 2.2.0<br/>wfrp4e-rnhd: 2.4.0<br/>wfrp4e-starter-set: 2.3.0<br/>wfrp4e-ua1: 2.3.0

**Comment by SimonasBanys** [comment]
![image](https://user-images.githubusercontent.com/31985858/154158396-4646828e-90cf-4019-bcb6-8cb2b27b0b59.png)

Rules reference for damage calculation when reducing with AP and TB

**Comment by moo-man** [comment]
I disagree, the general consensus is that "Damage" is the calculation before armour is applied.

**Comment by SimonasBanys** [comment]
Damage caused multiplication is after armour and TB

**Comment by pallando** [comment]
@SimonasBanys I fear you're confusing Wounds and Damage.
Page 159 states:
> 4: Apply Damage
> Using the Damage and the Hit Location you struck, you now
> see how many Wounds your opponent loses from your attack.
> Subtract your opponent’s Toughness Bonus and any Armour
> Points protecting the Hit Location from your Damage.

**Comment by GregorHak** [comment]
I also have problem with size (Bear is large, New Character is average). Why in this case Bear damage is 14, not 18 when rule - size multiples damages shoud work there. After -2 TB is 12 total damage, shoud be 14.
![obraz](https://user-images.githubusercontent.com/99994770/155127776-26aedec0-e0e0-4989-8837-40e3282ca9bd.png)

**Comment by moo-man** [comment]
Closing this as I believe the current implementation is correct
