### ISSUE TITLE
Bug? with Damaged Artery when applied from Critical

### ISSUE THREAD

**Issue by bluetardis** [moo-man/WFRP4e-FoundryVTT#1043]
**Describe the bug**
Foundry errata/bug? in the note - refer to Damaged Artery in the attachment

**To Reproduce**
As per the rolls but any critical should work

**Screenshots**
Bug from Chat and also Foundry versions
(This  one is from Forge rather than mine but it seems to reproduce ok)

![Chat-Damaged-Artery](https://user-images.githubusercontent.com/5024761/154778850-43eed731-1f73-4c3f-a093-651215ba62b9.png)

![Forge-Versions](https://user-images.githubusercontent.com/5024761/154778883-479ba450-0302-4531-83d3-a120ab10a38e.png)

**Version Numbers**
As per attachment but patched as of Feb-19th

**Comment by moo-man** [comment]
I'm not understanding what the issue is here?

**Comment by bluetardis** [comment]
Apologies for being unclear. I have marked up what I thought the issue was - its not clear if Foundry was expecting a variable passed or if your WFRP module expects the GM to interpret.  (Could also be me... 4 more weeks of morphine which is still slowing my brain down...)

![arm_location](https://user-images.githubusercontent.com/5024761/155030473-7c2bbcbb-c04d-453c-bf91-1bfc450fc458.png)

**Comment by moo-man** [comment]
The note specifies the instructions the user should take.
