### ISSUE TITLE
[WFRP4e Core] Remove additional line in Humans (Reiklander)

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1044]
Hello, I found probably miss click. There is additional line in this text (imported from compendium) - Image in comment.<br/>**From**: patryk695035@gmail.com<br/>foundry: 9.249<br/>wfrp4e: 5.1.0<br/>wfrp4e-core: 2.4.0

**Comment by GregorHak** [comment]
![obraz](https://user-images.githubusercontent.com/99994770/154818661-49c96c5b-0a1f-46c5-b5a9-63b4d4d491e8.png)

**Comment by GregorHak** [comment]
Also there is "space" before "Sadly, most Artists spend their lives...." in Artist career.

![obraz](https://user-images.githubusercontent.com/99994770/155012445-e4b033e5-b792-4b6d-a35d-aaa24e66a585.png)
