### ISSUE TITLE
[WFRP4e Core] If is possible add auto -5 XP fewer per Advance for Talents like Artistic or Craftsman

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1045]
If is possible add auto -5 XP fewer per Advance for Talents like Artistic or Craftsman.

Artistic talent description:
You have a natural talent for art, able to produce precise sketches with nothing but time and appropriate media. This ability has several in-game uses, ranging from creating Wanted Posters to sketching accurate journals, and has spot benefits as determined by the GM. Further to this, add Art (Any) to any Career you enter; if it is already in Career, you may instead purchase the Skill for 5 XP fewer per Advance. 

Or maybe any tips how I should do this manually? My way is to give missing promotion XP as XP reward when player wanna purchase the Skill<br/>**From**: patryk695035@gmail.com<br/>foundry: 9.249<br/>wfrp4e: 5.1.0<br/>wfrp4e-core: 2.4.0

**Comment by moo-man** [comment]
Already implemented via skill sheets

**Comment by GregorHak** [comment]
![obraz](https://user-images.githubusercontent.com/99994770/155015679-a5253cdd-c2a4-4f6c-adea-abc1e08146a8.png)
Sorry my bad

**Comment by GregorHak** [comment]
Sorry, my bad
![obraz](https://user-images.githubusercontent.com/99994770/155015761-12176f4a-2321-47d4-b128-e435975f227c.png)
