### ISSUE TITLE
Damaging Quality if the creature is one step larger but not for Creature Traits.

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1047]
**Is your feature request related to a problem? Please describe.**
Damaging Quality if the creature is one step larger works nice, but I assume that should not work for Creature Traits like Bite, Stomp, etc. 

**Describe the solution you'd like**
Only should work for Weapon(x) trait in creature sheet.

**Additional context**
"The RAW here is simple.
WFRP4, p341, 'Size Combat Modifiers':

Its weapons gain the Damaging Quality if the creature is one step larger, and Impact if two steps larger.

So, that applies to all weapons, bizarrely including Ranged weapons like Crossbows, but not Creature Traits, Spells, and so on."
Andy Law#7502 (The Rookery, 17.09.2021)
UNOFFICIAL WFRP4 FAQ
https://docs.google.com/document/d/1v37KH8Pa1BjTfnH4QT_N4_MGK3seKMvkvQKnWiJ4u3A/edit#

**Comment by moo-man** [comment]
This already is implemented
