### ISSUE TITLE
Mutation Uneven Horns

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1048]
**Describe the bug**
When add mutation "Uneven Horns" to character sheet this mutation count like Creature Trait: Horns Rating (Feature). Does not count automatically +1 AP to the head, and description of trait suggests that you make a Free Attack with Horns.

**To Reproduce**
Move "Uneven Horns" mutation to player character sheet

**Additional context**
Mutation - Core Physical Corruption Table page 184
"Uneven Horns +1 Armour Points to the Head; counts as a Creature Weapon of Damage equal to your SB (see page 343)"
***If you see page 343 to which we were redirected, you see Creature Trait: Weapon (Rating) not Horns Rating (Feature)**

Creature Trait - Core page 340 
"Horns Rating (Feature)
The creature has horns or some other sharp appendage (if its Horns Trait represents a different feature it will be noted in brackets). When the creature gains an Advantage for Charging, it may make a Free Attack with its Horns, performed as normal, using Rating to calculate Damage (its Strength Bonus is already included)."

**Version Numbers
foundry: 9.249
wfrp4e: 5.1.0
wfrp4e-core: 2.4.0

**Comment by moo-man** [comment]
The trait does provide the Head AP as well as the attack. What is the issue here?

**Comment by GregorHak** [comment]
Mutation "Uneven Horns" do not count Head AP
![obraz](https://user-images.githubusercontent.com/99994770/155177927-8f3ebd4e-864d-4bec-a90e-4e3fa32f8f11.png)
Clanrat after dragging mutation still have 2/0/3 AP on head. 

Description of mutation "Uneven Horns" is wrong, because show description of Creature Trait  "Horns Rating (Feature)"
Should show  "Counts as a Creature Weapon of Damage equal to your SB" or something like that. 

This is how I understand it. I'm new to foundry, I might be wrong

**Comment by moo-man** [comment]
Do you see the AP effect in either the item itself or the actor with the item

**Comment by GregorHak** [comment]
item efects in library:
![obraz](https://user-images.githubusercontent.com/99994770/155184014-832190da-ad37-4b4a-bb70-51482c0d09f2.png)
![obraz](https://user-images.githubusercontent.com/99994770/155183346-7f4e972a-09a6-4618-b923-704ac967c54c.png)

item efects in actor after dragging is empty
![obraz](https://user-images.githubusercontent.com/99994770/155183971-f91474bb-2b0e-4d33-ad5f-8315675869fa.png)

**Comment by moo-man** [comment]
Okay, I was looking at the EIS mutation, which is correct, the core one lacks the AP
