### ISSUE TITLE
Opposed roll does not disply the right opponent when using chat buttons

### ISSUE THREAD

**Issue by sladecraven** [moo-man/WFRP4e-FoundryVTT#1055]
All latests releases (Foundry+WFRP), no module except CoreC7.

To reproduce : 
1 - Setup a fight between 2 characters
2 - Do not target, let char1 attack with its weapon
3 - Lets char2 do a defense roll (Dodge for example)
4 - In the chat, click on "Opposed Test" button to rely the 2 rolls
5 -> The Opposed Test message is wrong, it displays twice the name of the attacker, which is very confusing.

See capture ( in the green box, it should be "gg is targeting gg2") : 

![image](https://user-images.githubusercontent.com/1085008/155509090-3826bbf2-0d8c-47b1-8a4a-77fce34ab67f.png)

**Comment by GregorHak** [comment]
Try this:
1. Do not target, let char1 attack with its weapon
![obraz](https://user-images.githubusercontent.com/99994770/155514145-67da4751-0cf6-473b-a335-7b83c3929b15.png)
2. Select char2 token, Cilck right mouse button to choose a target
![obraz](https://user-images.githubusercontent.com/99994770/155514825-9c496134-7508-4a23-bdeb-fe8e8eb13e97.png)
3. Cilck right mouse button to char1 attack test and click oppose with targets
![obraz](https://user-images.githubusercontent.com/99994770/155514445-fbcf84f8-a05b-49a3-8d29-1249ee0bba5b.png)
4.  Lets char2 do a defense roll (Dodge for example)
