### ISSUE TITLE
Creature trait - Arboreal

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1056]
**Is your feature request related to a problem? Please describe.**
Creature trait - Arboreal is automatically counted to all Climb and Stealth Tests, but not always creature climbing or stealthing in the woodlands. 

**Describe the solution you'd like**
1) Can you make pop out window before Climb and Stealth Tests roll to creatures with this trait - with question: are creature is in the woodlands or something like that. If Yes adds its Agility Bonus to the SL.

2) Other solution, please add text info on chat that creature has +X SL from Arboreal trait, will work like notification for shorter weapons. Even if automatically counted you will see this, and manually count
![obraz](https://user-images.githubusercontent.com/99994770/155509895-3d4f76a8-2839-4c75-832d-3b50ec437ef4.png)

3) Stop automatically counted SL but give option to choose from the bonuses field in roll window
![obraz](https://user-images.githubusercontent.com/99994770/155510561-30316945-10a2-42d6-822f-989ec6679338.png)

**Additional context**
Creature trait - Arboreal
"The creature is at home in the forests. In the woodlands, it adds its Agility Bonus to the SL of all Climb and Stealth Tests."
*Please note that this bonus always counts in the forest, not just for **successful** forest tests.

**Comment by moo-man** [comment]
Since this is a broad condition that can apply to *all* tests in woodland, the intention is for the effect to be toggled on or off depending on the location.
