### ISSUE TITLE
Add option to delete talent from creature sheet

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1059]
**Is your feature request related to a problem? Please describe.**
I can't delete talent from creature sheet. Creature trait you can disable or delete from notes tab, but talent llike "Tenacious" - I can't find a way to delete/disable

**Additional context**
![obraz](https://user-images.githubusercontent.com/99994770/155596612-dcb55e5f-e52f-4de2-bc45-cf8495d3d3f3.png)

**Comment by moo-man** [comment]
This is already implemented via the delete key
