### ISSUE TITLE
Diseases - Festering Wound do not work

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1060]
**Describe the bug**
When I click Incubation for Festering Wound I got thiss error:
![obraz](https://user-images.githubusercontent.com/99994770/155625784-0d7c01c6-7886-4f07-9325-60f0817eba98.png)

**Screenshots**
![obraz](https://user-images.githubusercontent.com/99994770/155625592-1e8cb4a9-5807-45b8-976e-8a1dab949c78.png)

**Version Numbers**
foundry: 9.249
wfrp4e: 5.1.0
wfrp4e-core: 2.4.0

**Comment by moo-man** [comment]
Anything that does not follow a conventional roll formula must be done manually

**Comment by GregorHak** [comment]
Ok, thanks

**Comment by GregorHak** [comment]
Ok, thanks

**Comment by GregorHak** [comment]
by the way, how to initiate Wound effect? Any button for that? Or i should do everything manually, but why then you write macro?

![obraz](https://user-images.githubusercontent.com/99994770/155627584-01fe95ba-ac7e-412c-b98a-beb4f7386cb6.png)

**Comment by moo-man** [comment]
If you have general questions please use one of the discord channels
