### ISSUE TITLE
[WFRP4e System] Adding the possibility to customise games icons

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1071]
Dear Moo Man, 

I understand that you needed to "delete" the original icon you were using for copyright issues, but is there a possibility that we can choose to customise them and keep them the same with every update ?

Every time i update the core module, my custom icons are deleted.

Thank you again.<br/>**From**: manga.afternoon.officiel@gmail.com<br/>foundry: 9.255<br/>wfrp4e: 5.1.1<br/>wfrp4e-core: 2.4.1

**Comment by fmunoz-geo** [comment]
You can create a folder under the modules with all your images and just open the core item db and replace the image string with the directory with the new dieectory as long as the file is named identical.
(Keep copy safe of the original db file)

**Comment by moo-man** [comment]
Yeah that is the intention. Adding a way to reference these icons in a different location is not something I plan to do, see #135 

Icon paths are stored in the database. If, hypothetically, there was some configuration option like the sound path, but for icons, where the user can change where the icons are stored, it would require updating every singe item (owned and not), not to mention this update would also need to be applied to every thing in the compendium, as well as any future content. This would be incredibly error prone and cause a lot of confusion with both users and myself.
