### ISSUE TITLE
Melee (Basic) in new character card

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1075]
**Describe the bug**
When you use button: Add Basic Skills or begin Character Creation new character gain skill "Melee". Should be "Melee (Basic)". Weapons do not use "Melee" when you don't have "Melee (Basic)" but insted use WS.

**Comment by moo-man** [comment]
Melee is included to match the official character sheet, and for the same reasons.

**Comment by GregorHak** [comment]
Okey, but Melee (Basic) it is not added automatically. When you use button: Add Basic Skills or begin Character Creation Melee (Basic) is skipped.

**Comment by moo-man** [comment]
Adding Melee (Basic) automatically could cause unintentional behavior, as having the skill lets Basic weapons have their Qualities.

**Comment by GregorHak** [comment]
Okey, I understand
