### ISSUE TITLE
[WFRP4e Core] Twin-tailed Comet AoE

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1088]
Comet does not have the option RAW to expand the AoE based on overcasts as far as I can tell, but it is included as an option when the miracle is cast.<br/>**From**: CoG#9765<br/>foundry: 9.255<br/>wfrp4e: 5.1.1<br/>wfrp4e-core: 2.4.1<br/>wfrp4e-dotr: 2.3.1<br/>wfrp4e-eis: 2.3.1<br/>wfrp4e-pbtt: 2.2.1<br/>wfrp4e-rnhd: 2.4.1<br/>wfrp4e-starter-set: 2.3.1

**Comment by Cogsagi** [comment]
Source material for reference.

Spells mention expanding AoE, miracles do not. Other miracles specifically mention adding 2SL to expand the AoE like Soulfire or Heed not the Witch, which is missing from Comet.

Spell overcasts:
![image](https://user-images.githubusercontent.com/41082782/159069563-eae6222c-5cd7-431c-92de-32770981d011.png)


Miracle overcasts:
![image](https://user-images.githubusercontent.com/41082782/159069495-e0a99f0e-b746-4972-bb9a-671c95fe5202.png)
