### ISSUE TITLE
[WFRP4e Core] add xp error

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1099]
Hi, 
i use a macro for adding xp to characters, teh macro work for more session, but at last time, at the start of teh session it wors perfecti, but at the end i have this error:

cannot read properties of undefined (reading 'data')

one charachter from the group recive the xp, but all other doesn't, i try it in other wfrp4e world and in that world at all charchter i have this error message.
I make a new test world for this problem, and have this error for all charachter (new, or imported) but if i import that character, that works fine, the imported version is working fine too

all of my things ar up-to-date

Thy for the help!

This is the macro: (its from the gm-tools module)
addXP();

async function addXP() {

  // setup: determine group of actors to be awarded experience
  if (game.user.targets.size < 1) {
    // (1) all player characters if no tokens are selected
    awardees = Array.from(game.actors).filter(pc => pc.hasPlayerOwner && pc.type == "character");
  } else {
    // (2) otherwise, all targeted player character tokens
    awardees = Array.from(game.user.targets).filter(pc => pc.actor.hasPlayerOwner && pc.actor.type == "character");
  }

  // setup: exit with notice if there are no player-owned characters
  if (awardees.length < 1) return ui.notifications.error(game.i18n.localize("GMTOOLKIT.Token.TargetPCs"), {});

  // Get  session ID/date, default XP award and default reason
  let XP = Number(game.settings.get("wfrp4e-gm-toolkit", "addXPDefaultAmount"))
  let reason = (game.settings.get("wfrp4e-gm-toolkit", "addXPDefaultReason"))
  if (reason == "null") {
    reason = ""
  } else {
    reason = (game.settings.get("wfrp4e-gm-toolkit", "addXPDefaultReason")) 
    let session = game.gmtoolkit.utility.getSession()
    reason = reason.replace("%date%", session.date)
    if (session.id != "null" ) reason = reason.replace("%session%", session.id)
  }

  // Prompt for XP if option is set
  if (game.settings.get("wfrp4e-gm-toolkit", "addXPPrompt")) {
    let awardeeList = "<ul>"
    awardees.forEach (pc => {
      awardeeList +=  `<li>${pc?.actor?.name || pc.name}</li>` 
    })
    awardeeList += "</ul>"
    const dialog = new Dialog({
      title: (game.i18n.localize('GMTOOLKIT.Dialog.AddXP.Title')),
      content: `<form>
              <p>${game.i18n.format("GMTOOLKIT.Dialog.AddXP.Recipients", {recipients : awardeeList})}</p>
              <div class="form-group">
                <label>${game.i18n.localize("GMTOOLKIT.Dialog.AddXP.Prompt")}</label> 
                <input type="text" id="add-xp" name="add-xp" value="${XP}" />
              </div>
              <div class="form-group">
                <label>${game.i18n.localize("GMTOOLKIT.Dialog.AddXP.Reason")}</label> 
                <input type="text" id="xp-reason" name="xp-reason" value="${reason}" />
              </div>
          </form>`,
      buttons: {
        yes: {
          icon: "<i class='fas fa-check'></i>",
          label: game.i18n.localize("GMTOOLKIT.Dialog.Apply"),
          callback: (html) => {
            let XP = Math.round(html.find('#add-xp').val());
            if (isNaN(XP)) return ui.notifications.error(game.i18n.localize("GMTOOLKIT.Dialog.AddXP.InvalidXP"))
            let reason =  html.find('#xp-reason').val();
            updateXP(awardees, XP, reason);
          }
        },
        no: {
          icon: "<i class='fas fa-times'></i>",
          label: game.i18n.localize("GMTOOLKIT.Dialog.Cancel"),
        },
      },
      default: "yes"
  }).render(true);
  } else {
    updateXP(awardees, XP, reason)
  }

} // END: addXP

function updateXP(awardees, XP, reason) {
  let chatContent = ""

  // cycle through player characters, gathering experience change data for report message
  awardees.forEach ( pc  => {
    recipient = pc?.actor?.name || pc.name 
    XPTotal = pc?.details?.experience?.total || pc.actor.data.data.details.experience.total; 
    newXPTotal = Math.max(XPTotal + XP,0);
    XPCurrent = pc?.details?.experience?.current  || pc.actor.data.data.details.experience.current; 
    newXPCurrent = Math.max(XPCurrent + XP,0);

    // update token actor or actor
    pc?.actor ? pc.actor.awardExp(XP, reason) : pc.awardExp(XP, reason)

    // build report message 
    chatContent += game.i18n.format("GMTOOLKIT.AddXP.Success", {recipient, XPTotal, newXPTotal, XPCurrent, newXPCurrent} )  
  }); // end cycle
  
// confirm changes made in whisper to GM
    let chatData = game.wfrp4e.utility.chatDataSetup(chatContent, "gmroll", false)
    chatData.flavor = game.i18n.format("GMTOOLKIT.AddXP.Flavor", {XP, reason})
    ChatMessage.create(chatData, {});  
    console.log(chatContent)

} // END: updateXP

/* ==========
 * MACRO: Add XP
 * VERSION: 0.8.0
 * UPDATED: 2021-12-30
 * DESCRIPTION: Adds a set amount of XP to all or targeted player character(s). Adds XP update note to the Chat log.
 * TIP: Characters must have a player assigned. 
 * TIP: Default XP amount and reason can be preset in module settings, along with option to bypass prompt for XP amount each time.
 * TIP: Non-whole numbers are rounded off. Negative numbers are subtracted. 
 ========== */
<br/>**From**: Bill#6288<br/>foundry: 9.255<br/>wfrp4e: 5.2.0<br/>wfrp4e-core: 2.4.2<br/>wfrp4e-eis: 2.3.2<br/>wfrp4e-rnhd: 2.4.1<br/>wfrp4e-starter-set: 2.3.2

**Comment by Jagusti** [comment]
This is resolved in the next version of the GM Toolkit module. The fix is available on the development branch if needed before a proper release.
