### ISSUE TITLE
No harm

### ISSUE THREAD

**Issue by Bensakur** [moo-man/WFRP4e-FoundryVTT#11]
Hello, i'm a newbie in Foundry and I can barely  speak English properly. 
What I want to ask is why this error appears when I try to get the damage from the opposed test. The "Florian" in the picture wields a dagger, by the way.
Thanks for the help!

![issue](https://user-images.githubusercontent.com/68592437/88047026-3c23f380-cb51-11ea-83c2-912c03295af6.jpg)

**Comment by moo-man** [comment]
There's no damage because he's not *using* the weapon in the attack, it looks like he's just rolling a melee skill. Click on the weapon in the combat tab to roll an attack with a weapon. 

If you see see **SL**: +7 (10 Damage) then you should be good.
