### ISSUE TITLE
[WFRP4e System] Drag and drop problem

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1109]
drag and drop doesn't work, even aften cleaning and updating all modules.<br/>**From**: malherbe.cyan@gmail.com<br/>foundry: 9.255<br/>wfrp4e: 5.2.0<br/>wfrp4e-altdorf: 2.0.1<br/>wfrp4e-core: 2.4.2<br/>wfrp4e-dotr: 2.3.2<br/>wfrp4e-eis: 2.3.2<br/>wfrp4e-rnhd: 2.4.1<br/>wfrp4e-starter-set: 2.3.2<br/>wfrp4e-ua1: 2.3.1

**Comment by StevenEvans1966** [comment]
Having the same issue.

 Trying to drag drop heal from rest get

Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'testData')
[Detected 1 package: system:wfrp4e]
    at <anonymous> ([D:\Users\Steven\AppData\Local\FoundryVTT\Data\systems\wfrp4e\modules\hooks\chat.js:374:41]())

Cant Drag an drop token on canvas on to
