### ISSUE TITLE
[WFRP4e Core] Advantage

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1110]
Hey there I want to post an issue to you, or more like an enhancement for the combat system. We players often forget to increase our advantage points for sucessfull opposed tests and we would like the system to take care of that.

best regards,
a huge fan.<br/>**From**: jason.a.charles@outlook.com<br/>foundry: 9.266<br/>wfrp4e: 5.2.0<br/>wfrp4e-core: 2.4.2<br/>wfrp4e-eis: 2.3.2<br/>wfrp4e-rnhd: 2.4.1<br/>wfrp4e-starter-set: 2.3.2

**Comment by Jagusti** [comment]
This is handled in [v0.9.3 of the GM Toolkit](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/releases/tag/v0.9.3).

**Comment by moo-man** [comment]
Going to leave this as a GM toolkit feature
