### ISSUE TITLE
[WFRP4e System] Food2 as marker

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1124]
Can't use Food2 as marker. I do not see this marker on the list. Some entry icon has different name than png file but still I don't find Food2 (corn icon).<br/>**From**: patryk695035@gmail.com<br/>foundry: 9.269<br/>wfrp4e: 5.2.0<br/>wfrp4e-core: 2.4.2

**Comment by GregorHak** [comment]
Additional screenshots:
![obraz](https://user-images.githubusercontent.com/99994770/166496806-7370029f-e0bf-4223-891c-47d3d96ebe62.png)
![obraz](https://user-images.githubusercontent.com/99994770/166496915-a61d65a4-144c-428a-945d-b6ef5ffb57d7.png)

**Comment by Kayne** [comment]
I made a pull request to add missing Food icon: #1132
