### ISSUE TITLE
[WFRP4e Core] Sharpshooter Effect

### ISSUE THREAD

**Issue by Txus5012** [moo-man/WFRP4e-FoundryVTT#1129]
Here is the script I created for the Sharpshooter effect.
![Sharpshooter](https://user-images.githubusercontent.com/87753744/168422369-8e9e8fda-bdbe-463f-89f7-d5ef21314b96.jpg)

**Comment by Havoclivekiller** [comment]
Shouldn't this take into account that the weapon is Ranged and not used in Point Blank range?

**Comment by Txus5012** [comment]
This effect only applies if there is a negative size modifier, so no need to specify if it is a Ranged attack.
Is this talent affected when shooting at Point Blank range?

**Comment by Havoclivekiller** [comment]
My bad. I thought you get penalties to melee to and Point Blank - I meant Engaged, that you dont get modifiers due to size but that rule is in a diff system. Overall this is good, good job

**Comment by Kayne** [comment]
I think this is simpler and does the same job:

```javascript
if (args.options.sizeModifier < 0)
  args.prefillModifiers.modifier += args.options.sizeModifier * (-1)
```

**Comment by Txus5012** [comment]
Yeah, very nice. Actually this would be even simpler:

if (args.options.sizeModifier < 0)
  args.prefillModifiers.modifier -= args.options.sizeModifier
