### ISSUE TITLE
[WFRP4e Core] Menacing Talent

### ISSUE THREAD

**Issue by Txus5012** [moo-man/WFRP4e-FoundryVTT#1141]
**Is your feature request related to a problem? Please describe.**
Looking at the Menacing talent, it is a bit confusing to have to select two different lines in the roll dialog. The bonus of the Test related to the Talent has it's own automatization so I guess we shouldn't mess with it, but the bonus of the Talent's description can be easily automatized (specially since I can't see any scenario where the player won't like to add it).

**Describe the solution you'd like**
The Menacing effect can be automized with the simple script below.
Note that there isn't any "NAME.Intimidate" line in the language file, so it should be added.
![Menacing](https://user-images.githubusercontent.com/87753744/170886541-f5a3421e-1bb8-4dc0-a753-a34d5e2a29da.jpg)

**Comment by moo-man** [comment]
I prefer to maintain consistency with how other talents work with their bonuses being selectable

**Comment by moo-man** [comment]
Sorry I misread, I was sure this was already provided
