### ISSUE TITLE
[WFRP4e System] aethyric attunement

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1153]
successful critical channelling tests with aethyric attunement still show minor misscast<br/>**From**: Perkuns#9523<br/>foundry: 9.269<br/>wfrp4e: 5.3.0<br/>wfrp4e-altdorf: 2.0.1<br/>wfrp4e-archives1: 2.4.1<br/>wfrp4e-core: 2.4.3<br/>wfrp4e-dotr: 2.3.3<br/>wfrp4e-eis: 2.3.3<br/>wfrp4e-middenheim: 2.4.1<br/>wfrp4e-pbtt: 2.2.2<br/>wfrp4e-rnhd: 2.4.1<br/>wfrp4e-starter-set: 2.3.3<br/>wfrp4e-ua1: 2.3.1<br/>wfrp4e-ua2: 2.0.0

**Comment by SimonasBanys** [comment]
![Capture](https://user-images.githubusercontent.com/31985858/173811238-f4303343-dc1d-4bbe-be05-cf6a01fb8e60.PNG)

screenshot showing the result. no errors are shown in the console

**Comment by moo-man** [comment]
Old aethyric attunement script
