### ISSUE TITLE
[WFRP4e System] Translation Keys

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#116]
Missing translation keys for : 
"Add basic Skills" 
"Import Stat Block"

<br/>**From**: LeRatierBretonnien<br/>wfrp4e: 3.0.0<br/>wfrp4e-core: 1.0<br/>wfrp4e-rnhd: 1.0<br/>wfrp4e-starter-set: 1.0

**Comment by sladecraven** [comment]
Missing translation keys also for :   
"New extended test"
 "New Trapping" 
"New Critical"
"New Injury"
