### ISSUE TITLE
[Power Behind the Throne] Middenheim map

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1177]
Why isnt the Middenheim map that is included in the book and pdf in the module?<br/>**From**: Rickard.k@icloud.com<br/>foundry: 9.269<br/>wfrp4e: 5.3.0<br/>wfrp4e-core: 2.4.3<br/>wfrp4e-dotr: 2.3.3<br/>wfrp4e-eis: 2.3.3<br/>wfrp4e-pbtt: 2.2.2<br/>wfrp4e-starter-set: 2.3.3

**Comment by moo-man** [comment]
Pretty soon, but note I have only included the map assets themselves, not preconfigured scenes. I don't want a Middenheim map in the PBTT module to be confused with the Middenheim map provided by the Middenheim module, since that one has the pinned journal entries and drawings and is the one that *should* be used if the user has it. Otherwise, they can create a scene with the map in PBTT.

**Comment by M4sterbetty** [comment]
Ok, Thank you for the great job your doing!
