### ISSUE TITLE
Spell item description appears automatically

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1182]
**Describe the bug**
When edit spell item descrition the lore of magic text appears automatically. GM notes are not affected, I check spells from Lore of Life and Light and bug occurs. Maybe it's intentional?

**To Reproduce**
[link to yt video](https://youtu.be/GG6lDkyodvM)

![obraz](https://user-images.githubusercontent.com/99994770/179812412-f57e0271-4da5-41db-b785-d76d7f6f6ec1.png)

**Comment by moo-man** [comment]
It is intentional
