### ISSUE TITLE
Charging when you already have maximum Advantages

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1189]
**Describe the bug**
If you check charging box in any Weapon Test when have max Advantages e.g. 3/3 your Advantages increase in this dialog box to 4, so you get also +40 modifiers for Advantages. This should not happend, because you are over the Advantages limit (your max modifier for Advantages is +30). You can just leave Charging box unchecked if you have max Advantages before charge, but talents like Berserk Charge (When you charge, you gain +1 Damage) and Mounted Combat rules (When Charging, you may use the Strength and Size rules of your mount for the purposes of calculating Damage) and others things depends on charging will not work, they will not automatically count.

Can you add a function: if you have max Advantages, and check Charging box, Advantages will not be +1, but will stay at the current, max level.

#Edit: There is always a option to check Charging box, and manually edit Advantages from 4 to 3, but a function, which automatically do it for you, will be great

**Comment by Jagusti** [comment]
It would be good to retain the charging flag in the test data though if the box is checked, even if Advantage is capped and the bonus isn't applied.
