### ISSUE TITLE
[Death on the Reik] Temple of Sigmar - Joural incorrect

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1196]
Receiving Room is mislabel as G and the Cript is mislabeled as H<br/>**From**: Steven Evans#8842<br/>foundry: 9.269<br/>wfrp4e: 5.4.1<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-archives1: 2.4.1<br/>wfrp4e-core: 2.4.4<br/>wfrp4e-dotr: 2.3.4<br/>wfrp4e-eis: 2.3.4<br/>wfrp4e-horned-rat: 2.0.1<br/>wfrp4e-middenheim: 2.4.2<br/>wfrp4e-owb1: 2.0.1<br/>wfrp4e-pbtt: 2.2.3<br/>wfrp4e-rnhd: 2.4.2<br/>wfrp4e-starter-set: 2.3.4<br/>wfrp4e-ua1: 2.3.2<br/>wfrp4e-ua2: 2.0.0

**Comment by moo-man** [comment]
Marking this as non-issue as the book itself has the typo

**Comment by GregorHak** [comment]
Then maybe add info about this in GM note
