### ISSUE TITLE
[WFRP4e Core] Bug for automatic payment request

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1207]
Hello,

When using the automatic price button for an item. 

Such as "11/-" for the price of 2 beds in the beard of ulric tavern, I get an error message for the payment request "syntax error".
It is a minor bug, since I still do the request manually anyway, but would be neat to have it fixed on a future update.

For information I suppose the french translation of the warhammer modules.<br/>**From**: Eligios#7739<br/>foundry: 9.280<br/>wfrp4e: 5.4.1<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-core: 2.4.4<br/>wfrp4e-eis: 2.3.4

**Comment by moo-man** [comment]
@sladecraven User reported that this only applies with the French translation, could you check if this is a problem with the system or the translation specifically?

**Comment by sladecraven** [comment]
Needs to write /pay 12pa, it works. He should come to the French Discord, you can close this
