### ISSUE TITLE
[WFRP4e System] Armour Points are 0 on v10

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1208]
Open Core (v2.4.4) Trappings compendium.
Open Leather Jack (or other armour item)
In Details tab, AP is set to 0 on all hit locations.

The correct values persist in trappings.db. 
They also appear correctly with the same compendium version on FVTT 9.280 / WFRP4e 5.4.1<br/>**From**: Jagusti#3610<br/>foundry: 10.283<br/>wfrp4e: 6.1.1

**Comment by Jagusti** [comment]
In the Compendium 
![image](https://user-images.githubusercontent.com/521096/187899020-dfbeeaa9-b8e6-48f8-96b1-eafc354690d6.png)

Item migration when dragging to character sheet
![image](https://user-images.githubusercontent.com/521096/187898869-98635776-e7b3-47bb-b11e-2a1323593800.png)
