### ISSUE TITLE
V10 issues

### ISSUE THREAD

**Issue by Txus5012** [moo-man/WFRP4e-FoundryVTT#1211]
Some issues I've found while testing v10:

1. Fear and Terror commands.
Fear: Nothing happens.
Console log:
![Fear](https://user-images.githubusercontent.com/87753744/187917975-e915d3a7-3f26-4bb3-8894-5e78afd0fcb3.jpg)
Terror: The cool test is prompted, but no condition is added in failure or success. Also, it starts an opposed test.
![Terror](https://user-images.githubusercontent.com/87753744/187918318-e3bc1d48-2bc3-4bec-af48-553cab59cb84.jpg)
Console log:
![Terror log](https://user-images.githubusercontent.com/87753744/187918342-1f7de8b0-6baa-4105-9990-a903ac0adee9.jpg)

2. Reload.
When clicking in an unloaded weapon, nothing happens.
Console log:
![Reload](https://user-images.githubusercontent.com/87753744/187918729-17943bf5-6f69-4c22-ab1d-ad285f1d2c8f.jpg)

3. Sidebar icons.
Chat: The new message icon appears below the normal one
![New Chat Message](https://user-images.githubusercontent.com/87753744/187919074-19580fa6-a18a-42be-b0ff-a9ee41639dfb.jpg)
Cards: When selecting the Cards tab, the icon disappears.
![Cards](https://user-images.githubusercontent.com/87753744/187919140-2cb5332e-c1c6-4a25-af8f-dc2099026d15.jpg)

Foundry: v10
wfrp4e: 6.1.1
wfrp4e-core: 2.4.4
All other modules disabled.

**Comment by Txus5012** [comment]
4. Earning skills in career sheet.
In the Earning Skill tab of the career sheet nothing is shown. It is added correctly when dragging it to a character and the income roll works well.

**Comment by moonwolf-github** [comment]
I've got `GET https://my-foundry/WFRP-Header.jpg 404` on join page

**Comment by Jagusti** [comment]
@moonwolf-github this Foundry issue may cover your background image problem? https://github.com/foundryvtt/foundryvtt/issues/7917

**Comment by moonwolf-github** [comment]
Hmm... I'm not sure, but when i added `systems/wfrp4e/` to background path (in `system.json`) it started working even for existing worlds. And there is no entry in `world.json` when I'm creating a new world.

**Comment by Txus5012** [comment]
5. Size.
The Size trait changes the token size correctly if it is Average or bigger, but do nothing if changed to Small or smaller. The Small talent doesn't change it either.
Also, there is no wound auto-calculation after changing size (smaller or bigger).

**Comment by moo-man** [comment]
> Also, there is no wound auto-calculation after changing size (smaller or bigger).

@Txus5012 I cannot seem to reproduce this
