### ISSUE TITLE
[WFRP4 System] Missing localization for characteristic labels and its tooltips

### ISSUE THREAD

**Issue by phenomen** [moo-man/WFRP4e-FoundryVTT#1212]
**Describe the bug**
In the Character / NPC sheets characteristic labels and its tooltips are not localized.
(I'm sure it worked fine a few updates ago)

**Screenshots**

![image](https://user-images.githubusercontent.com/138311/187949537-d5180aed-e582-40de-9ed4-8b40ca98bbf8.png)

**Version Numbers**

Foundry: 10.283
wfrp4e: 6.1.1

**Comment by moonwolf-github** [comment]
It works OK for me.

**Comment by phenomen** [comment]
Looks like this issue does exist only on pre-made NPCs from compendium while new NPCs have localized characteristics

![image](https://user-images.githubusercontent.com/138311/187996784-d98cb350-09c2-472e-8703-fabd5927f42f.png)

**Comment by moo-man** [comment]
This is from old actors from before the template had localization keys.

See https://github.com/moo-man/WFRP4e-FoundryVTT/issues/1226 for overall progress
