### ISSUE TITLE
[System][Bug] Healed upon stat change

### ISSUE THREAD

**Issue by Havoclivekiller** [moo-man/WFRP4e-FoundryVTT#1215]
Example, I've given a player an item that sucks the enemy's Strength, thus it increases Strength. It was made using an effect.
The problem, once the modifier in the effect makes Strength go over another ten (bonus increase), it increases Wounds (as it should be) but also resets it to full (instead of keeping what was set in the first place).

**Comment by moo-man** [comment]
This is intentional, as it's convenient generally more than it isn't, I have no way to know if a stat change should or shouldn't refill wounds
