### ISSUE TITLE
WRFP Modules does't work in Foundry V10

### ISSUE THREAD

**Issue by Ildebrandt** [moo-man/WFRP4e-FoundryVTT#1216]
Hi all, after updating foundry to V10 the WFRP modules no longer load. Is there a way to fix it or I have to (don't know how) try to revert to version 9.

Foundry: V10 Build 284
wfrp4e: 6.1.1
wfrp4e-core: 2.4.4

**Comment by moo-man** [comment]
Uninstall and reinstall the modules
