### ISSUE TITLE
[WFRP4e System] Edit World in game, text and background has almost the same colour

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1217]
Edited world description in game and noticed the text and background almost had the same colour, so it was almost completely invisible. Was using Firefox when tested.<br/>**From**: mogrogh#4778<br/>foundry: 10.284<br/>wfrp4e: 6.1.1

**Comment by mogrogh** [comment]
![bild](https://user-images.githubusercontent.com/69079040/188273927-5a2fb114-4072-4b12-bfce-fc823029ab61.png)
