### ISSUE TITLE
[WFRP4e System] Card Stacks button dissapears after clicking on it

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1219]
I clicked the card stack button by mistake and the buttan dissapears. Not even hovering where it should be gives me a tooltip. I tried Pathfinder 2-system and the button there is still visible.<br/>**From**: mogrogh#4778<br/>foundry: 10.284<br/>wfrp4e: 6.1.1

**Comment by mogrogh** [comment]
![bild](https://user-images.githubusercontent.com/69079040/188277917-700ead21-958b-434a-9b5a-98f9ff2613c1.png)

**Comment by mogrogh** [comment]
Button comes back if you press any other button, like journals.
