### ISSUE TITLE
[WFRP4e Core] Error when assigning wildcard tokens

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1220]
I am trying to create a token with wildcard but instead it gives me error. Even if I use *.png the token does not update in the prototype token. 
I go into prototype
https://media.discordapp.net/attachments/772245721733791747/1015702594708054026/unknown.png
I change the path to the folder
https://media.discordapp.net/attachments/772245721733791747/1015703131037892789/unknown.png
I get this errors on the console
https://cdn.discordapp.com/attachments/772245721733791747/1015703410936389814/unknown.png

Even if I give the wildcard a file extension. the prototype dont update the token: I had tried both to update token and apply but still dont work
https://cdn.discordapp.com/attachments/772245721733791747/1015703924063338576/unknown.png
Still it default to mystery man instead of the folder with the token
https://cdn.discordapp.com/attachments/772245721733791747/1015704126300098641/unknown.png<br/>**From**: danil0#8120<br/>foundry: 10.284<br/>wfrp4e: 6.1.1

**Comment by danil0man** [comment]
It gives me this last error after I close it
![image](https://user-images.githubusercontent.com/72052103/188285251-e505efce-27cf-4fb1-8c2f-6288b968a6a4.png)

**Comment by moo-man** [comment]
Foundy core issue
