### ISSUE TITLE
[WFRP4e System] Inventory management is difficult when there are many items on the sheets

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1230]
When a sheet has many items, it's difficult to move items into and out of containers, leading to a lot of frustration when giving items to players. 

Some enhancements that could be made in this area are having collapsible sections for different item categories and containers and having a button that opens a dialog for moving an item to a container.<br/>**From**: Bolts#9418<br/>foundry: 9.280<br/>wfrp4e: 5.4.1<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-core: 2.4.4<br/>wfrp4e-dotr: 2.3.4<br/>wfrp4e-eis: 2.3.4<br/>wfrp4e-middenheim: 2.4.2<br/>wfrp4e-pbtt: 2.2.3<br/>wfrp4e-rnhd: 2.4.2<br/>wfrp4e-starter-set: 2.3.4<br/>wfrp4e-ua1: 2.3.2

**Comment by GregorHak** [comment]
I've been waiting for this update, can it be expected in the future @moo-man ?
