### ISSUE TITLE
[WFRP4e System] Morrslieb button in light controls not working

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1232]
Just updated to V10 and was trying out the system for an upcoming game. I noticed that Morrslieb button in the light controls no longer changes the scene green. I am not sure if it did anything else in the pas but nothing appears to happen currently. <br/>**From**: Joseph#8010<br/>foundry: 10.284<br/>wfrp4e: 6.1.2

**Comment by Txus5012** [comment]
Curiously, in my tests it worked if the FX Master module is activated, but not without the module.
