### ISSUE TITLE
[WFRP4e System] Some FVTT dialog boxes are right-cropped

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1233]
I've not checked exhaustively, but this can be observed for Macros Directory and Configure Scene.

A similar issue was reported by Vox Nihili on the Foundry Discord, though this isn't occurring for me.  In fact, under v10 thumbnails correctly fill the width of the sidebar rather than be tiled.  https://discord.com/channels/170995199584108546/697845419593695362/1016618833169100812<br/>**From**: Jagusti#3610<br/>foundry: 10.284<br/>wfrp4e: 6.1.2

**Comment by Jagusti** [comment]
Macros Directory 
![image](https://user-images.githubusercontent.com/521096/188982525-26b6cc98-3b5e-4111-95a7-311a6a6014a4.png)

Configure Scene: see `Initial View Position` line
![image](https://user-images.githubusercontent.com/521096/188982472-fa9cb85d-862a-4950-b199-492823a15193.png)

**Comment by Jagusti** [comment]
Hmmm ... should there be a vertical scroll bar on Configure Scene? 🤔

**Comment by Jagusti** [comment]
The Scenes sidebar on v10: 
![image](https://user-images.githubusercontent.com/521096/188983017-60b97c27-c988-4b8b-bef4-386cac1690ce.png)

**Comment by TheFirst05** [comment]
We also get a similar effect with the combat tracker tab when it's popped out. The Group Advantage boxes are not shown the same way either.
