### ISSUE TITLE
Weapon Length

### ISSUE THREAD

**Issue by Ryach** [moo-man/WFRP4e-FoundryVTT#1234]
In settings you can mark use weapon reach system but looks to me is not calculated at all if attacking or defending 
![image](https://user-images.githubusercontent.com/6523648/189077629-77f47403-019f-4ff5-b190-0ccbd108d86a.png)

I tested this in foundry 9 and 10 last version 

Rules:
Weapon Length - If your weapon is longer than your opponents’, they suffer a penalty of –10 to hit you as you find it easier to keep them at bay.

Foundry:
wfrp4e:
wfrp4e-core:

**Comment by Txus5012** [comment]
Works well (v9 & v10). It is calculated and shown after resolving the opposed test.
