### ISSUE TITLE
[WFRP4e System] Secret block is not shown for the GM

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1253]
Secret block is not shown for the GM. It still possible to see that it exists when editor is activated.
Tested on fresh world with latest Foundry & WFRP4e, no other modules activated.<br/>**From**: zweite#5557<br/>foundry: 10.285<br/>wfrp4e: 6.1.2

**Comment by ZwS** [comment]
![Imgur](https://imgur.com/5DL5usL.png)
