### ISSUE TITLE
[WFRP4e Core] Quarterstaff typo in Hedge Witch & Witch Career descriptions

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1263]
In the Hedge Witch and Witch Career descriptions, they both gain "Quartersta?", instead of "Quarterstaff".<br/>**From**: The First#7330<br/>foundry: 10.285<br/>wfrp4e: 6.1.2

**Comment by fmunoz-geo** [comment]
Also similar issue with the last level of Envoy. It has "staff" as trapping. Same typo.
