### ISSUE TITLE
[WFRP4e Core] AP is shown as 0 for compendium armor

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1270]
For items in compendium AP for locations is shown as 0. However if item is imported then AP is shown as intended.
![bug](https://imgur.com/wl9GX0c.jpg)<br/>**From**: zweite#5557<br/>foundry: 10.285<br/>wfrp4e: 6.1.2

**Comment by moo-man** [comment]
Non-issue

Core items are built for v9, migration is applied when the item is created

**Comment by ZwS** [comment]
So once core will be updated to the v10 this issue will be gone?

**Comment by moo-man** [comment]
Right
