### ISSUE TITLE
testData.other is sometimes string and sometimes array

### ISSUE THREAD

**Issue by silentmark** [moo-man/WFRP4e-FoundryVTT#1283]
**Describe the bug**
Whenever an extended test is created and completed successfully (i.e. reload test), there is an error in the console:
`Uncaught TypeError: data.push is not a function`. This issue only happens on final successful test which removes the extended test. As a result, message on the chat doesn't show information about completition.

**To Reproduce**
Create an extended reload test, make first test partially successful - a massage with progress will be added to the chat. Roll second successful test - a message without a progress is shown and - only that test was successfull 

the issue is located in: `  async handleExtendedTest(test) {`

once following lines are executed, an error occurs in .push method: 

```
      else if (item.system.completion.value == "remove") {
        await this.deleteEmbeddedDocuments("Item", [item._id]) //this line gets executed 
        this.deleteEffectsFromItem(item._id)
        item = undefined
      }
      displayString = displayString.concat(`<br><b>${game.i18n.localize("Completed")}</b>`)
    }

    test.result.other.push(displayString) //this line throws an error as result.other changes from empty array to empty string. 
```

I think that changing all occurrences in the code of other.concat() to other.push would resolve the issue in more elegant way, but for now i went with following custom change: 

```
      displayString = displayString.concat(`<br><b>${game.i18n.localize("Completed")}</b>`)
    }

    test.result.other.push(displayString)
        
    if (item.system.SL.current >= item.system.SL.target) {
      if (item.system.completion.value == "reset") {
        item.system.SL.current = 0;
      }
      else if (item.system.completion.value == "remove") {
        await this.deleteEmbeddedDocuments("Item", [item._id])
        this.deleteEffectsFromItem(item._id)
        item = undefined
      }
    }

    if (item)
      this.updateEmbeddedDocuments("Item", [item]);
    
  }
```

**Screenshots**
n/a

**Version Numbers**
PLEASE PROVIDE YOUR FOUNDRY, SYSTEM, and MODULE VERSIONS (where applicable) 

Foundry: 10.286
wfrp4e: 6.1.3
wfrp4e-core: x

**Comment by moo-man** [comment]
I can't reproduce this exactly, but I know it happens and it's been a bit of a thorn, the whole `other` property is a bit of a mess. I've changed it to `preData.other` which should always be an array (then turned into `result.other`)
