### ISSUE TITLE
Updating Core Rulebook module creates top-level entries rather than folders

### ISSUE THREAD

**Issue by Jagusti** [moo-man/WFRP4e-FoundryVTT#1286]
**Describe the bug**
In an existing world  originally created pre-v10, updating (with full overwrite checks,  rather than initialising) the Core module creates v10 style paged journals at the top level, rather than inside a top level Core Rulebook folder. 

Additionally, the new top level Skills and Talents journal (which was also the name of a subfolder under Character in previous versions) is not created at all, so none of the new pages for those are added. 

Old journal entries aren't removed. 

**What should happen:** 
- the Core Rulebook folder created at top level
- all new journal pages added within that rather than top level

**What else should happen:** (parking this here, but happy to move it to a separate enhancement request. 
- an option to remove existing old Core journal content (perhaps excluding name changes)
- a warning if that option isn't taken about probable duplicate entries
- old journal entries removed if that option is taken

**To Reproduce**

1. Load a world that is migrated to FVTT v10, but where Core content has previously been initialized prior to module version 3.0.0. 
2. Go to Settings, Core Rulebook Module > Setup > Update 
3. Don't change any checkbox options (so keep all overwrites and exclusion defaults)
4. Run Update
5. View Journal sidebar to see new entries appended to journal directory at top level

**Screenshots**
On the left: initializing in a new v10 world
On the right: initializing in an existing pre-v10 world
![image](https://user-images.githubusercontent.com/521096/192007446-b5bf83ca-4141-46cf-96f0-568f205d3e23.png)

**Version Numbers**
Foundry: 10.286
wfrp4e: 6.1.3
wfrp4e-core: 3.0.0

**Comment by Jagusti** [comment]
This happens with other new content introduced in 3.0.0, presumably because the RollTable folder was called Core rather than Core Rulebook, they are dropped in at top level.

What should happen: when updating the module, if the Core folder exists (and has Core module tables in it), it should be renamed Core Rulebook before updating with new tables.

**Comment by moo-man** [comment]
This has always happened with all the modules

**Comment by moo-man** [comment]
I'm going to go ahead and close this as I think the need for automatic transitioning from v9 -> v10 is mostly past and isn't worth the effort.
