### ISSUE TITLE
[WFRP4e Core] Initialization bug and scene notes

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1303]
A couple of small issues:
- When initializing the core module, the Career - High Elf and Career - Human (Reiklander) tables are placed at top-level, not with the other career tables. It seems that they lack "initialization-folder".
- Scenes no longer have scene notes. Maybe because of the new journals?<br/>**From**: Txus#5021<br/>foundry: 10.286<br/>wfrp4e: 6.1.4<br/>wfrp4e-core: 3.0.1<br/>Active Modules: advanced-macros, alternative-rotation, audio-preview, autoanimations, babele, betterroofs, breaktime, color-picker, colorsettings, combat-carousel, combatbooster, compendium-folders, curtain-animations, dice-so-nice, drag-ruler, fateroll, foundryvtt-es, foundryvtt-show-notes, foundryvtt-simple-calendar, fxmaster, give-item, healthEstimate, hidden-tables, hide-gm-rolls, introduce-me, JB2A_DnD5e, koboldworks-ready-up, levels, lib-wrapper, qol-maximize-reopened-sheets, remote-highlight-ui, sequencer, smalltime, socketlib, splatter, token-action-hud, tokenmagic, tokenmagic-automatic-wounds, wall-height, wfrp4e-castellano, wfrp4e-character-details, wfrp4e-fx, wfrp4e-gm-toolkit

**Comment by Txus5012** [comment]
Thanks. The journal entry is back in the Reikland map.
But those careers are now placed in "Character Creation", instead of "Career Tables". (Again, it's not a big issue)
