### ISSUE TITLE
[WFRP4e System] Automatic Roll reversal not working in FVTT v10

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1313]
The talents with the 'roll reversal' effects are not working anymore. Tested with Bookish and Alley Cat.
<br/>**From**: LeRatierBretonnien#2065<br/>foundry: 10.287<br/>wfrp4e: 6.1.4<br/>wfrp4e-core: 3.0.1<br/>wfrp4e-dotr: 2.3.4<br/>wfrp4e-eis: 2.3.4<br/>wfrp4e-ua1: 2.3.2<br/>Active Modules: lib-wrapper, wfrp4e-eis-maps, wfrp4e-gm-toolkit, wfrp4e-pbth-maps, wfrp4e-unofficial-grimoire

**Comment by moo-man** [comment]
Could not reproduce: using Alley Cat


![Image](https://user-images.githubusercontent.com/28637157/201798921-824cf0f3-7f23-4dd5-b073-89484a9aa7a9.png)

**Comment by sladecraven** [comment]
Well, tested  again in a fresh world, and it works. You can close.
