### ISSUE TITLE
[WFRP4e System] Blinded Effect

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1314]
If the id of the Blinded condition is changed to "blind", applying the Blinded effect will apply Foundry's new blind effect (removes vision while the condition is active).
Of course, all references to the "blinded" id should be changed too.<br/>**From**: Txus#5021<br/>foundry: 10.287<br/>wfrp4e: 6.1.4<br/>wfrp4e-core: 3.0.1<br/>Active Modules: advanced-macros, alternative-rotation, audio-preview, autoanimations, babele, betterroofs, breaktime, color-picker, colorsettings, combat-carousel, combatbooster, compendium-folders, curtain-animations, dice-so-nice, drag-ruler, fateroll, foundryvtt-es, foundryvtt-show-notes, foundryvtt-simple-calendar, fxmaster, healthEstimate, hidden-tables, hide-gm-rolls, introduce-me, JB2A_DnD5e, koboldworks-ready-up, levels, lib-wrapper, qol-maximize-reopened-sheets, remote-highlight-ui, sequencer, smalltime, socketlib, splatter, token-action-hud, tokenmagic, tokenmagic-automatic-wounds, wall-height, wfrp4-wfrp4e-npc-generator, wfrp4e-castellano, wfrp4e-character-details, wfrp4e-fx, wfrp4e-gm-toolkit

**Comment by fmunoz-geo** [comment]
But the Blinded condition in WFRP, IIRC, just impairs vision not completely remove it.

**Comment by Txus5012** [comment]
Yes, you're right.
