### ISSUE TITLE
[WFRP4e System] Error in applyFear function

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1316]
Hello,

I found an error un V10 (WFRP4E core) in wfrp4e.js (line 15100) in the function applyFear(...)
There is a an assignation -> fear.system.SL.target = value;
We have to write this now : fear.data.SL.target = value;

Best regards,
@Prolice#9101<br/>**From**: Prolice#9101<br/>foundry: 10.287<br/>wfrp4e: 6.1.4<br/>wfrp4e-core: 3.0.1<br/>wfrp4e-eis: 2.3.4<br/>wfrp4e-starter-set: 2.3.4<br/>Active Modules: babele, combat-utility-belt, combatbooster, cursor-hider, dice-so-nice, easy-target, forien-quest-log, foundry-combat-focus, fr-core, fvtt-token-targeting, fxmaster, healthEstimate, JB2A_DnD5e, lessfog, lib-wrapper, LockView, pointer, popout, settings-extender, token-action-hud, tokenmagic, torch, vtta-tokenizer, wfrp4e-character-details, wfrp4e-eis-maps, wfrp4e-gm-toolkit, wfrp4e-random-treasure, wfrp4e-unofficial-grimoire, wh4-fr-translation

**Comment by prolice** [comment]
My mistake, it is in fact in the system file wfrp4e.js
![image](https://user-images.githubusercontent.com/48445910/194722111-fee6ab43-162c-40cf-a627-d5e6d99146ed.png)

**Comment by moo-man** [comment]
This was fixed in https://github.com/moo-man/WFRP4e-FoundryVTT/commit/b9afc40c118d6fc99be988c89e9d88e3da5c9c71
