### ISSUE TITLE
[Rough Nights & Hard Days] Gnome not available during chargen

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1321]
Gnome is unavailable during chargen when the RNHD module is active

Removing line 3 of chargen-gnome.js fixes this. 
`WFRP4E.species["gnome"] = "Gnome"`
<br/>**From**: Jagusti#3610<br/>foundry: 10.287<br/>wfrp4e: 6.1.4<br/>wfrp4e-core: 3.0.1<br/>wfrp4e-rnhd: 2.4.2<br/>Active Modules: wfrp4e-gm-toolkit

**Comment by BoltsJ** [comment]
For me the problematic line was line 2: `WFRP = game.wfrp4e.config`, and I believe because 6.1.4 changed the global `WFRP` object to `const`

**Comment by moo-man** [comment]
> For me the problematic line was line 2: `WFRP = game.wfrp4e.config`, and I believe because 6.1.4 changed the global `WFRP` object to `const`

6.1.4 didn't change that file at all, it's been `const` for the last two years
![image](https://user-images.githubusercontent.com/28637157/195725228-86b3595a-b081-442f-a629-07d0de2df938.png)
