### ISSUE TITLE
[WFRP4e Core] Missing text on The Aethyr page in Magic rules

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1325]
After updating to V10 on Foundry and reinitializing the Core contents in my game I went through the new journal entries and noticed that the "The Aethyr" page in the "Magic" rules journal is blank.<br/>**From**: Ursur1minor#4715<br/>foundry: 10.288<br/>wfrp4e: 6.1.4<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-archives1: 2.4.1<br/>wfrp4e-core: 3.0.1<br/>wfrp4e-dotr: 2.3.4<br/>wfrp4e-eis: 2.3.4<br/>wfrp4e-starter-set: 2.3.4<br/>Active Modules: actually-private-rolls, betterroofs, combat-enhancements, combat-utility-belt, compendium-folders, dice-calculator, drag-all-to-hotbar, drag-ruler, fast-flip, find-the-culprit, foundryvtt-simple-calendar, fxmaster, healthEstimate, levels, lib-changelogs, lib-wrapper, LightsHUD, monks-active-tiles, multilevel-tokens, parallaxia, perfect-vision, permission_viewer, pointer, searchanywhere, socketlib, soundfxlibrary, wall-height, warpgate, weatherblock

**Comment by moo-man** [comment]
There is no text for schilderheim

**Comment by Txus5012** [comment]
There is, page 282.

**Comment by moo-man** [comment]
This is very strange because this isn't a new thing, it hasn't had text since the core module's release because I couldn't find any (only the hook).
