### ISSUE TITLE
[WFRP4e Core] Spectators

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1326]
The module treats players as spectators even though they have character cards assigned to them<br/>**From**: darksilent88@gmail.com<br/>foundry: 10.288<br/>wfrp4e: 6.1.4<br/>wfrp4e-core: 3.0.1<br/>Active Modules: Custom-Token-Animations, DragTransfer, LightSwitch, NotYourTurn, SDRA04, SoundBoard, SoundBoard-BlitzCommunityPack, SoundBoard-BlitzFreePack, about-face, about-time, advanced-macros, adventuremusic, animated-spell-effects, autoanimations, background-volume, calendar-weather, chat-portrait, colorsettings, combat-carousel, danger-zone, dice-calculator, dice-so-nice, dlopen, dynamic-illumination, entice-with-dice-so-nice, foundryvtt-reward-experience, foundryvtt-simple-calendar, graham-plowmans-music-pack, ivan-duch-music-packs, jaamod, jb2a_patreon, lessfog, lib-wrapper, lordudice, merchantsheetnpc, michaelghelfi, nice-more-dice, perfect-vision, pings, player-pronouns, quick-actions, quick-combat, sequencer, settings-extender, smalltime, socketlib, sound-link, splatter, sync-token-name, tabletop-music-bazaar-free, tabletop-rpg-music, tagger, talisdice, token-action-hud, torch, torchlight, trigger-happy, vtta-tokenizer, warpgate, wcube, weather-control, wfrp4-wfrp4e-npc-generator, wfrp4e-character-details, wfrp4e-gm-toolkit, wfrp4e-laws-pet-shoppe, forge-vtt

**Comment by Jagusti** [comment]
I think Spectators is just a GM Toolkit thing, so this may have nothing to do with Core. Disabling the module might be one way to verify.

**Comment by moo-man** [comment]
Closing this until more details are provided (also disable all those modules and see if it's resolved)
