### ISSUE TITLE
[WFRP4e System] /char command broken

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1327]
In latest release, WFRP4 + Core module only, English language.
No other module.
Core module initialized.
Command /char -> select race (human) -> select Default -> crash .

<br/>**From**: LeRatierBretonnien#2065<br/>foundry: 10.288<br/>wfrp4e: 6.1.4<br/>wfrp4e-core: 3.0.1<br/>Active Modules:

**Comment by sladecraven** [comment]
![image](https://user-images.githubusercontent.com/1085008/197243181-11770d71-0cb3-494f-b940-c3becae23299.png)

**Comment by sladecraven** [comment]
Does not work also with subspecies anyway.

**Comment by sladecraven** [comment]
Well really simple, I created a whole new world to test it, with only system+core module, nothing else.
Module Initialization, then /char -> bug

**Comment by moo-man** [comment]
Right, what I mean is I don't get that error
