### ISSUE TITLE
[WFRP4e Core] First Potent of Amul script updates Fortune Point as NaN

### ISSUE THREAD

**Issue by SimonR22** [moo-man/WFRP4e-FoundryVTT#1328]
**Describe the bug**
When casting successfully, script for the spell First Potent of Amul returns NaN as a result. Then Fortune Point value is no longer editable via the character sheet.

Script is the following : 

**To Reproduce**
Try to cas successfully First Potent of Amul

**Screenshots**
![image](https://user-images.githubusercontent.com/45527224/197533252-db565a9e-1d24-4713-b7c6-de68f16faec4.png)

**Version Numbers**
PLEASE PROVIDE YOUR FOUNDRY, SYSTEM, and MODULE VERSIONS (where applicable) 

Foundry: 10.288
wfrp4e: **6.1.4**
wfrp4e-core: **3.0.1**
wfrp4e-starter-set: N/A
wfrp4e-rnhd: N/A
wfrp4e-eis: **2.3.4**
wfrp4e-ua1: N/A
wfrp4e-dotr: N/A
wfrp4e-archives1: N/A
wfrp4e-middenheim: N/A
wfrp4e-archives1: N/A
wfrp4e-pbtt:N/A
wfrp4e-altdorf: N/A
wfrp4e-ua2: N/A
wfrp4e-owb1:N/A
wfrp4e-horned-rat: N/A
wfrp4e-empire-ruins:N/A

Other modules installed : 
![image](https://user-images.githubusercontent.com/45527224/197533940-4992da9e-d665-40f7-b3b8-6e9c1daf08ee.png)

**Comment by moo-man** [comment]
Could not reproduce. As usual, the first step in troubleshooting should be disabling modules. Secondly, make sure the spell you're using is up to date (i.e. fresh from the compendium).

**Comment by moo-man** [comment]
Closing as stale
