### ISSUE TITLE
[WFRP4e System] Career roll doesn't work in french 

### ISSUE THREAD

**Issue by Sayama3** [moo-man/WFRP4e-FoundryVTT#1331]
**Describe the bug**
On the French version of the game, when rolling a career (from the "generate a new character" button) the career from the random table isn't found.
![image](https://user-images.githubusercontent.com/39456336/198041239-50b694f7-d96f-48c5-80a8-8fcc88ddad0e.png)
![image](https://user-images.githubusercontent.com/39456336/198040578-13615860-97de-4e8a-b859-599fb752f1af.png)

**To Reproduce**
 - Put foundryVTT in french
 - Create a new World
 - Import the module mentionned bellow
 - Initialize the world as usual
 - Create a new character
![image](https://user-images.githubusercontent.com/39456336/198041570-43873c53-91e3-47e7-85d9-86c890b1c51a.png)
 - Roll for a career
![image](https://user-images.githubusercontent.com/39456336/198041239-50b694f7-d96f-48c5-80a8-8fcc88ddad0e.png)

**/!\\** Sometimes, the name of the career is the same in english and in french so it work. **/!\\** 

**Version Numbers**
Babele: 2.3.2
FR - Traduction du core: 10.288.1
libWrapper: 1.12.10.0
WFRP4e - Core Module en français: 6.2.13
WFRP4e - Core Rulebook Module: 3.0.1

Foundry: 10.288
wfrp4e: 6.1.4
wfrp4e-core: 3.0.1

**Solution**
After searching for a bit, I found at that instead of getting the name of the career from the text result of the roll table.
We could use the UUID that's contain in it to make a search and then, from this document, getting the name of the career.

I've test it out and it works for me

Here the code of the solution :
Should be for the [char-gen.js](https://github.com/moo-man/WFRP4e-FoundryVTT/blob/cc4d8acd37e9f8818610563daa8d8368b443900a/modules/apps/char-gen.js#L196) file.
```js
/**
* Roll a career and display the instructions, as well as post the career to chat.
* 
* @param {String} species Species key
* @param {Number} exp Exp value to show
* @param {Boolean} isReroll Whether this career is from a reroll
*/
async rollCareer(isReroll=false) {
this.careerExp = 0;
if (isReroll)
  this.careerExp = game.wfrp4e.config.randomExp.careerReroll;
else
  this.careerExp = game.wfrp4e.config.randomExp.careerRand;

let rollSpecies = this.species;
if (this.species == "human" && !this.subspecies)
  this.subspecies = "reiklander";
if (this.subspecies && game.wfrp4e.tables.findTable("career", rollSpecies + "-" + this.subspecies))
  rollSpecies += "-" + this.subspecies;
let roll = await game.wfrp4e.tables.rollTable("career", {}, rollSpecies);

let text = roll.object.text;

try {
  let careerDocument = await fromUuid(roll.result.replace(/.*\[([^\]]+).*/gm, "$1"));
  text = careerDocument.name;
} catch (e) {
  try {
	// Extract career name
	text = Array.from(roll.object.text.matchAll(/{(.+?)}/gm))[0][1];
	if (!text)
	  text = roll.object.text;
  }
  catch(e)
  {
	text = roll.object.text;
  }
}

this.displayCareer(text, isReroll);
}
```

**Comment by moo-man** [comment]
Unless input from @sladecraven says otherwise I'm going to close the issue, additionally, chargen is revamped in the next update so it could be fixed on it's own
