### ISSUE TITLE
[WFRP4e System] Can't open the character sheet

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1337]
Hi after updating and migrating the world into Foundry 10 I can't open any Character sheets.
Is ther a workaround?
Greetings
<br/>**From**: Harlequinn #3042<br/>foundry: 10.288<br/>wfrp4e: 6.1.4<br/>wfrp4e-core: 3.0.1<br/>wfrp4e-eis: 2.3.4<br/>wfrp4e-starter-set: 2.3.4<br/>Active Modules: pdf-sheet, pdfoundry, wfrp4e-gm-toolkit

**Comment by CanisLupus999** [comment]
Launch the world in safe configuration and retry. Also, I strongly recommend joining Foundry discord, as it's easier to troubleshoot these kind of issues there.

**Comment by moo-man** [comment]
Closing due to lack of details
