### ISSUE TITLE
[WFRP4e Core] Symptoms issues

### ISSUE THREAD

**Issue by Txus5012** [moo-man/WFRP4e-FoundryVTT#1342]
**Describe the bug**
I found issues with some symptoms. Happens when applying a system effect or an active disease:

- Buboes: Doesn't apply the modifier for characteristic rolls. .key must be deleted in this line.

![Buboes](https://user-images.githubusercontent.com/87753744/202144314-21aa05fc-95eb-4705-a693-dc7884629546.jpg)

- Gangrene: Throws an error. There is an extra "}" in this line.
![Gangrene](https://user-images.githubusercontent.com/87753744/202147495-6430be4b-e5e5-46cf-8396-1be8ebb9d954.jpg)

- Nausea: Doesn't add the stunned condition. Don't know how to fix this one.

**To Reproduce**
Add the system effect for these symptoms, or an active disease with these symptoms.

Foundry: 10.290
wfrp4e: 6.1.4
wfrp4e-core: 3.0.1

**Comment by moo-man** [comment]
Could not reproduce the Nausea issue
