### ISSUE TITLE
[WFRP4e System] Allow an option to configure an external folder for icons

### ISSUE THREAD

**Issue by sladecraven** [moo-man/WFRP4e-FoundryVTT#135]
Same idea than for sounds, in order to let users specify an external folder

**Comment by moo-man** [comment]
Not sure I understand this, you can put icons in say, Data folder, and use them

**Comment by sladecraven** [comment]
The idea was to provide a existing folder setup by the GM that contains all icons with the same name than in the compendium, and then automatically retrieve the icons from the new folder, in order to avoid selecting icons hand by hand.
Maybe unuseful if new official icons are in the pipe, anyway.

**Comment by moo-man** [comment]
I'm going to go ahead and close this, while it was easy to do with sound effects, I don't want to interfere with the normal Foundry workflow of assigning icons and potentially mess with user data.
