### ISSUE TITLE
[WFRP4e System] WoM Overcasting rules do not add damage correctly

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1358]
When using the overcasting buttons after rolling a casting test, the damage correctly increases when clicking the damage button. 

However, after this, when you target and then click the "unopposed" button to resolve the casting, the final chat card displays the wrong damage value.<br/>**From**: The First#7330<br/>foundry: 10.288<br/>wfrp4e: 6.2.1<br/>wfrp4e-archives1: 2.4.1<br/>wfrp4e-archives2: 3.0.0<br/>wfrp4e-core: 3.0.2<br/>wfrp4e-dotr: 2.3.4<br/>wfrp4e-eis: 2.3.4<br/>wfrp4e-empire-ruins: 3.0.1<br/>wfrp4e-horned-rat: 2.0.1<br/>wfrp4e-pbtt: 2.2.3<br/>wfrp4e-rnhd: 3.0.0<br/>wfrp4e-starter-set: 3.0.0<br/>wfrp4e-ua1: 2.3.2<br/>Active Modules: about-face, colorsettings, dd-import, drag-ruler, easy-target, fast-flip, foundryvtt-simple-calendar, lib-wrapper, mcc, popout, quick-insert, settings-extender, smalltime, socketlib, token-action-hud, tokenmagic, wfrp4e-gm-toolkit, forge-vtt, forge-vtt-optional

**Comment by TheFirst05** [comment]
![image](https://user-images.githubusercontent.com/96636889/202914938-410544bc-b5d3-4081-b35c-747f817a302a.png)
Here is a screenshot. To reproduce:

Successfully cast a damaging spell. Assign extra SL to increase damage. Target a token and click "oppose with targets". Resolve the opposed Test card by clicking "unopposed".

**Comment by moo-man** [comment]
Fixed in 6.2.2
