### ISSUE TITLE
Define a default CSS text color on an application level

### ISSUE THREAD

**Issue by Moerill** [moo-man/WFRP4e-FoundryVTT#136]
Coming from this issue:
https://github.com/Moerill/fvtt-pointer/issues/6

![image](https://user-images.githubusercontent.com/26152015/98462651-21d05d00-21b6-11eb-8c36-08d76571c924.png)

What is happening?
I (and probably many other mods with custom apps) do not define a text color and background, so the theme can take care of that. But most text colors you define in your system theme do only get applied on more specific classes/parts of an application and not on the higher level. So if someone doesn't follow that class schema, it will just be default FVTTs dark gray, which is nigh unreadable.
Proposed solution:
add a css rule, that overrides the default fvtt app text color rule ``.window-app .window-content { color: #191813; }`` with something that is readable on most backgrounds of default apps for your system.

**Comment by valberg** [comment]
I'm having this same issue with many help pages and such defined by modules.
