### ISSUE TITLE
Suspicious code in TestWFRP.runPreEffects. Potential security issue!

### ISSUE THREAD

**Issue by heretyk999** [moo-man/WFRP4e-FoundryVTT#1367]
**Describe the bug**
I found something in my opinion suspicious in source code of the module. In TestWFRP.runPreEffects, there is something that looks like obfuscated code - inner function called "_0x402b".
There is a commit 04c0b902a6f6e44163d8b8341bef3db93c63f50a from Sep 29 titled "version numbers", which indeed bumps version, but also introduces the previously mentioned code.

Basically, it all looks suspicious.

**Comment by moo-man** [comment]
Non-issue

Contact me privately if you want to discuss
