### ISSUE TITLE
Engaged status effect

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1380]
When pick Engaged status effect on character, character looses all advantages. Make sense for other status effect, but should not remove advantages when click Engaged.

![obraz](https://user-images.githubusercontent.com/99994770/205488400-761e3c68-8105-4ac7-9293-62f146a2330f.png)

**Comment by Jagusti** [comment]
Feel free to thow this over to the GM Toolkit issue bank https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/issues

**Comment by GregorHak** [comment]
https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/issues/206
