### ISSUE TITLE
Extended test

### ISSUE THREAD

**Issue by Ryach** [moo-man/WFRP4e-FoundryVTT#1414]
Extender test missing some important functionality if I can ask for adding options to it? Thank you

- Add a option to add second skill or characteristic to the test (some tests in Warhammer allow to test combined skills, and both need to be passed to archive success)
- Add option to choose the default difficulty level of the test
- Add an option to edit the amount of success in progression track

**Comment by GregorHak** [comment]
Also can Extended tests tab can be scrollable under base and advanced skills in skills tab ? Now you must click arrow, and then you can't view skills but only Extended test and vice versa. Something like on the image would be nice
![obraz](https://user-images.githubusercontent.com/99994770/220639922-5f7a1378-8b4e-46ce-8fbf-77ff31686759.png)

**Comment by moo-man** [comment]
Unfortunately I don't think I'll be implementing your first point. I think there are some ambiguities on how Combining Tests actually interact with Extended Tests.

I have implemented your second request, default difficulties. 

The third request is already implemented, see point **6. Extended Test Row** https://github.com/moo-man/WFRP4e-FoundryVTT/wiki/Sheet-Tabs#extended-tests

**Comment by GregorHak** [comment]
@moo-man Did you consider my idea?

**Comment by moo-man** [comment]
Unfortunately won't be happening, the CSS here is tricky and I want to avoid scrollbars within scrollbars where I can.
