### ISSUE TITLE
[WFRP4e System] Shooting at engaged targets

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1429]
The code:
     if (this.options.engagedModifier) {
        let unmodifiedTarget = target - this.options.engagedModifier;
		let unmodifiedTarget = target
        if (this.result.roll > unmodifiedTarget) {
          this.result.other.push(game.i18n.localize("ROLL.HitAnotherEngagedTarget"));
        }
      }
is in the wrong place, its currently only being checked when the roll is a success (it should only check when the test is a failure and the unmodifiedTarget number already includes a -20 so the "- this.options.engagedModifier;" part is also wrong.<br/>**From**: Totalgit#8320<br/>foundry: 10.291<br/>wfrp4e: 6.3.1<br/>wfrp4e-core: 3.0.4<br/>wfrp4e-eis: 3.0.1<br/>wfrp4e-pbtt: 2.2.3<br/>Active Modules: about-face, about-time, autoanimations, color-picker, colorsettings, combat-carousel, compact-compendium-list, df-manual-rolls, dfreds-droppables, dice-calculator, dice-so-nice, drag-ruler, flying-tokens, force-client-settings, foundryvtt-arms-reach, foundryvtt-simple-calendar, introduce-me, jb2a_patreon, lib-wrapper, mkah-compendium-importer, module-credits, monks-hotbar-expansion, monks-little-details, multi-token-edit, permission_viewer, scene-transitions, sequencer, smarttarget, socketlib, splatter, stairways, times-up, token-action-hud, token-auras, token-ease, token-mold, tokenmagic, turnAlert, wfrp4-wfrp4e-npc-generator, wfrp4e-gm-toolkit, wfrp4e-pbth-maps

**Comment by totalgit** [comment]
Pc has ranged skill of 68, shot at target with engaged, had -20 penalty. rolled 42 and it said "oops you shot wrong target". 42 vs 48 is a successful shot, edited the roll with 27,28 & 29 and 27-28 were fine, a result of 29 showed the "oops" message again. So its appearing after skill - 40 instead of 20. I did some looking and the check happens in

  // ********** Success **********
    else if (this.result.roll <= 5 || this.result.roll <= target) {
      description = game.i18n.localize("ROLL.Success")
      outcome = "success"

This part of the code, when it needs to be placed after

    // ********** Failure **********
    if (this.result.roll >= 96 || (this.result.roll > target && this.result.roll > 5)) {
      description = game.i18n.localize("ROLL.Failure")
      outcome = "failure"
      if (this.result.roll >= 96 && SL > -1)
        SL = -1;
this part. I put it here in my own version and removed the "-this.options.engagedModifier;" and it works as intended for me now.

**Comment by moo-man** [comment]
This is a bit confusing because currently the engaged modifier is saved as a positive number 

```js
      if (item.attackType == "ranged" && target && target.hasCondition("engaged")) {
        modifier -= 20;
        tooltip.push(`${game.i18n.localize("EFFECT.ShootingAtEngagedTarget")} (-20)`);
        options.engagedModifier = 20; 
      }
```
`options.engagedModifier = 20;`

Then is subtracted from the target, so the unmodified target is *less* than the computed one.
```js
      if (this.options.engagedModifier) {
        let unmodifiedTarget = target - this.options.engagedModifier;
        if (this.result.roll > unmodifiedTarget) {
          this.result.other.push(game.i18n.localize("ROLL.HitAnotherEngagedTarget"))
        }
      }
```
Additionally, `if(this.result.roll > unmodifiedTarget)` needs to be swapped, as it's checking for a "success" with the unmodified target.

See the commit for the fix
