### ISSUE TITLE
[WFRP4e System] Conditions Blind, Deaf & Entangle do not give penalties in roll dialogue

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1430]
(For bookkeeping's sake)

Opening the roll dialogue with Blind, Deaf or Entangle throws an error, and none of the penalties can be added to the modifier boxes.

(first found by Totalgit, via discord).<br/>**From**: The First#7330<br/>foundry: 10.291<br/>wfrp4e: 6.3.1<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-archives1: 2.4.1<br/>wfrp4e-archives2: 3.0.2<br/>wfrp4e-core: 3.0.4<br/>wfrp4e-dotr: 2.3.4<br/>wfrp4e-eis: 3.0.1<br/>wfrp4e-empire-ruins: 3.0.2<br/>wfrp4e-horned-rat: 2.0.1<br/>wfrp4e-pbtt: 2.2.3<br/>wfrp4e-rnhd: 3.0.3<br/>wfrp4e-starter-set: 3.0.2<br/>wfrp4e-up-in-arms: 3.0.1<br/>Active Modules: about-face, colorsettings, dd-import, drag-ruler, easy-target, fast-flip, foundryvtt-simple-calendar, item-piles, lib-wrapper, mcc, popout, quick-insert, settings-extender, smalltime, socketlib, times-up, token-action-hud, tokenmagic, wfrp4e-gm-toolkit, wfrp4e-random-treasure, forge-vtt, forge-vtt-optional

**Comment by TheFirst05** [comment]
Is it possible to add this bug to the 6.4 release? I think we got entangling issues twice within the last month or so, and we've no longer been able to simply click the entangling modifiers in the list of options. Instead having to manually input the modifier into the box.

This is the error we get when we open the roll dialog to make a test when suffering from one of these conditions:

![image](https://user-images.githubusercontent.com/96636889/226466043-4c5b0423-e710-4656-b3f6-7b92688e9130.png)

**Comment by moo-man** [comment]
Yeah, missed it, thanks
