### ISSUE TITLE
Decapitated critical

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1446]
When drag Decapitated critical (head) from core module in chat I got message: [object Promise]
![obraz](https://user-images.githubusercontent.com/99994770/220677337-481310ce-7087-495d-989f-3fea1bc3568d.png)

**Comment by moo-man** [comment]
I cannot reproduce, what do you mean by dragging it to chat? What are your precise reproduction steps.

**Comment by GregorHak** [comment]
https://user-images.githubusercontent.com/99994770/226208642-2133a23d-2859-4dae-aef3-e92089a1cb0f.mp4

**Comment by GregorHak** [comment]
![obraz](https://user-images.githubusercontent.com/99994770/226208685-18a7c4b7-24ec-4843-bc68-f6ad12465f49.png)
![obraz](https://user-images.githubusercontent.com/99994770/226208791-77472112-0c0a-4acf-b063-6831b2351c05.png)

![obraz](https://user-images.githubusercontent.com/99994770/226208706-a492e391-672a-4449-ae77-3c65d39c21cb.png)
![obraz](https://user-images.githubusercontent.com/99994770/226208715-d449cc1c-b9f3-4314-9980-70af1bc9d9bc.png)
![obraz](https://user-images.githubusercontent.com/99994770/226208749-c8be7b15-e929-4e1f-b8f1-dae126dadd13.png)
![obraz](https://user-images.githubusercontent.com/99994770/226208757-135ecd47-28b1-4174-8105-fc2ee9f8a6f0.png)
![obraz](https://user-images.githubusercontent.com/99994770/226208765-cd22e720-d987-4ac0-9c81-ae6aeadd5d2b.png)
![obraz](https://user-images.githubusercontent.com/99994770/226208777-45680051-aa23-4cb7-95f9-ec96a7717745.png)
