### ISSUE TITLE
[WFRP4e System] Advanced Skills getting populated with 0 advances on character creation

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1452]
Whenever I create a new character, they come with a ton of advanced skills with a 0 advancement, necessitating deleting them from the character sheet.

For instance: created a new character "Busker" and it had Art (0), Entertain (0), Melee (0), Ride (0) amongst others in the advanced skills tab.

I posted in the Foundry Discord with Screenshots. Please let me know if you need more information.<br/>**From**: datalink7a@gmail.com or datalink7#6983<br/>foundry: 10.291<br/>wfrp4e: 6.3.1<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-archives1: 2.4.1<br/>wfrp4e-archives2: 3.0.2<br/>wfrp4e-core: 3.0.4<br/>wfrp4e-dotr: 2.3.4<br/>wfrp4e-eis: 3.0.1<br/>wfrp4e-empire-ruins: 3.0.2<br/>wfrp4e-horned-rat: 2.0.1<br/>wfrp4e-middenheim: 2.4.2<br/>wfrp4e-pbtt: 2.2.3<br/>wfrp4e-rnhd: 3.0.3<br/>wfrp4e-starter-set: 3.0.2<br/>wfrp4e-ua1: 2.3.2<br/>wfrp4e-ua2: 2.0.0<br/>wfrp4e-up-in-arms: 3.0.1<br/>Active Modules: dice-so-nice, lib-wrapper, pin-cushion, socketlib, wfrp4e-eis-maps

**Comment by GregorHak** [comment]
Works as is should. These skills are Group skill. Check header above these skills

**Comment by moo-man** [comment]
The ones given in example are grouped, but there is actually an issue with advanced skills being given with 0 advances
