### ISSUE TITLE
[WFRP4e System] Roll table result not displayed after initiating roll from chat card

### ISSUE THREAD

**Issue by si-lang** [moo-man/WFRP4e-FoundryVTT#1466]
**Describe the bug**
Given a critical hit was accomplished and a chat card is displayed, a click on the "Critical" button triggers just the roll, but not drawing a result from the critical table.

**To Reproduce**
This issue is very hard to reproduce, because it is a multithreading issue. The described bug can only occur if a 3D dice module is installed, namely "Dice So Nice!". The problem was introduced in the following commit: https://github.com/moo-man/WFRP4e-FoundryVTT/commit/48aa77c34e0551f5de719834a0e27557604133b2

In modules/system/tables-wfrp4e.js there are the following lines:
```
      if (options.showRoll)
      {
        let msg = await roll.toMessage({rollMode : game.settings.get("core", "rollMode"), });
        if (game.dice3d)
          await game.dice3d.waitFor3DAnimationByMessageID(msg.id)
      }
```

A brief description of what is supposed to happen in order to establish naming for further reference:
When waiting for roll.toMessage() (Event 1) the animated roll in "Dice So Nice!" is triggered (Event 2), resolving the promise of Event 1 and setting a value in `msg` (Event 3). In waitFor3DAnimationByMessageID() (Event 4), there is a subscription to the Hook "diceSoNiceRollComplete" (Event 5), which is resolved by "Dice So Nice!", after the 3D roll completes (Event 6). Event 6 finally resolves the promise of Event 4 and continues the program flow (Event 7).

Currently the expected order of events is:
await 1 -> 2 -> resolve 1 -> 3 -> await 4 -> 5 -> 6 -> resolve 4 -> 7

Sadly, this event flow is not guaranteed, because when waiting in Event 1, it can happen, that "Dice So Nice!" already resolves its animation and triggers Event 6, while nobody is observing this Hook-call for the given message ID (which normally is initiated in Event 4) and therefore, Event 4 never resolves:
await 1 -> 2 -> 6 -> resolve 1 -> 3 -> await 4 -> 5 (Note: 7 is not executed, because 4 is never resolved!)

I can not reproduce this phenomenon on a "clean" instance (Foundry + wfrp4e + wfrp4e-core) reliably, but with my heavily modded world, this issue happens 100% of the time. - I hope I could narrow down this issue enough for you to spot the source of the problem and acknowledge, that it can occur independent of any installed modules (although I gladly append my module list for convenience).

One option to fix this issue is to start listening for "diceSoNiceRollComplete" up until we want to start Event 4. If the Hook was already called with the given message ID, we could simply skip Event 4 and continue with Event 7. - This solution feels awkward, imho.

Another, cleaner option would be to somehow get the message ID without triggering the "Dice So Nice!" roll, start Event 4 without subscribing, trigger the 3D roll separately, and finally await Event 4.

If I can provide any more hints on the problem, just let me know and keep up the good work!

**Version Numbers**
Foundry: 10.291
wfrp4e: 6.3.9
wfrp4e-core: 3.0.4
wfrp4e-eis: 3.0.1
Active Modules: SoundBoard (1.7.1), WhisperBox (3.0.0), _CodeMirror (5.58.3-fvtt5), _mathjs (7.5.1-fvtt2), _sortablejs (1.14.0-fvtt1), about-time (10.0.1), advanced-macros (1.19.5), ambientdoors (2.3.3), babele (2.3.4), betterroofs (1.7.6), chat-images (3.2), chat-notifications (1.2.5), clipboard-image (0.2.0), colorsettings (2.9.1), combat-enhancements (1.2.1), combat-utility-belt (1.10.4), combatbooster (3.5.1), df-architect (4.0.0), df-curvy-walls (3.4.0), df-settings-clarity (3.3.0), dfreds-droppables (2.0.5), dice-calculator (1.5.3), dice-so-nice (4.6.5), drag-ruler (1.13.3), dragupload (2.2.2), everybody-look (2.0.0), fogmanager (v1.2.8), foundryvtt-arms-reach (2.2.12), foundryvtt-simple-calendar (v1.3.75), fxmaster (3.5.2), gm-notes (7.10), hide-gm-rolls (0.13.0), initiative-double-click (1.6.1), lessfog (0.10.1), levels (3.7.5), lib-df-buttons (1.4.2), lib-wrapper (1.12.12.0), mcc (1.4.1), mobile-improvements (1.1.1), monks-common-display (10.2), multilevel-tokens (1.6.0), navigator (0.1), pdf-sheet (0.22.4), perfect-vision (4.1.17), permission_viewer (0.10.0), pings (1.4.0), polyglot (1.8.12), popout (2.10), select-tool-everywhere (1.4.1), settings-extender (1.2.1), smart-doors (1.4.1), socketlib (1.0.12), split-journal (1.2.0), token-action-hud (3.0.19), token-attacher (4.5.11), token-auras (2.3), token-hud-art-button (1.3.0), token-mold (2.15.4), token-tooltip-alt (3.1.5), tokenmagic (0.6.1.2), torch (2.6.0), touch-vtt (1.9.1), wall-height (4.9.3), wallter (0.1.5), weather-control (4.1.9), wfrp4e-character-details (1.2.0), wfrp4e-core (3.0.4), wfrp4e-eis (3.0.1), wfrp4e-eis-maps (6.0.0), wfrp4e-gm-toolkit (6.0.1), wfrp4e-laws-pet-shoppe (1.1.0), wfrp4e-ubersreik-maps (6.0.0)

Edit: Formatting

**Comment by moo-man** [comment]
The only time I've seen it be an issue is if the setting "show chat card immediately" is enabled, is that enabled in your "heavily modded world"?

**Comment by si-lang** [comment]
True, this setting is active and I can confirm, that this is the cause of the issue. - Thank you very much for your quick and helpful response!

Neverthess, I really appreciate not waiting for 3D dice to see the results and would prefer to keep this setting enabled. Is it within the scope of this project to tackle this bug?

**Comment by moo-man** [comment]
Not sure, I'll chat with @JiDW and see whose side the fix is on

**Comment by si-lang** [comment]
Very well! Thank you very much for your support!

**Comment by moo-man** [comment]
As of the most recent DSN version (4.6.7) this has been fixed
