### ISSUE TITLE
[Character Creation] Create and add option for species table combining "Archives of the Empire Vol. II" (Ogres) & "Rough Nights & Hard Days" (Gnomes)

### ISSUE THREAD

**Issue by Editorism** [moo-man/WFRP4e-FoundryVTT#1467]
Currently there are only separate options for species tables containing Ogres for owners of "Archives of the Empire Vol. II" **or** Gnomes for owners of "Rough Nights & Hard Days".

It would be nice to have an option for owners of both modules to benefit from the ownership of both of them.

**Comment by moo-man** [comment]
This table is not provided in any book, so will not appear in any module.

You can find community created tables for this on the discord
