### ISSUE TITLE
[Old World Bundle I] Flusskapitän Meinard Links has speed of 52

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1472]
Flusskapitän Meinard Links actor in old world bundle, something knocking adventure has a speed of 52 instead of 5.<br/>**From**: Joseph#8010<br/>foundry: 10.291<br/>wfrp4e: 6.3.1<br/>wfrp4e-core: 3.0.4<br/>wfrp4e-middenheim: 2.4.2<br/>wfrp4e-owb1: 2.0.1<br/>wfrp4e-ua1: 2.3.2<br/>wfrp4e-up-in-arms: 3.0.1<br/>Active Modules: dice-so-nice, wfrp4-wfrp4e-npc-generator, wfrp4e-actor-sheet-print, wfrp4e-gm-toolkit, wfrp4e-laws-pet-shoppe, wfrp4e-random-treasure

**Comment by GregorHak** [comment]
The fastes man alive
