### ISSUE TITLE
Carer leveling and Force advancement Indicator

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1473]
I have talent craftsman, so create trade (smith) skill, and edit it like in screen 1 (check Force advancement Indicator). Now I have complet puglist (1lvl pit fighter). I have all needed Characteristic (3 = WS, S, T) and skills (all of 8) listed at 1lvl pit fighter on 5 or more adv., and more than 1 talent from this career. I have 1 adv on trade (smith) skill. When click (screen 2) "+" = Create Item and choose Pit fighter lvl2 I must pay 200 xp. Which should be 100 xp. Problem solved when uncheck "Force advancement Indicator" from trade (smith).
 
 screen 1
![obraz](https://user-images.githubusercontent.com/99994770/224838074-e1c75d61-e5ec-41e4-9d80-72158e23d553.png)

screen 2
![obraz](https://user-images.githubusercontent.com/99994770/224839155-f1ef0f77-20f9-4eb1-8da2-0f91f1ece54d.png)

**Comment by moo-man** [comment]
The exp field in the career selector is freely editable for exactly this reason. If you want to automate this portion, simply add the skill to the career instead of forcing the Advancement Indicator
