### ISSUE TITLE
Cardsharp talent effect

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1474]
Hey, can you add Cardsharp talent effect?
📑Core - 134 - Cardsharp - You are used to playing, and winning, at cards, although your methods may involve a little cheating. When you successfully use Gamble or Sleight of Hand when playing cards, you can choose to either use your rolled SL, or the number rolled on your units die. So, a successful roll of 28 could be used for +8 SL. If you play a real card game to represent what is happening in-game, you may receive an extra number of cards per deal equal to your level in Cardsharp, then discard down to the appropriate hand-size before each round of play.

```
if (args.test.item && args.test.item.name == "Gamble" &&  (args.test.result.roll <= 5 || args.test.result.roll <= args.test.target))
{

let SL = Math.floor(args.test.target / 10) - Math.floor(args.test.result.roll / 10)
let ones = Number(args.test.result.roll.toString().split("").pop())

if (ones > SL)
   args.test.result.other.push(`<b>${this.effect.label}</b>: ${ones + args.test.successBonus + args.test.slBonus} SL if playing cards.`)
}

if (args.test.item && args.test.item.name == "Sleight of Hand" &&  (args.test.result.roll <= 5 || args.test.result.roll <= args.test.target))
{

let SL = Math.floor(args.test.target / 10) - Math.floor(args.test.result.roll / 10)
let ones = Number(args.test.result.roll.toString().split("").pop())

if (ones > SL)
   args.test.result.other.push(`<b>${this.effect.label}</b>: ${ones + args.test.successBonus + args.test.slBonus} SL if playing cards.`)
}
```

**Comment by Txus5012** [comment]
This could be added to the Diceman talent too.
