### ISSUE TITLE
[WFRP4e System] Can't create char due to missing species table

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1510]
Hi there!

I am not able to create a new character due to a missing species table.
I know I don't have the core module but is there a way to fill the character sheet manually without any tables?

Thx!

Best regards

Phil<br/>**From**: phiL0co#2085<br/>foundry: 10.291<br/>wfrp4e: 6.4.0<br/>Active Modules:

**Comment by moo-man** [comment]
You can create your own species table, but there is a lot of scripting needed to get the rest to work

**Comment by phiL0co** [comment]
OK, so the WFRP4e system is kind of useless without the core module, right?

**Comment by moo-man** [comment]
No, you can still create a character manually.

**Comment by phiL0co** [comment]
Could you give me a hint how that's supposed to work?

I can't fill in the species field and thus can't complete the character sheet.
I can't enter anything into the species field either.

Thx a lot!

**Comment by moo-man** [comment]
You can create characters manually by simply filling out the fields, such as characteristics, and providing your own Items such as skills and careers. The species tab is freely editable so I'm unsure what problems you're facing. 

More detailed help can be provided via the Discord servers.
