### ISSUE TITLE
[WFRP4e System] Aethyric Armour throws an error and fails when applied by players

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1511]
To reproduce:

Be a player.
Successfully cast Aethyric Armour
Click "Apply Aethyric Armour (Shadow)". (we don't target)
The message "Apply Effect request sent to GM" appears, but nothing happens.
The following error appears in the console log:

Uncaught TypeError: t.document is undefined
    targets https://assets.forge-vtt.com/bazaar/systems/wfrp4e/6.4.0/wfrp4e.js:7292
    applyEffectToTarget https://assets.forge-vtt.com/bazaar/systems/wfrp4e/6.4.0/wfrp4e.js:7292
    _onApplyEffectClick https://assets.forge-vtt.com/bazaar/systems/wfrp4e/6.4.0/wfrp4e.js:6154
    jQuery 2
        dispatch
        handle

A person with GM permissions has no issues with applying the effects.
This seems to be specific to spells, as another player has Blessing of Battle and has no problem applying the effect to their targets. <br/>**From**: The First#7330<br/>foundry: 10.291<br/>wfrp4e: 6.4.0<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-archives1: 2.4.1<br/>wfrp4e-archives2: 3.0.3<br/>wfrp4e-core: 3.1.0<br/>wfrp4e-dotr: 2.3.4<br/>wfrp4e-eis: 3.1.0<br/>wfrp4e-horned-rat: 2.0.1<br/>wfrp4e-pbtt: 2.2.3<br/>wfrp4e-rnhd: 3.0.4<br/>wfrp4e-up-in-arms: 3.0.2<br/>wfrp4e-wom: 3.0.0<br/>Active Modules: about-face, colorsettings, dd-import, drag-ruler, easy-target, fast-flip, foundryvtt-simple-calendar, item-piles, lib-wrapper, mcc, popout, quick-insert, settings-extender, smalltime, socketlib, stairways, times-up, token-action-hud, token-z, tokenmagic, wfrp4e-gm-toolkit, forge-vtt, forge-vtt-optional

**Comment by TheFirst05** [comment]
Since the previous update (6.5.0), the error message is different:

caught (in promise) TypeError: Cannot read properties of undefined (reading 'toObject')
    at wfrp4e.js:7471:126
    at Array.map (<anonymous>)
    at WFRP_Utility.applyEffectToTarget (wfrp4e.js:7471:106)
    at ChatWFRP._onApplyEffectClick (wfrp4e.js:6204:27)
    at HTMLElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
(anonymous) @ wfrp4e.js:7471
applyEffectToTarget @ wfrp4e.js:7471
_onApplyEffectClick @ wfrp4e.js:6204
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
