### ISSUE TITLE
[Enemy in Shadows] [WoM] Dhar spellcasting is broken using WoM rules

### ISSUE THREAD

**Issue by TheFirst05** [moo-man/WFRP4e-FoundryVTT#1520]
We've been testing out the Dhar spellcasting optional rule from Enemy in Shadows, and it is currently bugged in several ways, particularly when using the WoM optional Casting and Channelling rules. I've outlined the different ways in which it is bugged below. Some of these bugs might be related to issue #1519 

Optional Settings ticked:

- Dhar Spellcasting Rules (EiS module)
- Use Winds of Magic Overcast Rules
- Use Winds of Magic Channelling Rules

### **Feature Request: Dhar Overcasting with Winds of Magic rules**
Winds of Magic never clarified how Dhar overcasting works with the WoM overcasting system. A commonly suggested implementation is to double the amount of SL available to overcast for Dhar spellcasters. This isn't "official", but we'd greatly appreciate the option, even in the Homebrew settings, where we can use this implementation. As of current, EiS Dhar overcasting simply does not work with WoM settings.

### **Bug: Overchannelling a Dhar spell calculates available SL incorrectly when cast**
To reproduce:
- Channel a Dhar spell until you have channelled more SL than the CN of the spell.
- Cast the Dhar spell.
The system will incorrectly apply ALL the channelled SL to the Casting Test.

![image](https://user-images.githubusercontent.com/96636889/230138606-86550bab-3ea6-4877-b34e-36995142a8eb.png)

### **Bug: Chat cards using Dhar spellcasting do not remove the miscast and minor corruption prompts upon edit**
Usually if you edit a Chat card from a critical to a normal result, the chat card updates and removes the option to roll a critical. This does not work with Dhar spellcasting.
In the screenshot below, I modified the result from a normal result, to 55, then 88, then 77. Note that currently the system does not use WoM miscast rules.
![image](https://user-images.githubusercontent.com/96636889/230139319-41e30dac-cb31-4497-9707-34c6ad6b4a69.png)

### **Bug: Casting a Dhar spell and obtaining a Total Power result gives negative SL**
See the screenshot above. You can spend negative SL to increase the spellcasting options.
![image](https://user-images.githubusercontent.com/96636889/230142601-349329ae-b1df-4b12-bfe6-9a5c8ba2314c.png)

**Version Numbers**
Everything is up to date.

Foundry:
wfrp4e:
wfrp4e-core:
wfrp4e-rnhd:
wfrp4e-eis:
wfrp4e-dotr:
wfrp4e-archives1:
wfrp4e-middenheim:
wfrp4e-archives1:
wfrp4e-pbtt:
wfrp4e-altdorf:
wfrp4e-horned-rat:

**Comment by moo-man** [comment]
Fixed all except repeating prompts, which is not related to Dhar mechanics
