### ISSUE TITLE
[WFRP4e Core] typeerror: cannot read property 'data' of undefined by use of weapon

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#153]
I'd like to roll for a weapon (example Hand Weapon) in a combat...

...but there's always the "typeerror: cannot read property 'data' of undefined".

Anything I could do wrong?<br/>**From**: georg@kellendorfer.com<br/>wfrp4e: 3.0.2<br/>wfrp4e-core: 1.01

**Comment by moo-man** [comment]
I need more details on this. Can you contact me on Discord Moo Man#7518

**Comment by PatrickBauer** [comment]
@moo-man We could reproduce this error trying to use a melee weapon (I have no idea about warhammer, but a GM of our german discord asked to help :D) 

I could determine that this line threw the error: 

` let skillUsed = testData.extra.weapon.skillToUse;`

skillToUse is undefined at this moment, the next line which is trying to access `skillUsed` is getting the `'data' of undefined`error.

![image](https://user-images.githubusercontent.com/1428943/100020406-17ca7300-2de0-11eb-9869-9aa49b6a6ee7.png)

**Comment by moo-man** [comment]
Try updating WFRP and see if the issue persists.

**Comment by PatrickBauer** [comment]
@moo-man Yes, issue is still there, the update didn't help.

**Comment by moo-man** [comment]
Closing this as I believe it's been resolved by now in the current version. Please reopen if it persists.
