### ISSUE TITLE
Orc creature keeps resetting to maximum wounds

### ISSUE THREAD

**Issue by nyoung** [moo-man/WFRP4e-FoundryVTT#154]
I'm testing with a [Token] Orc that has been randomized and his wounds keep resetting to maximum, after taking multiple hits and applying the damage and even when I try to reduce his health manually. 

I have Foundry VTT 0.7.6, WFRP4e 3.0.0 and 1 active module - the WFRP Core Rules

Probably something I'm doing wrong as I'm really new to Foundry. Not sure what information I can provide to help troubleshoot.

**Comment by moo-man** [comment]
Please update the system
