### ISSUE TITLE
[BUG] Channel Until Ready 🪄

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1545]
In Magic tab, when try Channel spell there is a option to "Channel Until Ready". 

✨Now: When Miscast occurs (eg. roll double while filed channeling) "Channel Until Ready" do not care and keeps rolling channeling tests.

🌟Suggestion: When Miscast occurs (eg. roll duble while filed channeling) "Channel Until Ready" stops rolling channeling tests, you can check Miscast effect, and then again manually start "Channel Until Ready".

📝Why? Some Miscast may disturb channeling and wizard must start from scratch or test Cool.

**Comment by SimonasBanys** [comment]
jsut checked myself @moo-man doesnt stop channelling

**Comment by SimonasBanys** [comment]
![image](https://user-images.githubusercontent.com/31985858/233139972-b99c7a75-99fa-4f40-86d8-44cb6d1f193e.png)

**Comment by SimonasBanys** [comment]
looking at the testDuplicate roll, seems to check for misscast before rolling, which would return false

**Comment by moo-man** [comment]
And then we are back to https://github.com/moo-man/WFRP4e-FoundryVTT/issues/1349

A different solution is needed.

**Comment by SimonasBanys** [comment]
any chance we can potentially give as part of channel until ready request whats the CN to channel required? and then set that as while condition rather than true?

**Comment by moo-man** [comment]
The loop breaks when the CN is achieved or a miscast happens, I'm not inclined to make it more complicated and don't really see the use.
