### ISSUE TITLE
[Up In Arms] Magic isn't healing Bleeding

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1549]
In Up in Arms, any magic that heals Wounds also heals Bleeding Condition, but that doesn't seem to be working here.

This was tested with the Winds of Magic version of the Healing Light spell on a Creature, tested while the target Creature's token was both linked and unlinked to the actor. In both cases, the Creature's Wounds were healed, but it still retained its Bleeding Condition.

Modules active: Forge, Core, Winds of Magic, Up in Arms.<br/>**From**: Andres#7311<br/>foundry: 10.291<br/>wfrp4e: 6.4.0<br/>wfrp4e-core: 3.1.0<br/>wfrp4e-up-in-arms: 3.0.2<br/>wfrp4e-wom: 3.0.0<br/>Active Modules: forge-vtt

**Comment by moo-man** [comment]
Not possible to implement, no way to distinguish magical healing from non-magical.

**Comment by GregorHak** [comment]
Suggestion: Maybe add notification(reminder about that) in spell description or in chat when with success casting spell that heals.
