### ISSUE TITLE
v11 request - use new appliedEffects and allApplicableEffects functions instead of actorEffects

### ISSUE THREAD

**Issue by kaelad02** [moo-man/WFRP4e-FoundryVTT#1592]
**Is your feature request related to a problem? Please describe.**
I'm the maintainer/developer for Active Token Effects and got a PR to add support for this system. That module lets you use active effects to make changes to tokens and it's not respecting the tweaks made by this system, mainly that the effects that should be applied are in `actorEffects` of an actor instead of the default `effects` array. Right now we'll have to add a helper function to get the effects:

```js
const getEffects = (actor) => {
    if (game.system.id === "wfrp4e") return actor?.actorEffects;
    return actor?.effects;
};
```

Not a huge deal, but in v11 it can be better.

**Describe the solution you'd like**
Foundry v11 adds some enhancements to active effects and one of them are two new functions described in foundryvtt/foundryvtt#9185. I was wondering if you'd be willing to use those new functions, specifically `allApplicableEffects` instead of `actorEffects` to determine what effects should apply. The default version of `allApplicableEffects` already has the code to copy effects from items, like you have, so I think the only real tweak would be to apply the removal of effects in certain situations (e.g. when items are equipped).

Selfishly, if you make this change then I can just call `actor.appliedEffects()` to get the active effects that are applied to the actor instead of having to add a special check for the system like we're doing for v10.

**Comment by moo-man** [comment]
Thanks, I'll certainly be converting over to the new functions, as that was the point of `actorEffects`
