### ISSUE TITLE
[WFRP4e System] Group advantage not updated

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1605]
Token in active combat not recognised as combatant.
Notification "This actor must be part of a Combat in order to update group advantage."
Group advantage not updated. 
<br/>**From**: Jagusti#3610<br/>foundry: 11.299<br/>wfrp4e: 6.5.5<br/>wfrp4e-starter-set: 3.1.2<br/>Active Modules: LockView, breaktime, dice-so-nice, foundryvtt-simple-calendar, illandril-chat-enhancements

**Comment by Jagusti** [comment]
![groupadv_combatant gif](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/521096/5b49bb6f-b0fb-40c9-830f-22e89737bd49)
