### ISSUE TITLE
[Core Rulebook] money weight is being calculated incorrectly

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1611]
Money encumbrance in item correct, but math is wrong<br/>**From**: Perkuns#9523<br/>foundry: 11.299<br/>wfrp4e: 6.5.6<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-archives1: 3.0.0<br/>wfrp4e-archives2: 3.0.5<br/>wfrp4e-core: 3.1.2<br/>wfrp4e-dotr: 3.0.2<br/>wfrp4e-eis: 3.1.4<br/>wfrp4e-empire-ruins: 3.0.6<br/>wfrp4e-horned-rat: 2.0.1<br/>wfrp4e-middenheim: 3.0.0<br/>wfrp4e-owb1: 2.0.1<br/>wfrp4e-pbtt: 2.2.3<br/>wfrp4e-rnhd: 3.0.6<br/>wfrp4e-starter-set: 3.1.3<br/>wfrp4e-ua1: 3.0.1<br/>wfrp4e-ua2: 2.0.0<br/>wfrp4e-up-in-arms: 3.0.5<br/>wfrp4e-wom: 3.0.3<br/>Active Modules: about-time, acelib, breaktime, colorsettings, dice-calculator, dice-so-nice, drag-ruler, easy-target, find-the-culprit, foundryvtt-simple-calendar, gm-token-drag-visibility-v2, image-hover, lib-captions, lib-changelogs, lib-find-the-path, lib-wrapper, monks-scene-navigation, party-overview, permission_viewer, quick-insert, remote-highlight-ui, routinglib, scene-packer, socketlib, times-up, token-action-hud, token-auras, vtta-tokenizer, wall-height, wfrp4e-dotr-maps, wfrp4e-eis-maps, wfrp4e-pbth-maps, wfrp4e-ubersreik-maps

**Comment by SimonasBanys** [comment]
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/31985858/a5f8dbed-a2fb-4205-a1a5-23f5a52d624a)

**Comment by mathsteck** [comment]
Having exactly the same issue after the update:
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/3390366/a1668a45-0a0f-4dd4-a2d5-bcebaaf006f3)
