### ISSUE TITLE
[Core Rulebook] Encumbrance

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1613]
Hallo Moo-Man,

the encumbrance for worn armour isn't calculated in Ver 11 of FoundryVTT. It seems to just subtract 3 from any armour encumbrance rating instead of 1.

Thanks for all the great work! :-)<br/>**From**: RedFox#7511<br/>foundry: 11.299<br/>wfrp4e: 6.5.6<br/>wfrp4e-archives1: 3.0.0<br/>wfrp4e-archives2: 3.0.5<br/>wfrp4e-core: 3.1.2<br/>wfrp4e-dotr: 3.0.2<br/>wfrp4e-up-in-arms: 3.0.5<br/>wfrp4e-wom: 3.0.3<br/>Active Modules:

**Comment by Red-Fox4** [comment]
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/135282376/5760ac2e-409a-4258-b36b-e50696ad0e3e)
