### ISSUE TITLE
UiA Shieldsman in core mechanics?

### ISSUE THREAD

**Issue by Granathar** [moo-man/WFRP4e-FoundryVTT#1616]
I noticed that it's impossible to apply damage after defending with a shield because weapon in defense is not being recognized as weapon, unless you have Riposte with Fast weapon or Champion creature trait.

There is a dirty solution with adding Champion to character and then manually tracking if defense was made with a shield, then manually modifying the advantage, and then right click to apply damage, but yeah - it's quite dirty workaround that moves one micromanagement into another as we will have to remember that defending with other weapon than one with Shield quality is not valid for damage reflection. That's only valid if I understand rules correctly and defending with a shield is automatic riposte using the same roll, not a separate attack action with separate roll after defense for spending 2 Advantage - that would make this change wrong.

Automatic advantage tracking is not actually needed, but lack of ability to apply damage in defense without Champion is quite annoying.

Is it possible to put it as some setting similar to WoM channeling and UiA group advantage?

**Comment by moo-man** [comment]
I would be open for this except for the advantage cost, which doesn't have a good way to manage and confirm it's being used.

As discussed on discord, there's a much easier alternative by simply using the manual opposed buttons.

**Comment by Granathar** [comment]
Manual advantage tracking is fine, we track everything manually anyway. The workaround with opposing buttons is generally speaking good enough, but extra automation sparing these two-three clicks would still be welcome.
