### ISSUE TITLE
[Power Behind the Throne] v3.0.0 manifest missing URL and using `system` 

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1624]
- package URL has dropped from manifest file
- uses deprecated `system` instead of `relationships.systems`<br/>**From**: Jagusti#3610<br/>foundry: 10.291<br/>wfrp4e: 6.5.8<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-archives1: 3.0.1<br/>wfrp4e-archives2: 3.0.5<br/>wfrp4e-core: 3.1.3<br/>wfrp4e-dotr: 3.0.3<br/>wfrp4e-eis: 3.1.5<br/>wfrp4e-empire-ruins: 3.0.7<br/>wfrp4e-horned-rat: 2.0.1<br/>wfrp4e-middenheim: 3.0.1<br/>wfrp4e-owb1: 2.0.1<br/>wfrp4e-pbtt: 3.0.0<br/>wfrp4e-rnhd: 3.0.6<br/>wfrp4e-starter-set: 3.1.4<br/>wfrp4e-ua1: 3.0.1<br/>wfrp4e-ua2: 2.0.0<br/>wfrp4e-up-in-arms: 3.0.5<br/>wfrp4e-wom: 3.0.4<br/>wfrp4e-zoo: 3.0.1<br/>Active Modules:

**Comment by Jagusti** [comment]
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/521096/821b4727-3708-42b6-bbb8-d193de657476)
