### ISSUE TITLE
[WFRP4e Core] Chaos Star pause missing on Firefox

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#164]
the nice chaos star which is used as a pause symbold instead of the Foundry Pause clock is not visible for the players<br/>**From**: patrickmohrmann#2953<br/>wfrp4e: 3.0.2<br/>wfrp4e-core: 1.01<br/>wfrp4e-rnhd: 1.01<br/>wfrp4e-starter-set: 1.01

**Comment by grz0** [comment]
Probably fixed. Works for me on Firefox.
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/3605541/6dcaf295-294a-469b-9636-03a04e55cf33)

**Comment by moo-man** [comment]
Closing until further issues are discovered
