### ISSUE TITLE
[Core Rulebook] Fate's Fickle Fingers' icon

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1642]
The icon for Fate's Fickle Fingers spell isn't shown.
This happens because the path to the icon is fates-fickle-finger.png and the icon's name is fate's-fickle-finger.png<br/>**From**: Txus_5021<br/>foundry: 11.302<br/>wfrp4e: 6.5.9<br/>wfrp4e-core: 3.1.4<br/>Active Modules: advanced-macros, alternative-rotation, audio-preview, autoanimations, breaktime, chat-images, colorsettings, combat-tracker-dock, curtain-animations, dice-so-nice, drag-ruler, fateroll, foundryvtt-show-notes, foundryvtt-simple-calendar, healthEstimate, hidden-tables, hide-gm-rolls, item-piles, JB2A_DnD5e, lib-wrapper, remote-highlight-ui, sequencer, smalltime, socketlib, splatter, token-action-hud, tokenmagic, tokenmagic-automatic-wounds, walledtemplates, wfrp4e-endeavours, wfrp4e-fx, wfrp4e-gm-toolkit, wfrp4e-laws-pet-shoppe, wfrp4e-miscambios

**Comment by Txus5012** [comment]
It seems that the icon has been removed from the Core Module.
