### ISSUE TITLE
"undefined" is not valid JSON when opening character sheet

### ISSUE THREAD

**Issue by rikmarais** [moo-man/WFRP4e-FoundryVTT#1654]
**Describe the bug**
Error when opening character sheet. Undefined is not valid JSON

**To Reproduce**
Updated from 11.302 to 11.304, error appeared. Does not disappear on rollback to 11.302. Other GMs and users can't see the error.
Difficult to reproduce, but figured it was still worth sharing.

**Screenshots**
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/34374883/76a305ad-d3b5-43d5-8694-1fa558758290)
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/34374883/a55b30d1-549e-4714-a516-145fb6a8d04b)
(Second screenshot from when modules were still enabled, but error persists with or without)

**Version Numbers**
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/34374883/f2a29b22-b2a5-4fa5-a034-955d166a0169)
(One active module is the Forge module)

Foundry: 11.304
wfrp4e: 6.5.9
wfrp4e-core: 3.1.4
wfrp4e-starter-set: 3.1.5
wfrp4e-rnhd: 3.0.7
wfrp4e-ua1: 3.0.2

**Comment by moo-man** [comment]
You can ignore it, it's an quirk that sometimes pops up when using wfrp on forge

**Comment by rikmarais** [comment]
Alright, thanks for checking it out.

It's possible that this is related to a bug in the Forge module which has recently been fixed but not yet deployed. Hopefully with the new version of the Forge module, this will no longer pop up. If it does resurface, please let me know and I'll hunt it down. Thanks!

**Comment by moo-man** [comment]
It's not a new thing, has been around for over a year, I just haven't found a solution to it.
