### ISSUE TITLE
Magic Resistance (Trait) 🛡️

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1665]
**Describe the bug**
The SL of any spell affecting character with Magic Resistance (Trait) should be reduced by the Rating given. So, Magic Resistance 2 would reduce the SL by 2, Magic Resistance 5 would reduce the SL by 5... Now, always reduce SL by -2 and do not care about Trait Specification field.

**Screenshots**
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/d6da949d-748b-42b7-95f3-45a0437f8489)
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/14de7762-b323-4a37-adc6-e234f132d707)

**Comment by moo-man** [comment]
There is no problem here. Multiple Talent effects stack.

**Comment by Forien** [comment]
> There is no problem here. Multiple Talent effects stack.

I think the author meant Trait, in that case, Rating should be taken into consideration, but isn't.

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/04fa8082-0cc4-4e7d-a0c8-4ddbea8e4c0f)

**Comment by moo-man** [comment]
Woops, reading helps
