### ISSUE TITLE
Afraid (Trait) better readability 📝

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1666]
Hi, now the Afraid (Trait) description looks like this:
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/af3adad0-45b6-4b9a-9bfb-739165543368)

I suggest changing it to something like this:
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/84ad7ec2-11ac-4b34-8e74-5627c6e55db0)

HTML:
```
<p>The creature is afraid of the Target as if the Target has Fear (0). </p>
<p>The Fear trait represents an extreme aversion to something. Creatures that cause Fear have a Fear Rating; this value reﬂects the SL you are required to pass on an Extended Cool Test to overcome your Fear. You may continue to Test at the end of every round until your SL equals or surpasses the creature’s Fear rating. Until you do this, you are subject to Fear.</p>
<p>When subject to Fear:</p>
<ul>
<li>You suffer –1 SL on all Tests to affect the source of your fear.</li>
<li>You may not move closer to whatever is causing Fear without passing a <strong>Challenging (+0) Cool</strong> Test. If it comes closer to you, you must pass a <strong>Challenging (+0) Cool</strong> Test, or gain a <em>@Condition[Broken]</em> Condition.</li>
</ul>
```

**Comment by moo-man** [comment]
I'm not sure I'm going to go through with these. While I agree it's much better readability, I'm not inclined to add drastic changes to text, as it could create different interpretations of it, and I would have to apply them to all existing actors.

I want to avoid questions about differences between the source material and the Foundry implementations

**Comment by GregorHak** [comment]
Generaly in core rulebook there is only a reference:
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/e83f5f96-ae77-44b3-84f8-2ab8a044afc4)

Now, in Foundry Psychology item has better readability, but trait has not
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/05d7e15c-0d77-481f-8815-d75a943fa620)
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/5dbb8e8b-28e8-4af5-bc0e-1e566dcacdf9)

**Comment by GregorHak** [comment]
close thread, now trait look different (image below)
![Uploading obraz.png…]()
