### ISSUE TITLE
[WFRP4e System] Stat block import doesnt import spells

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#167]
Minor improvement for the future, nothing urgent:

e.g. Elva Fellgiebel from "Hell rides to Hallt" has the following spells:

Spells: Blast, Corrosive Blood, Dart, Drain, Eavesdrop,
Magical Shield, Manifest Lesser Daemon

which get imported as trappings instead of Spells<br/>**From**: genmaster <br/>wfrp4e: 3.1.0<br/>wfrp4e-core: 1.01<br/>wfrp4e-eis: 1.0<br/>wfrp4e-rnhd: 1.01<br/>wfrp4e-starter-set: 1.01

**Comment by genmaster** [comment]
![image](https://user-images.githubusercontent.com/7229237/98867876-9bdf3b00-246f-11eb-9662-4934106187f0.png)
results in 
![image](https://user-images.githubusercontent.com/7229237/98867922-a7cafd00-246f-11eb-81ca-57266562f253.png)

**Comment by genmaster** [comment]
raw data:

ELVA FELLGIEBEL – REEVE (GOLD 1)
M WS BS S T I Agi Dex Int WP Fel W
4 46 34 32 31 54 43 49 67 61 42 15
Traits: Weapon (Sword) +7
Skills: Bribery 52, Charm 65, Cool 67, Channelling 66,
Dodge 48, Intimidate 39, Language (Magick) 74, Lore
(Dhar) 72, Melee (Basic) 53
Talents: Arcane Lore (Dark), Frightening (Causes Fear
1), Kingpin, Petty Magic
Trappings: Fine Clothing, Ritual Books, Writs
and Legal Documents, 1d10 gold crowns
Spells: Blast, Corrosive Blood, Dart, Drain, Eavesdrop,
Magical Shield, Manifest Lesser Daemon

**Comment by moo-man** [comment]
Not sure it's ever going to, tbh, it's mainly a best effort parsing and there's probably a lot of complications with spells regarding lore.

**Comment by moo-man** [comment]
I'm going to go ahead and close this as I deem the importer does enough as it is, and dealing with spells is beyond its best effort approach. Additionally C7 tend to ascribe spells to NPCs in various ways
