### ISSUE TITLE
Hateful Impulses (Core Mutation) 😠

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1673]
**Describe the bug**
If you drag Hateful Impulses (Core Mutation) to character with empty spice field, it will be treated like Human.

**Now in Foundry**
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/9fa509b6-70ff-4892-888e-d1954c3692ed)

**My idea**
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/1637f2fa-4806-4e96-a69f-b07efb363358)

**Additional context**
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/71ee8614-3b79-49a2-80e4-a26bff597cac)
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/ce532999-98cf-4f78-a1c8-dc4c71cc650d)

**Describe the solution you'd like**
```
fromUuid("Compendium.wfrp4e-core.psychologies.Q2MCUrG2HppMcvN0").then(item => {
   item = item.toObject()
    let species = args.actor.details.species.value || "of your species"
    item.name = `Animosity (all not ${species})`
    args.actor.createEmbeddedDocuments("Item", [item])
})
```

**Comment by GregorHak** [comment]
If you ask why? Simple, not always character is a human

**Comment by Forien** [comment]
Why not just fill in your `species` field?

![](https://i.gyazo.com/cd8c1a1b22964346cd5e5039f8f9570b.gif)

**Comment by GregorHak** [comment]
I know that, but answer the question: Are you fill species field for every NPC and creature? I consider that sometimes this field is empty, and for this case I think that better is replacing "Human" with "of your species"

**Comment by Forien** [comment]
> I know that, but answer the question: Are you fill species field for every NPC and creature? I consider that sometimes this field is empty, and for this case I think that better is replacing "Human" with "of your species"

If I care enough about NPCs to give them corruptions - yes, I fill most of the inputs. 
Also since 91% of the Empire is Human, it's logical that default for empty field is Human.

I don't disagree with your suggestion, I'm just finding it not impactful since it's not that time consuming to enter species.

Especially that if I make an Elf and I don't fill in the species, then 2-3 months later when I use that NPC I might not remember who it was.

**Comment by GregorHak** [comment]
To sum up: 
- "of your species" fits every time, when "Human" can mislead
- Phrase "of your species" is nothing new, see desc of this mutation
- This change should not be priority and most important, but will be nice if will made - even in distant future
- Also 🤪 this change can potentially lead to dystopian lifestyle, because if you drag this mutation on character sheet (with empty species) no additional care of you is needed, which may make you lazzy and inattentive

**Comment by Forien** [comment]
As I said, I don't disagree, just found it very interesting it's an issue :P 



> * may make you lazzy and inattentive

That's the worst case scenario! :o
