### ISSUE TITLE
[WFRP4e System] If Active Effect changes Max Wounds, Wounds never get lower than original Max

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1682]
Steps to reproduce:

1. Make an Active Effect on an Actor (or Item)
2. Set it's changes to `system.status.wounds.max` | Add | 4
3. Check your Actor. They have for example 12/16 Wounds now
4. Change your Actor's Wounds to 1/16
5. Observe Actor reverting to 12/16 Wounds
6. Disable Effect
7. Wounds are now 12/12
8. Reduce Wounds to 1/12
9. Wounds stay 1/12<br/>**From**: forien<br/>foundry: 11.304<br/>wfrp4e: 6.5.9<br/>wfrp4e-core: 3.1.4<br/>wfrp4e-up-in-arms: 3.0.6<br/>wfrp4e-wom: 3.0.5<br/>Active Modules: ATL, dfreds-chat-pins, dfreds-effects-panel, forien-armoury, forien-custom-utility, lib-wrapper, socketlib, times-up, wfrp4e-gm-toolkit, wfrp4e-unofficial-grimoire

**Comment by Forien** [comment]
I know we can use "pre-Wound" calculation, but this one still feels like a weird bug, probably a low priority one

**Comment by moo-man** [comment]
intention is to use scripts to modify wound calculations
