### ISSUE TITLE
[WFRP4e System] - Moving Compendiums into Folders results in a bug (v11)

### ISSUE THREAD

**Issue by Forien** [moo-man/WFRP4e-FoundryVTT#1691]
I swore that I've seen it's reported, but I couldn't find it now...

**Describe the bug**
Basically when I create a new folder in Compendium tab and then try to move any compendium (official or not), Compendium tab breaks on update. Compendium is actuallly being moved, the only thing that breaks is tab refresh/redraw.

**To Reproduce**
1. Be on v11 and WFRP4e system
2. Create a compendium
3. Create a folder
4. Drag Compendium onto a Folder
5. Witness the bug
6. Refresh to see Compendium is in the Folder

```js
foundry.js:15940 Uncaught (in promise) TypeError: undefined. metadata.index is not iterable
[No packages detected]
    at new CompendiumCollection (foundry.js:15940:29)
    at Game.initializePacks (foundry.js:8791:27)
    at onChange (foundry.js:9075:14)
    at Setting._onUpdate (foundry.js:24150:67)
    at ClientDatabaseBackend.callback (foundry.js:13703:11)
    at foundry.js:13677:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13677:33)
CompendiumCollection @ foundry.js:15940
initializePacks @ foundry.js:8791
onChange @ foundry.js:9075
_onUpdate @ foundry.js:24150
callback @ foundry.js:13703
(anonymous) @ foundry.js:13677
#handleUpdateDocuments @ foundry.js:13677
```

**Version Numbers**
PLEASE PROVIDE YOUR FOUNDRY, SYSTEM, and MODULE VERSIONS (where applicable) 

foundry: 11.305
wfrp4e: 6.5.9
wfrp4e: 6.5.9
wfrp4e-core: 3.1.4
wfrp4e-up-in-arms: 3.0.6
wfrp4e-wom: 3.0.5

**Comment by Txus5012** [comment]
Probably related:

In v11, if you Toggle Edit Lock of a compendium the icon won't appear/disappear untill a refresh or clicking in the Sort button. It is toggled, it's just the icon not updating.
This doesn't happen in other systems.

In the issue above, you can also click the Sort button to see the compendium moved (Step 6).

foundry: 11.305
wfrp4e: 6.5.9
wfrp4e-core: 3.1.4
Seen with all modules disabled.

**Comment by Forien** [comment]
> Probably related:
> 
> In v11, if you Toggle Edit Lock of a compendium the icon won't appear/disappear untill a refresh or clicking in the Sort button. It is toggled, it's just the icon not updating. This doesn't happen in other systems.
> 
> In the issue above, you can also click the Sort button to see the compendium moved (Step 6).
> 
> foundry: 11.305 wfrp4e: 6.5.9 wfrp4e-core: 3.1.4 Seen with all modules disabled.

I believe it's related. Basically in v11 with wfrp4e whenever you update a compendium document itself (not content), the tab tries to refresh/re-render and that probably breaks. Updates are all made, just not appearing unless you open compendium tab in popup (by right click) or until you F5

**Comment by BoltsJ** [comment]
So the underlying cause of that error seems to be a bug in foundry being surfaced by the wfrp4e-core module deleting the basic items compendium. When the pack is deleted, it still shows up in `game.data.packs`, and causes an undefined value to get passed to the CompendiumCollection constructor.

**Comment by Forien** [comment]
> So the underlying cause of that error seems to be a bug in foundry being surfaced by the wfrp4e-core module deleting the basic items compendium. When the pack is deleted, it still shows up in `game.data.packs`, and causes an undefined value to get passed to the CompendiumCollection constructor.

Can confirm. Using `game.data.packs.splice(2, 1)` where `2` was index of `basic` pack (probably because I have some world packs as well?) made the issue go away (until the F5 of course).
