### ISSUE TITLE
[WFRP4e System] Damaging Quality Doesn't Work

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1700]
"Damaging" weapon effect does not seem to apply on successful attacks where the units die is higher. Tested on 2 separate worlds with 4 different character sheets.<br/>**From**: Raddish Red#8120<br/>foundry: 10.291<br/>wfrp4e: 6.5.3<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-archives1: 2.4.1<br/>wfrp4e-archives2: 3.0.3<br/>wfrp4e-core: 3.1.0<br/>wfrp4e-dotr: 2.3.4<br/>wfrp4e-eis: 3.1.0<br/>wfrp4e-horned-rat: 2.0.1<br/>wfrp4e-middenheim: 2.4.2<br/>wfrp4e-pbtt: 2.2.3<br/>wfrp4e-ua1: 3.0.0<br/>wfrp4e-ua2: 2.0.0<br/>wfrp4e-up-in-arms: 3.0.2<br/>wfrp4e-wom: 3.0.2<br/>Active Modules: barbrawl, df-manual-rolls, df-qol, df-settings-clarity, foundryvtt-arms-reach, foundryvtt-simple-calendar, lib-wrapper, settings-extender, wfrp4e-dotr-maps, wfrp4e-eis-maps, wfrp4e-gm-toolkit, wfrp4e-ubersreik-maps

**Comment by moo-man** [comment]
Not reproducible

**Comment by Forien** [comment]
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/c70d774d-43e1-48e6-adbe-1e3b5d1aaa1c)

Works fine in foundry 11.305 and wfrp4e 6.5.9

I do not have the modules like `df-manual-rolls` so can't say anything for conflicts.

**Comment by moo-man** [comment]
User thought it replaced attacker SL
