### ISSUE TITLE
[WFRP4e System] Implementing Counter from Age of Sigmar / Wrath & Glory into Warhammer Fantasy

### ISSUE THREAD

**Issue by jtsmirror** [moo-man/WFRP4e-FoundryVTT#1718]
**Is your feature request related to a problem? Please describe.**
While not a problem per se, I would appreciate the integration of the 'Counter' function from Age of Sigmar: Soulbound / Wrath & Glory into Warhammer Fantasy in form of Advantage Counter. This feature would offer a fast way to manage advantage with new Group Advantage rules from Up In Arms.

**Describe the solution you'd like**
I envision the possibility of using this feature as a quick option for adding and subtracting advantages for players and enemies. I am aware of the option to modify advantages in the character sheet or in the combat encounters tab, but I believe that the implementation of a similar counter (with the option to disable it for those who do not prefer it) would significantly enhance combat during game.

**Additional context**
How it look in soulbound
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/136428641/0619f30d-de91-44e8-8c8a-6008b34f7587)
How i want it to look in Warhammer (simple presentation of idea)
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/136428641/19cc7c3b-596d-4e15-aca2-b25373a807db)

**Comment by moo-man** [comment]
I see little reason for this, Advantage is only relevant for combat (unlike the other games where they persist), and so the combat tracker will be being used anyway.
