### ISSUE TITLE
[WFRP4e System] FX Master Special Effects

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#172]
I use the WFRP4 Game System + all paid WFRP4 Modules.

I want to add webm Special Efects in FXMaster. 
But I get only this tiny window with no possibility to add any.<br/>**From**: ScarSacul#6846<br/>wfrp4e: 3.1.0<br/>wfrp4e-core: 1.1<br/>wfrp4e-eis: 1.0<br/>wfrp4e-rnhd: 1.02<br/>wfrp4e-starter-set: 1.02

**Comment by ScarSacul** [comment]
![fxmaster wfrp4 no special effects](https://user-images.githubusercontent.com/74356592/98934697-ccac8800-24e2-11eb-8868-9c26ccf34baf.jpg)
