### ISSUE TITLE
[WFRP4e System] channelling SL is capped at memorized CN when using unmemorized spells. 

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1731]
We are playing WHFB. There is a problem with checking concentration of wizards. If the spell is not memorized by the character, then the set of successes does not increase. 

For example: 
a spell requires 12 successes(if the spell is not memorized);
a spell requires 12 successes(when it is memorized).

However, when performing a check, there is a threshold of 6 successes maximum, no higher is added. In both cases.

<br/>**From**: Grinpis#9194<br/>foundry: 11.307<br/>wfrp4e: 6.6.1<br/>wfrp4e-core: 3.1.6<br/>Active Modules: babele, dice-calculator, dice-so-nice, lib-wrapper, ru-ru, wfrp4e-character-details

**Comment by moo-man** [comment]
Non reproducible, CN is halved as expected, and user can't be contacted.
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/28637157/1825e7a8-0a17-41a3-95d0-8dab6904c52d)

**Comment by Grinpis300** [comment]
![Безымянный](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/136200476/66ccd527-b30c-4995-9652-d760c59e4081)
the number of successes on the check does not match to the number of the CN creation (when the spell is not remembered)

**Comment by Grinpis300** [comment]
or
![1](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/136200476/673305a6-0c19-49e0-805d-25a8e16cba4a)
![Безымянный](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/136200476/85ff9090-6279-4098-8a03-75fc6a1d8f3b)

**Comment by moo-man** [comment]
Ok I think I understand now
