### ISSUE TITLE
Problems with fear

### ISSUE THREAD

**Issue by Grinpis300** [moo-man/WFRP4e-FoundryVTT#1735]
If the effect of fear is imposed on the target, then in the effects of the modifier's influence - 1 CP, but this is not observed in the left plate (and as a result, it does not participate in the battle)
![Безымянный](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/136200476/43155c5a-101e-495a-972e-293e6761cfe7)
![1](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/136200476/807dd6ed-1d52-41ba-ba8f-f7fb8acfa2e0)

**Comment by moo-man** [comment]
Select the modifier to apply the values
