### ISSUE TITLE
Hide Equipped/Worn text when items are Collapsed 🧤

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1743]
Can You consider hide text "Equipped" and "Worn" when items are collapsed? 

You know what I mean? I marked on yellow which text should be hidden, in this case: "Equipped" from Weapons and "Worn" from Clothing and Accessories, but no "Worn" from Armour, because items there are not collapsed.

![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/ecdef811-5819-4df6-807e-c2b1901392ad)

**Comment by Jagusti** [comment]
If you get rid of `Equipped` and `Worn`, may as well get rid of `Qty` and `Enc` too?
