### ISSUE TITLE
[WFRP4e System] Critical Wounds disappearing

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1745]
I received two criticals in a fight (Gut Wound + Broken Arm (Minor)). However, every time I sign out and log back in, the criticals are missing from my sheet. The bleed from Gut Wound also seems to impossible to remove with player permissions.<br/>**From**: CoG#9765<br/>foundry: 11.307<br/>wfrp4e: 6.6.1<br/>wfrp4e-core: 3.1.6<br/>wfrp4e-dotr: 3.0.6<br/>wfrp4e-eis: 3.1.7<br/>wfrp4e-middenheim: 3.0.3<br/>wfrp4e-pbtt: 3.0.3<br/>wfrp4e-rnhd: 3.0.8<br/>wfrp4e-starter-set: 3.1.7<br/>wfrp4e-up-in-arms: 3.0.7<br/>wfrp4e-wom: 3.0.7<br/>Active Modules: about-face, calendar-weather, colorsettings, custom-compendium-banners, dice-so-nice, drag-ruler, easy-target, foundry-combat-focus, foundryvtt-simple-calendar, fvtt-party-resources, lib-wrapper, lordudice, permission_viewer, popout, scaleGrid, settings-extender, socketlib, special-dice-roller, splatter, split-journal, torch, weather-control, wfrp4e-gm-toolkit, forge-vtt

**Comment by Cogsagi** [comment]
Submitted with my old discord info. Can reach me at .cog if needed.

**Comment by moo-man** [comment]
Impossible in what way, do you receive an error when you try?

**Comment by Cogsagi** [comment]
Yes, I believe its related to the critical wound not "existing" on the serverside of things despite it showing on my sheet until I reload.
Would an error ID be useful?

**Comment by moo-man** [comment]
Can you verify it's still a problem in WFRP 7.0.0?

**Comment by Cogsagi** [comment]
Looks like the recent update resolved all the issues above! Thank you!

**Comment by moo-man** [comment]
👍 great!
