### ISSUE TITLE
[WFRP4e System] Pings and Pointers - Settings

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#175]
The Pings and Pointers Module Settings are very hard to read.<br/>**From**: ScarSacul#6846<br/>wfrp4e: 3.1.0<br/>wfrp4e-core: 1.1<br/>wfrp4e-eis: 1.0<br/>wfrp4e-rnhd: 1.02<br/>wfrp4e-starter-set: 1.02

**Comment by ScarSacul** [comment]
![Pointer and Pings_1](https://user-images.githubusercontent.com/74356592/98935856-704a6800-24e4-11eb-9600-6e80522f33e9.JPG)
![Pointer and Pings_2](https://user-images.githubusercontent.com/74356592/98935859-72142b80-24e4-11eb-8a62-9f67f859ee5c.JPG)
