### ISSUE TITLE
[WFRP4e System] Hardy do not increase health

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1750]
Hardy talent increase (in new version, previously was ok) Wounds only once, eg 4 levels of it add only 1x Toughness Bonus

STR:
Have a Player Character
Note Wounds [W] and Toughness Bonus [TB]
Add Hardy talent (1 level)
ER=AR: W increase by TB
Add next level(s) of Hardy talents
ER: W are increased by total of TB times Hardy levels
AR: W are increased inly by 1x TB, regardless of Hardy level<br/>**From**: timitum@gmail.com or discord macieks#8665<br/>foundry: 11.308<br/>wfrp4e: 7.0.0<br/>wfrp4e-archives1: 4.0.0<br/>wfrp4e-core: 4.0.0<br/>wfrp4e-dotr: 4.0.0<br/>wfrp4e-eis: 4.0.0<br/>wfrp4e-pbtt: 4.0.0<br/>wfrp4e-rnhd: 4.0.0<br/>wfrp4e-starter-set: 4.0.0<br/>wfrp4e-ua1: 4.0.0<br/>Active Modules: wfrp4e-eis-maps

**Comment by Forien** [comment]
Can confirm.

Was worried it might affect all talent effects, but no.  
I tested `Hardy` and `Strike to Injure`

`Hardy` only seems to apply once while `Strike to Injure` Applies multiple times

As can be seen in screenshots, 3 `Strike to Injure` talents properly add 3 Damage (`3 * +1`), while `Hardy` only adds 4 hp once. 

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/c4395bd1-f8b0-450c-99a8-7fb6faf04fc7)

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/2fe376fb-4048-46a8-ba3b-af160c75e75e)
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/c8c3689b-cf23-41fd-a07e-31b82b947eeb)


So it might be `Wound Calculation` trigger only?
