### ISSUE TITLE
Decimal numbers goes crazy when item is worn 😜

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1751]
**Describe the bug**
Please check video, when wrote "ENC = 1.1" some numbers start goes crazy
[LINK to video](https://youtu.be/ePG5XzttN28)

**Version Numbers**
Foundry: 11 308
wfrp4e: 6.6.1

**Comment by Forien** [comment]
Typical computer issue with floating numbers :D 

Probably easy to fix by doing `parseFloat` or some other trimming/rounding

**Comment by GregorHak** [comment]
It looks like the problem has been fixed.
