### ISSUE TITLE
[Core Rulebook] Some of the trappings and spells icons are missing and throw 404s

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1753]
exactly as the title says<br/>**From**: Perkuns#9523<br/>foundry: 11.308<br/>wfrp4e: 7.0.1<br/>wfrp4e-altdorf: 4.0.0<br/>wfrp4e-archives1: 4.0.0<br/>wfrp4e-archives2: 4.0.0<br/>wfrp4e-core: 4.0.0<br/>wfrp4e-dotr: 4.0.0<br/>wfrp4e-eis: 4.0.0<br/>wfrp4e-empire-ruins: 4.0.0<br/>wfrp4e-horned-rat: 4.0.0<br/>wfrp4e-middenheim: 4.0.0<br/>wfrp4e-owb1: 4.0.0<br/>wfrp4e-pbtt: 4.0.0<br/>wfrp4e-rnhd: 4.0.0<br/>wfrp4e-starter-set: 4.0.0<br/>wfrp4e-ua1: 4.0.0<br/>wfrp4e-ua2: 4.0.0<br/>wfrp4e-up-in-arms: 4.0.0<br/>wfrp4e-wom: 4.0.0<br/>Active Modules: about-time, acelib, ATL, breaktime, colorsettings, custom-css, dice-calculator, dice-so-nice, drag-ruler, easy-target, find-the-culprit, forien-armoury, forien-copy-environment, forien-quest-log, foundryvtt-simple-calendar, fuzzy-foundry, gm-token-drag-visibility-v2, image-hover, item-piles, lib-captions, lib-changelogs, lib-find-the-path, lib-wrapper, module-credits, monks-scene-navigation, party-overview, permission_viewer, popout, quick-insert, remote-highlight-ui, routinglib, silence-compatibility-warnings, socketlib, sweetnothings, times-up, token-action-hud, token-auras, vtta-tokenizer, wall-height, wfrp4e-dotr-maps, wfrp4e-eis-maps, wfrp4e-ubersreik-maps, _CodeMirror

**Comment by moo-man** [comment]
Any more information would be helpful

**Comment by SimonasBanys** [comment]
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/31985858/227f7b3a-f7d2-4fb8-a40b-ad2ff946f2b1)
didnt get in time before your comment to upload screenshot of errors

**Comment by moo-man** [comment]
These aren't spell icons, they are image sin journal entries. You can fix them by updating your imported journals.
