### ISSUE TITLE
[WFRP4e System] Chaos star still missing in Firefox

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1754]
Sorry but this is still missing. Latest versions of VTT, WFRP 4e and Firefox installed.<br/>**From**: .turnstar<br/>foundry: 11.308<br/>wfrp4e: 7.0.1<br/>wfrp4e-up-in-arms: 4.0.0<br/>Active Modules: dice-so-nice, foundryvtt-simple-calendar, lib-wrapper, mythic-gme-tools, party-overview, pings, popout, settings-extender, tabletop-rpg-music, torch, forge-vtt

**Comment by grz0** [comment]
Works for me on FF and self-hosted Foundry:
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/3605541/9c0f0181-9ee9-4752-9cff-9b110fe86df7)

**Comment by GregorHak** [comment]
For me also working
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/8fddc47c-f878-417c-a010-55009dbf7835)

**Comment by moo-man** [comment]
Closing this as I won't pursue a fix (if one is still needed)
