### ISSUE TITLE
[Core Rulebook] Disease Symptoms aren't reflecting in chat

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1755]
When you select Core Rulebook journal, then "Disease and Infection" page, then click on any symptom, chat messages only say "undefined" and no errors in console.<br/>**From**: Wolenard<br/>foundry: 11.308<br/>wfrp4e: 7.0.1<br/>wfrp4e-altdorf: 4.0.0<br/>wfrp4e-archives1: 4.0.0<br/>wfrp4e-archives2: 4.0.0<br/>wfrp4e-core: 4.0.0<br/>wfrp4e-dotr: 4.0.0<br/>wfrp4e-eis: 4.0.0<br/>wfrp4e-empire-ruins: 4.0.0<br/>wfrp4e-horned-rat: 4.0.0<br/>wfrp4e-middenheim: 4.0.0<br/>wfrp4e-owb1: 4.0.0<br/>wfrp4e-pbtt: 4.0.0<br/>wfrp4e-rnhd: 4.0.0<br/>wfrp4e-starter-set: 4.0.0<br/>wfrp4e-ua1: 4.0.0<br/>wfrp4e-ua2: 4.0.0<br/>wfrp4e-up-in-arms: 4.0.0<br/>wfrp4e-wom: 4.0.0<br/>wfrp4e-zoo: 4.0.0<br/>Active Modules:

**Comment by Txus5012** [comment]
There are a couple of issues more with diseases and symptoms.

- There is a deprecation warning when expanding/collapsing diseases in the character sheet.
![Label](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/87753744/41a72aae-529f-42c1-8fb4-81d8764950d2)
This "label" here should be "name".

- There is another deprecation warning when invoking "Blight".
![Label Blight](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/87753744/4cbdcc05-45b9-4889-913d-ff0dc8eded9a)
Similar for "Convulsions".

- I think the scripts of "Coughs and Sneezes" and "Fever" have the script of the other one.
The same for "Lingering" and "Gangrene".

- "Coughs and Sneezes" has `"otherEffects": ["blight", "wounded"]` that belongs to "Gangrene". Don't know if that actually does something, though.
