### ISSUE TITLE
[Core Rulebook] Add link to Religion and Belief in Bless talent description

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1759]
Bless (Talent) description looks like:
"You are watched over by one of the Gods and can empower simple prayers. You can now deploy the Blessings of your deity as listed in Chapter 7: Religion and Belief. Under normal circumstances, you may only ever know one Divine Lore for the Bless Talent."

Can you change text: "Chapter 7: Religion and Belief" to "@UUID[Compendium.wfrp4e-core.journal-entries.NcH9OhleJFfaUdon]{Religion and Belief}".

It will match the rest of the talents with links.<br/>**From**: GregorHak, patryk695035@gmail.com<br/>foundry: 11.308<br/>wfrp4e: 6.6.1<br/>wfrp4e-core: 3.1.6<br/>Active Modules: advanced-drawing-tools, arms-reach, autocomplete-whisper, colorsettings, cursor-hider, FollowMe, forien-quest-log, foundryvtt-simple-calendar, hourglass, image-hover, introduce-me, item-piles, lib-wrapper, longer-chat-bubbles, louder-whispers, moulinette-core, moulinette-tiles, multilevel-tokens, My-Shared-Compendia, narrator-tools, permission_viewer, pings, polyglot, searchanywhere, settings-extender, simplefog, smalltime, smallweather, socketlib, splatter, token-ease, token-says, token-z, tokenmagic, tokenmagic-automatic-wounds, wfrp4e-gm-toolkit, wfrp4e-laws-pet-shoppe

**Comment by GregorHak** [comment]
After last update I assume that "wfrp4e-core.journal-entries" should be replace with "wfrp4e-core.journals",

**Comment by GregorHak** [comment]
Also for **Invoke (Talent)** can You do the same?
