### ISSUE TITLE
[Core Rulebook] Missing Melee weapons Reach descriptions

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1760]
Equip any melee weapon and check Reach Description in combat tab.

https://www.upload.ee/image/15649536/Zrzut_ekranu_2023-09-4_o_05.22.33.png

<br/>**From**: jtsmirror<br/>foundry: 11.308<br/>wfrp4e: 7.0.1<br/>wfrp4e-core: 4.0.0<br/>Active Modules: lib-wrapper, polyglot

**Comment by Txus5012** [comment]
I think the issue is that "reachDescription" isn't in the toTranslate list.
