### ISSUE TITLE
[Core Rulebook] Incorrect string WFRP4E.Reach.AverageDescription on items

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1761]
In the Core Rulebook Bestiary there are a couple of actors (Stellemar, Kastor Erichson) that have weapons with Average reach. But it looks like something is wrong and it shows as "WFRP4E.Reach.AverageDescription" instead of just "Average".

The correct localization key should be "WFRP4E.Reach.Average" without "Description" at the end.

There could be more actors like that.<br/>**From**: phenomen<br/>foundry: 11.308<br/>wfrp4e: 7.0.1<br/>wfrp4e-core: 4.0.0<br/>Active Modules:

**Comment by phenomen** [comment]
Example
![Foundry_Virtual_Tabletop_b65wJOS33G](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/138311/94bc49c6-e4a0-4547-99ee-06b1ea988a92)

**Comment by moo-man** [comment]
Duplicate #1760

**Comment by phenomen** [comment]
Nevermind, `WFRP4E.Reach.AverageDescription` actually exist but in the Core Rulebook's `en.json` but not used here
