### ISSUE TITLE
[WFRP4e System] WFRP4E.symptomTreatment and WFRP4E.symptoms are not localized correctly

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1762]
See screenshot<br/>**From**: phenomen<br/>foundry: 11.308<br/>wfrp4e: 7.0.1<br/>wfrp4e-core: 4.0.0<br/>Active Modules: babele, lib-wrapper, ru-ru

**Comment by phenomen** [comment]
![Foundry_Virtual_Tabletop_tEh0k0XZY7](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/138311/5ac96077-ec96-41da-b705-ac36ea61e37a)

**Comment by moo-man** [comment]
I'd ask if you could avoid translating the `premiumModules` object to maintain English bug report titles and details. Thanks.

**Comment by phenomen** [comment]
> I'd ask if you could avoid translating the `premiumModules` object to maintain English bug report titles and details. Thanks.

Sorry, I've noticed it after submitting a report. I was thinking it's used for compendium folder names or something like that 😔
