### ISSUE TITLE
[WFRP4e System] overcasting can go into negative

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1768]
You can overcast into negative.
See Image and video
https://ptb.discord.com/channels/449845411344154634/712500603250802829/1150797740658401320
https://cdn.discordapp.com/attachments/712500603250802829/1150798004903747655/image.png
Dont know if is a feature or a bug<br/>**From**: gm_d<br/>foundry: 11.308<br/>wfrp4e: 7.0.1<br/>wfrp4e-altdorf: 4.0.0<br/>wfrp4e-archives1: 4.0.0<br/>wfrp4e-archives2: 4.0.0<br/>wfrp4e-core: 4.0.0<br/>wfrp4e-dotr: 4.0.0<br/>wfrp4e-eis: 4.0.0<br/>wfrp4e-empire-ruins: 4.0.0<br/>wfrp4e-horned-rat: 4.0.0<br/>wfrp4e-middenheim: 4.0.0<br/>wfrp4e-owb1: 4.0.0<br/>wfrp4e-pbtt: 4.0.0<br/>wfrp4e-rnhd: 4.0.0<br/>wfrp4e-starter-set: 4.0.0<br/>wfrp4e-ua1: 4.0.0<br/>wfrp4e-ua2: 4.0.0<br/>wfrp4e-up-in-arms: 4.0.0<br/>wfrp4e-wom: 4.0.0<br/>wfrp4e-zoo: 4.0.0<br/>Active Modules: Inline-Table-Rolls, SharedVision, about-face, about-time, autoanimations, background-volume, baileywiki-landing-pages, baileywiki-maps-premium, baileywiki-nuts-and-bolts, betterroofs, bhk-errt, calendar-weather, chat-images, color-picker, colorsettings, config-presets, cursor-hider, darkness-activated-tiles, dd-import, dice-calculator, dice-so-nice, drag-ruler, dragupload, dynamic-soundscapes, easy-target, entice-with-dice-so-nice, fateroll, filepicker-plus, find-the-culprit, foundry-taskbar, foundryvtt-simple-calendar, fvtt-party-resources, fvtt-syrin-control, fxmaster, gatherer, give-item, go-to-player, healthEstimate, hover-distance, image-context, image-hover, inactive-tokens-lmao, item-piles, jb2a_patreon, journal-thumbnail, lessfog, levels, levels-layer-effects, levelsautocover, levelsvolumetrictemplates, lib-wrapper, light-switch, macro-folders, macro-manager, macro-wheel, mastercrafted, media-optimizer, module-credits, monks-active-tiles, monks-combat-details, monks-common-display, monks-hotbar-expansion, monks-little-details, monks-scene-navigation, monks-sound-enhancements, monks-tokenbar, monks-wall-enhancement, moulinette-core, moulinette-gameicons, moulinette-imagesearch, moulinette-scenes, moulinette-sounds, moulinette-tiles, multi-token-edit, multiface-tiles, multilevel-tokens, narrator-tools, omniscient-die, patrol, permission_viewer, playlist-down, playlist-drag-and-drop, popout, popout-resizer, progress-tracker, quick-doors, quick-insert, quickdraw, quickscale, ready-check, scene-packer, scenery, sequencer, settings-extender, sidebar-resizer, smalltime, smarttarget, socketlib, splatter, super-select, svt, tagger, theripper-premium-hub, tile-scroll, tile-sort, token-action-hud-core, token-action-hud-wfrp4e, token-attacher, token-hud-wildcard, token-mold, token-notes, token-z, tokenflip, tokenmagic, tokenmagic-automatic-wounds, trs-foundryvtt-dice-set, trs-hyperdrive-console-dice-set, user-latency, wall-height, weather-control, weatherblock, wfrp4e-eis-maps, wfrp4e-gm-toolkit, what-the-flag, forge-vtt, forge-vtt-optional

**Comment by warhammering** [comment]
Here is a image
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/140810683/0969e652-91f9-421e-9536-a6ed2d1ee4d2)
In the picture above I use overcast until I have 0 sl but I am able to keep clicking and it goes into negative
and then it goes into the negative
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/140810683/2b83ddbf-b6cb-4993-ab62-a6270d0cb7f8)
