### ISSUE TITLE
[WFRP4e Core] Scene: GM Screen not working

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#177]
I'm trying to view the GM Screen scene and I get this error:

Error: You are using a Scene background texture with dimensions 10205px by 3319px. One or both of these dimensions exceeds the maximum texture size of 8192px supported by your device.<br/>**From**: valberg@orn.li<br/>wfrp4e: 3.1.0<br/>wfrp4e-core: 1.1<br/>wfrp4e-rnhd: 1.02<br/>wfrp4e-starter-set: 1.02

**Comment by moo-man** [comment]
You're going to have to reduce the size of it due to your hardware limitations.

**Comment by valberg** [comment]
I've tried taking it down to 1920x1080, but still getting the error.  See the following screenshot (I have saved the configuration and accepted the popup about objects shifting position).

![Screenshot_2020-11-12 Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application(2)](https://user-images.githubusercontent.com/5782/98968463-ff1faa80-250d-11eb-8f15-7deffdbe28af.png)

Am I doing it wrong?

**Comment by moo-man** [comment]
Ah, my bad, the source file is still that large.

I will consider downscaling it, or offering a downscaled version.

**Comment by valberg** [comment]
Sounds good! Awesome work btw. Been looking forward to a VTT version of WFRP 4e :clap:

**Comment by moo-man** [comment]
Thanks! :D
