### ISSUE TITLE
[WFRP4e System] Weapon trait "Hack" is not dmdging armor

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1776]
If damage applied to an armored character using a weapon with "Hack" trait, APs aren't reduced. Have to reduce it manually which is always remains forgotten...<br/>**From**: Wolenard<br/>foundry: 11.308<br/>wfrp4e: 7.0.2<br/>wfrp4e-altdorf: 4.0.1<br/>wfrp4e-archives1: 4.0.1<br/>wfrp4e-archives2: 4.0.1<br/>wfrp4e-core: 4.0.1<br/>wfrp4e-dotr: 4.0.1<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-empire-ruins: 4.0.1<br/>wfrp4e-horned-rat: 4.0.1<br/>wfrp4e-middenheim: 4.0.1<br/>wfrp4e-owb1: 4.0.1<br/>wfrp4e-pbtt: 4.0.1<br/>wfrp4e-rnhd: 4.0.1<br/>wfrp4e-starter-set: 4.0.0<br/>wfrp4e-ua1: 4.0.1<br/>wfrp4e-ua2: 4.0.1<br/>wfrp4e-up-in-arms: 4.0.1<br/>wfrp4e-wom: 4.0.1<br/>wfrp4e-zoo: 4.0.1<br/>Active Modules:

**Comment by moo-man** [comment]
This is done manually, as the system doesn't know what to damage.

**Comment by GregorHak** [comment]
You have to do it manually, but you get a notification in the chat, just read the chat, then maybe you won't forget.
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/c50c9ab1-52d2-4193-bcc1-8499668cc271)
