### ISSUE TITLE
[WFRP4e System] No more sounds

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#179]
Hi , 
even after copying over the sound from an archive, no sounds are coming when running a combat.
is there something in the code that have changed?
in your text file, it says that copying the sounds should be enough , but seems not 

thanks in advance for your support<br/>**From**: guillaumesarazin@gmail.com<br/>wfrp4e: 3.1.0<br/>wfrp4e-core: 1.1<br/>wfrp4e-rnhd: 1.02<br/>wfrp4e-starter-set: 1.02

**Comment by moo-man** [comment]
It's currently a bug with 0.7.6, if it continues to not work after 0.7.7, please reopen this issue.

**Comment by guillaumecd15** [comment]
Thanks , btw, i ve just get the EIS module, good job ;)

**Comment by moo-man** [comment]
Thanks! :)

**Comment by guillaumecd15** [comment]
Issue happens only from the VTT console, not if you are using the web browser ( just for info)

**Comment by moo-man** [comment]
As far as I know, it's not that. It's that you can only hear audio triggered by other people

**Comment by guillaumecd15** [comment]
Yes i ve notice it too. I need a  player to get the sound

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________
