### ISSUE TITLE
Enhanced Healing Draught effect

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1790]
### Describe:
Hey, what do you think about the changes I made to Healing Draught? Can you consider use this changed code?

**Source of current Healing Draught:**
```javascript
let wounds = this.actor.status.wounds
if (wounds.value == 0)
  return ui.notifications.error("No effect at 0 Wounds")

ui.notifications.notify(`Healed ${this.actor.characteristics.t.bonus} Wounds`)
this.actor.modifyWounds(this.actor.characteristics.t.bonus)
```

**Source of my suggestion to Healing Draught:**
```javascript
let wounds = this.actor.status.wounds.value;
let max = this.actor.status.wounds.max;


if (wounds === 0)
  return ui.notifications.error("No effect at 0 Wounds, wasted a dose")
if (wounds === max)
  return ui.notifications.error("No effect, Wounds were already max, wasted a dose")


let tbonus = this.actor.characteristics.t.bonus;
let missing = max - wounds;
let recovered = missing < tbonus ? missing : tbonus;

this.actor.modifyWounds(recovered);
return ui.notifications.notify(`Healed ${recovered} Wounds`);
```

### What I do is:
Reminder that dose was used (in both codes has reduce quantity on use), and even when there is no effect display a notification that dose was wasted.
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/aef4c270-dc9d-4a28-be71-1176e039e296)

display notifications when wounds were already max
```javascript
if (wounds === max)
  return ui.notifications.error("No effect, Wounds were already max, wasted a dose")
```

If character has fewer missing Wounds (to max) than his Toughness bonus notifications will display the practical number of Wounds that are healed, not the amount of Toughness bonus.
eg. When character has Toughness bonus = 2 and 9/10 Wounds then notifications display that heal 1 Wound not 2 (because in practice it actually heals 1 wound)
```javascript
let tbonus = this.actor.characteristics.t.bonus;
let missing = max - wounds;
let recovered = missing < tbonus ? missing : tbonus;
```

**Comment by moo-man** [comment]
Effect has been reworked during the effect refactor

**Comment by GregorHak** [comment]
When update arrive, I will look on its

**Comment by moo-man** [comment]
You can see the scripts now, it uses https://github.com/moo-man/WFRP4e-FoundryVTT/blob/master/scripts/xUpKYT7BZCSmAfUy.js and https://github.com/moo-man/WFRP4e-FoundryVTT/blob/master/scripts/2zeP2nMSURjxrqYz.js
