### ISSUE TITLE
[Archives of the Empire: Vol 2.] Shield of Ptolos code not working

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1791]
When I use the Shield of Ptolos (Magic Shield that can be generated from a macro) to oppose a ranged attack, I cannot apply damage. No bug appears on the screen, but in console an error can be seen "Uncaught Reference Error". When I remove the shield effect, I can apply damage normally from the same check resolution. So, I think the shield effect code is not up to v11 and somehow blocks applying the damage. 

I have not checked other items from AoE2 module, but perhaps it would be a good idea to re-check them.

Thank you!<br/>**From**: nicodavout@gmail.com<br/>foundry: 11.308<br/>wfrp4e: 7.0.2<br/>wfrp4e-archives2: 4.0.1<br/>wfrp4e-core: 4.0.1<br/>Active Modules:

**Comment by nicodavout** [comment]
I attach the error screenshot.
![Capture](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/97904978/8ac418a6-e806-4d52-9293-aa6e59bbd027)

**Comment by moo-man** [comment]
Nothing to do with V11, effect has always been bugged

So you don't have to try and generate it again, here's the script that works

```js
if (args.opposedTest.attackerTest.weapon.attackType == "ranged")
{
     args.opposedTest.defenderTest.weapon.properties.qualities.shield.value += 2
}
```
