### ISSUE TITLE
[Enemy In Shadows] Initialisation of EiS is not working

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#180]
I have a game world that included initialised modules of the Core set, Starter Set and Rough Nights. (Also Dice so Nice)
I go to add EiS, click on initialise.
The initialisation reports a bunch of errors.
Most seem to be saying:
- A compendium item cannot be updated because that compendium is locked.
- An item cannot be update with a property value of 'max'
These error messages are not precise. The messages fade quickly.
If this info is insufficient, I will happily make a video for you, just ask.

When initialiasaion is 'complete', I go to look at the EiS items. Many are missing.
<br/>**From**: Robert Knowles-Leak<br/>wfrp4e: 3.0.2<br/>wfrp4e-core: 1.1<br/>wfrp4e-rnhd: 1.02<br/>wfrp4e-starter-set: 1.02

**Comment by RKnowlesLeak** [comment]
Having watched a tad more of you video, found the console in Foundry, and signed up to GitHub, I am probably in a better position to give you more info if you need it.
Just ask.

Great work by the way.

**Comment by moo-man** [comment]
Please update the WFRP system

**Comment by RKnowlesLeak** [comment]
Done and that worked.
Thank you for your help and prompt response.
Excellent work! You deserve great credit.
