### ISSUE TITLE
Torn Body Muscle (Major) wrong name in link

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#1805]
**Instead link to "Broken Bones", should be "Torn Muscles"**

![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/c7a52d68-6e5f-4b8c-ae3f-9de1c6196593)

**Now in Foundry**
```javascript
<p>@UUID[Compendium.wfrp4e-core.journals.NS3YGlJQxwTggjRX.JournalEntryPage.WCivInLZrqEtZzF4#major]{Broken Bones}</p>
<p>A muscle has been sprained or torn, impairing your capabilities.  </p><p><strong>Body:</strong> Suffer a penalty of -20 to all Tests involving the body</p>
```

**Should be**
```javascript
<p>@UUID[Compendium.wfrp4e-core.journals.NS3YGlJQxwTggjRX.JournalEntryPage.WCivInLZrqEtZzF4#minor$1]{Torn Muscle}</p>
<p>A muscle has been sprained or torn, impairing your capabilities.  </p><p><strong>Body:</strong> Suffer a penalty of -20 to all Tests involving the body</p>
```

**Comment by GregorHak** [comment]
Also wrong name in link is here:
**Instead link to "Broken Bones", should be "Torn Muscles"**
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/4048aae4-7391-4849-8e72-158710755d2d)

Also wrong name in link is here:
**Instead link to "Broken Bones", should be "Torn Muscles"**
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/85350237-2530-4041-bd52-974b654ed5a9)



Also missing whole link here:
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/5634d74d-9463-402f-8221-08128618513e)

**Comment by GregorHak** [comment]
Also Broken Leg Minor (Injury item type) has blank Penalty field
Should have: -20 to mobility Tests, cannot use Dodge, half Move like in Broken Leg Minor
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/a1111a64-a91e-4158-beda-efe9387c2351)
![obraz](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/99994770/7bec3a64-c6c8-4338-ae00-cd4d2166ddf6)

**Comment by moo-man** [comment]
I swear I've fixed these god damned items twenty times by now

**Comment by GregorHak** [comment]
I know, sorry
