### ISSUE TITLE
[Empire in Ruins] Missing spells and weapon/gear effects

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1811]
The spells on Grey Seer Skrittar are missing. Also missing is the special weapon effect for Maliss' Warpblade Halberd and the effect of his Warpsmoke Generator.<br/>**From**: tomwithadon<br/>foundry: 11.308<br/>wfrp4e: 7.0.3<br/>wfrp4e-altdorf: 4.0.1<br/>wfrp4e-archives1: 4.0.2<br/>wfrp4e-archives2: 4.0.2<br/>wfrp4e-core: 4.0.2<br/>wfrp4e-dotr: 4.0.2<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-empire-ruins: 4.0.2<br/>wfrp4e-horned-rat: 4.0.2<br/>wfrp4e-middenheim: 4.0.1<br/>wfrp4e-owb1: 4.0.1<br/>wfrp4e-pbtt: 4.0.2<br/>wfrp4e-rnhd: 4.0.1<br/>wfrp4e-starter-set: 4.0.0<br/>wfrp4e-ua1: 4.0.1<br/>wfrp4e-ua2: 4.0.2<br/>wfrp4e-up-in-arms: 4.0.1<br/>wfrp4e-wom: 4.0.1<br/>wfrp4e-zoo: 4.0.1<br/>Active Modules: arms-reach, ATL, compendium-folders, dice-so-nice, drag-all-to-hotbar, drag-ruler, forien-armoury, foundryvtt-simple-calendar, item-piles, lib-wrapper, socketlib, stairways, times-up, vtta-tokenizer, wfrp4-wfrp4e-npc-generator, wfrp4e-dotr-maps, wfrp4e-eis-maps, wfrp4e-gm-toolkit, wfrp4e-pbth-maps, wfrp4e-ubersreik-maps

**Comment by TomWithADon** [comment]
Sorry I put this under the wrong module. This should be under The Horned Rat
