### ISSUE TITLE
Automatically update Career item, Trappings, characteristics, Income, skills items and talents when updating Career level

### ISSUE THREAD

**Issue by GittaNaba2021** [moo-man/WFRP4e-FoundryVTT#1817]
Hello,

Foundry VTT v11 Build 313 with WFRP 7.0.3 here.

When updating a Career level, Trappings, characteristics, Career item, skills and talents are not updated automatically, everything must be updated manually.

**Describe the solution you'd like**
It would be very nice if Career item, Trappings, Income and characteristics at least could be updated automatically. Updating and Career skills and Talents would be even nicer but would probably require more interactions with the player.

By example, 
Someone with the Career item "Villager" starts as "Peasant", with S/T/Agi as characteristics, Skills like Animal Care, Athletics, etc. , Talents like Rover, Strong Back etc.

When you edit the Career item in the "Main" tab of the Character sheet, and move Career level from 1 to 2, nothing is updated :
- Career item stays "Peasant, should be "Villager"
- Characteristics are still S/T/Agi, shoudl now include "WS" too
- Income is still Brass 2, should be Brass 3
- Skills are still  Animal Care, Athletics, etc, should be Drive, Entertain (Storytelling) etc.
- Talents are still Rover, Strong Back etc. , should be Animal Affinity, Hardy etc.
- Trappings are still none, should include Leather Jerkin, Hand Weapon (Axe), etc.

Sheers,

**Comment by moo-man** [comment]
Not sure I really understand the issue, if I do, career tiers are each their own item. If you're changing them, you will need to reflect those changes yourself.

**Comment by GregorHak** [comment]
If You want move Career level from 1 to 2:
JUST drag Career level 2 to character sheet and check "Current" next to Career in Main Tab. 

If you wanna lern how to do things in Foundry with WFRP check yt tutorial videos or take a look:

10 Useful Things You Might Not Know About WFRP4e on Foundry VTT 
https://cubicle7games.com/blog/10-useful-things-you-might-not-know-about-wfrp4e-on-foundry-vtt

13 More Useful Things You Might Not Know About WFRP4e on Foundry VTT
https://cubicle7games.com/blog/13-more-useful-things-you-might-not-know-about-wfrp4e-on-foundry-vtt

**Comment by GittaNaba2021** [comment]
Hello, I tought updating Career level would automatically update everything related to this Career, just like the autolevel feature in DD5 Foundry system.
I was mistaken, updating Career just changes the number, nothing else. As you say, you have to drag and drop them.
Thanks for your response anyway !
