### ISSUE TITLE
[WFRP4e System] UI optimization for combat with standard NPC

### ISSUE THREAD

**Issue by francoisChe** [moo-man/WFRP4e-FoundryVTT#1830]
Hi Moo-man,

I've recently mastered a massive combat with gobelins hord against my group with his allies. It was very long for my players and very slow for me, but I identified some simple improvement ideas for faster combat.

First two UI optimization would be convenient : 
1. I think it's possible to display targets list in launch interface. (Adding from a list of targets in token view would be even better).

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/147914309/e193cb15-abdb-4aac-9d92-0ba1d1e84feb)

2. I thought it might be appropriate to add to the opposing test message combat actions as presented in the "Token Action Hud Classic" or a list of chosen tests (standard, define for the pc, or proposed for the active skill). The target PC or the GM would only have to click in the majority of cases and for the 30% others the actual system remains.
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/147914309/7bf67afb-bc00-4123-a569-c7c715c24a60)
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/147914309/ee56b9f1-c179-4450-a153-7c19c62c1b8f)

Third idea is more complicated. But it is frequent standard NPC duels even outside of mass battles. I would imagine a macro. This Macro opens an interface with one columns for active token and one for the target. 3 lines:
1. choice of an action for the attacker and defender based on the “Token Action Hud Classic” model
2. classic throwing panel
3. checkbox to apply damage type and crit automatically.
The throw button display a summary whisper in the chat (without the different steps to avoid noise). 

 So we would have the follow use case: 
1. turn order next, 
4. target, 
5. macro, 
6. definition of options, 
7. throw button, 
8. display in the chat of the summary of the weapon pass, 
9. narration by the GM. 

A module is possible but I have the impression that there is more a question of assembling existing bricks than of really creating one. Ideally this would be included in the system to avoid regressions. Whithout cover every case possible this interface is good for 70% times without conflict with the standard system.

What do you think of my ideas and will these additions be possible in the Warhammer Core?

**Comment by francoisChe** [comment]
Hi Moo-man, Migth we hope these developments in 7.2 ?

**Comment by moo-man** [comment]
Here is what I have implemented:

https://github.com/moo-man/WFRP4e-FoundryVTT/assets/28637157/c49eb727-a18f-45a2-9fdf-a22f226833f7

**Comment by francoisChe** [comment]
Nice, ! 

Weapon 1 is it the equiped weapon like shield ? 

Add buton for Improvised weapon would be convenient for example if the personnage use an crossbow at CC.  Idem for wihitout weapon.

**Comment by moo-man** [comment]
It is the first equipped melee weapon, and trait is the first melee trait

**Comment by francoisChe** [comment]
For defense the shield add +1 DR Bonus, but it is not often the first weapon, it it ? Dagger is it the second weapon ?

**Comment by moo-man** [comment]
First weapon would be whichever was added to the actor first.

**Comment by francoisChe** [comment]
To avoid Accidental click, unopposed button  may be in red and why not on the same line than the tokens.  

So 3 to 6 buttons for standard reaction should be readable : 
1.  (if you add an Configurable button for the personnage or the token.)
2. dodge, 
3. Disarmed
5. Improvised weapon (change equipment may be long for player, it would be more fluid )
4. (if first equiped weapon,)
5. (if second equiped weapon (for NPC trait I understand the order problem if you have more than 2),

**Comment by moo-man** [comment]
I'm keeping this minimal, this isn't intended to be a complete and configurable solution, but a quick-access QoL improvement.

**Comment by francoisChe** [comment]
Sorry if I'm a little picky about this feature, but it seems to me that t has a important ROI for QoL in combat. 

In case 4 and 5, if it is a trait, you could choose weapon with Defense Bonus priority (Weapon Extension  included ?). A shield should be proposed before first bow. A bow is an improvised weapon at CC, so an imporvised weapon or disarmed is often used without to modify equipment.

I understand 6 require more work to implement choice GUI, but I think you should keep this QoL idea in the raodmap. This configurable button add flexibility at fluidity, for example for a player strategy or special reaction in a scene. For the player a macro could be a close job, but for NPC the GM would improve the readability.

The heaviest version for GUI could done that (where 4-6 is only visible when relevant) :
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/147914309/55d8a33f-68ec-4963-8693-7621247ff3e0)

**Comment by Forien** [comment]
I think adding too many options will be detrimental. When you have 6 buttons and 3 of them are weapons that you need to hover to know which is which, its no longer QoL.

At that point it would be equal to using Token Action HUD, or even clicking on portrait in chat or tapping C to open a sheet and clicking on weapon.

I think at maximum there should be only 5 buttons, although 4 is ideal:

1. Dodge
2. Weapon trait
2. Main hand weapon (get first if there are multiple) 
3. Offhand weapon (get first if there are multiple) 
4. Unopposed

And buttons should only appears if given item is found (wiht exception of dodge and u opposed).  
Most actors with weapon dont have weapon trait, so they would see 3-4 buttons. Most actors with weapon trait dont have weapon items, so they would see 3 buttons.

**Comment by francoisChe** [comment]
For a player, "C" or HUD is fast, but GM must click before on the targueted token which the player chose. Click on the portrait, his the first step after you must navigate among the tabs. Here it's only shortcut for basic combat action. For minor NPC, you don't need more in 70% of cases. 

I agree with "And buttons should only appears if given item is found" or if a configurable action is chosen. Why not in different color ? If unopposed is on the token line you have beetwen 3 to 6 buttons for reactions. Hovering will only be necessary at the beginning or to check the linked actions for the weapon and configurable action. 

For Icons, 
1. I like shield idea, but may be a sword and a number (1, 2) or a Letter (R, L) would be more generic. 
2. Improvised -> a mass,  
3. Dodge -> perfect, 
4. Disharmed -> a hand, 
5. configurable action -> a star.

**Comment by francoisChe** [comment]
It's a personal flavour, Better, an option  heavy or ligth in parameters ;)
