### ISSUE TITLE
Ogre's Aren't Appearing in Character Creation

### ISSUE THREAD

**Issue by TheyWhoLaugh** [moo-man/WFRP4e-FoundryVTT#1852]
**Describe the bug**
I have installed Archives of the Empire Vol 2 and the Ogre's aren't appearing when character creation occurs, star signs are appearing however.

**To Reproduce**
I type /char in chat to start character creation and when I click species, Ogre is not among the listed for the 1d00 roll.

**Screenshots**

**Version Numbers**

![General Information](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/110943723/64f194a6-0657-4e61-86bd-22f08f37a64f)

Foundry:
wfrp4e:
wfrp4e-core:
wfrp4e-starter-set:
wfrp4e-rnhd:
wfrp4e-eis:
wfrp4e-ua1:
wfrp4e-dotr:
wfrp4e-archives1:
wfrp4e-middenheim:
wfrp4e-archives1:
wfrp4e-pbtt:
wfrp4e-altdorf:
wfrp4e-ua2:
wfrp4e-owb1:
wfrp4e-horned-rat:
wfrp4e-empire-ruins:

**Comment by moo-man** [comment]
Please consult the instructions on how to modify the Table Settings, located in the **Ogre Characters** Journal Entry.

**Comment by TheyWhoLaugh** [comment]
Got those on Discord, thanks mate you can make this as solved.
