### ISSUE TITLE
[Death on the Reik] Size and Damage calculations breaks equipping vehicle weapon

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1854]
From MooMan's homebrew options, have "Size and Damage calculations" active breaks equipping vehicle weapons. You can drag weapons onto the sheet but cannot click "equip"
I tried this on several types of boat, and with several weapons<br/>**From**: .simonius<br/>foundry: 11.315<br/>wfrp4e: 7.0.3<br/>wfrp4e-altdorf: 4.0.1<br/>wfrp4e-archives1: 4.0.2<br/>wfrp4e-archives2: 4.0.2<br/>wfrp4e-core: 4.0.2<br/>wfrp4e-dotr: 4.0.2<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-empire-ruins: 4.0.2<br/>wfrp4e-horned-rat: 4.0.2<br/>wfrp4e-middenheim: 4.0.2<br/>wfrp4e-owb1: 4.0.2<br/>wfrp4e-pbtt: 4.0.2<br/>wfrp4e-rnhd: 4.0.1<br/>wfrp4e-salzenmund: 4.0.1<br/>wfrp4e-starter-set: 4.0.0<br/>wfrp4e-ua1: 4.0.1<br/>wfrp4e-ua2: 4.0.2<br/>wfrp4e-up-in-arms: 4.0.1<br/>wfrp4e-wom: 4.0.1<br/>wfrp4e-zoo: 4.0.1<br/>Active Modules: ATL, adventuremusic, ambiences-vol-1-michael-ghelfi, ambiences-vol-2-michael-ghelfi, ambiences-vol-3-michael-ghelfi, ambiences-vol-4-michael-ghelfi, ambiences-vol-5-michael-ghelfi, ambiences-vol-6-michael-ghelfi, compendium-navigator, cursor-hider, dice-so-nice, dungeon-draw, forge-vtt-shared-compendiums-wfrp-custom-1, forien-quest-log, foundry-ready-big-city-slums-1-levels-and-flats, foundry-ready-dock-town, foundry-ready-gothic-mansion, foundry-ready-medium-city-1, foundry-ready-medium-city-2, foundry-ready-sewers, foundry_community_macros, healthEstimate, hide-gm-rolls, initiative-double-click, lib-wrapper, louder-whispers, monks-combat-marker, multi-token-edit, music-permissions, permission_viewer, popout, settings-extender, simple-dice-roller, simplefog, toggle-snap-to-grid, token-action-hud, tomcartos-anglers-wharf, tomcartos-bandit-hideout, tomcartos-bifrond-bazaar, tomcartos-ostenwold, tomcartos-pub-crawl, tomcartos-shilby-corporation-warehouse, vtt-resource-tracker, wfrp4e-gm-toolkit, wfrp4e-random-treasure, zsync, forge-vtt

**Comment by Forien** [comment]
Error seems to be caused by `mooSizeDamage`, specifically, trying to access the `actor.sizeNum` on `vehicle`.

It's these lines in `modules/item/item-wfrp4e.js`:
https://github.com/moo-man/WFRP4e-FoundryVTT/blob/5387bce286a9950c62221a21adb68e2093b44503/modules/item/item-wfrp4e.js#L1974-L1975

Or no effect-refactor branch these lines in `modules/model/item/weapon.js`:
https://github.com/moo-man/WFRP4e-FoundryVTT/blob/a9e0eb1d152fdb85a4c56258ac8063ba7da6e116/modules/model/item/weapon.js#L109-L110
