### ISSUE TITLE
All rolls are 99

### ISSUE THREAD

**Issue by Guzozzzo** [moo-man/WFRP4e-FoundryVTT#1890]
**Describe the bug**
All attack/skill/check rolls are 99, Initiative is 20

**To Reproduce**
If applicable, provide steps to reproduce this issue

**Screenshots**

**Version Numbers**
7.0.3, 6.6.1

Foundry:
wfrp4e:

**Comment by moo-man** [comment]
Ensure core module is updated by reinstalling it.
