### ISSUE TITLE
[Core Rulebook] Minor Infection link dead in End of Combat Reminder chat bubble

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1891]
In the End of Combat Reminder chat bubble, the Minor Infection link is dead even though there is a compendium entry for it.<br/>**From**: #florian0236<br/>foundry: 11.315<br/>wfrp4e: 7.0.3<br/>wfrp4e-core: 4.0.2<br/>Active Modules: actually-private-rolls, barbrawl, dice-so-nice, levels, lib-wrapper, monks-active-tiles, popout, tagger, theripper-premium-hub, wall-height

**Comment by florian-denizot** [comment]
![Screenshot 2024-02-22 154548](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/1583894/d781f4f4-0373-47ea-9d92-792f42dbd543)
