### ISSUE TITLE
[Middenheim: City of the White Wolf] [Power Behind the Throne] the grand duchy of Middenheim journal text overlap

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1892]
The Grand Duchy of Middenheim, many pages appear with text overlapping more text<br/>**From**: @telles007<br/>foundry: 11.315<br/>wfrp4e: 7.0.3<br/>wfrp4e-altdorf: 4.0.1<br/>wfrp4e-archives1: 4.0.2<br/>wfrp4e-core: 4.0.2<br/>wfrp4e-dotr: 4.0.2<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-middenheim: 4.0.2<br/>wfrp4e-pbtt: 4.0.2<br/>wfrp4e-up-in-arms: 4.0.1<br/>wfrp4e-wom: 4.0.1<br/>Active Modules: ATL, CautiousGamemastersPack, JB2A_DnD5e, SharedVision, WhisperBox, advanced-drawing-tools, autoanimations, autocomplete-whisper, colorsettings, df-curvy-walls, dice-so-nice, drag-ruler, forge-vtt-shared-compendiums-ingredients-feitos-por-mim, forge-vtt-shared-compendiums-landing-page, forge-vtt-shared-compendiums-telles-compendium, foundryvtt-simple-calendar, healthEstimate, image-hover, item-piles, journal-icon-numbers, journal-whiteboard, lib-df-buttons, lib-wrapper, monks-active-tiles, monks-bloodsplats, monks-combat-details, monks-combat-marker, monks-common-display, monks-little-details, party-overview, perceptive, popout, remote-highlight-ui, routinglib, sequencer, settings-extender, smart-doors, smarttarget, socketlib, token-action-hud-core, token-action-hud-wfrp4e, token-attacher, torch, wfrp4e-dotr-maps, wfrp4e-eis-maps, wfrp4e-gm-toolkit, wfrp4e-pbth-maps, wfrp4e-ubersreik-maps, forge-vtt

**Comment by telles-dajello** [comment]
It seems to happen only when viewing the journals in multiple pages

**Comment by moo-man** [comment]
Closing until further details provided
