### ISSUE TITLE
[WFRP4e System] Rolls are blank/not displayed

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1895]
Dice rolls on the chat are not displaying. The chat shows an empty field as if I had enabled the dice roll modification option. Clearly, I did not activate this option.
I was sure it was a modules issue (although the problem only appeared while modifying the settings of Moo Man's house rules).
Steps I took:

> removed all modules (the problem did not disappear)
> restored the factory settings (the problem did not disappear)
> uninstalled and reinstalled the WHFRP 4ed module (the problem did not disappear)
> uninstalled and reinstalled Foundry VTT (the problem did not disappear)

I am out of ideas on what to do and am asking for help. Below, I am including the chat log in txt format with the error. Thank you in advance for your help.

[3/4/2024, 2:09:26 PM] New Actor
Initiative Test
Roll:  vs 20
Roll:  vs
SL:
SL:
Description: Astounding Failure
---------------------------
[3/4/2024, 2:10:01 PM] Gamemaster
3
2d6 = 3 = 3
---------------------------
[3/4/2024, 2:10:33 PM] New Actor
Dexterity Test
Roll:  vs 20
Roll:  vs
SL:
SL:
Description: Failure
---------------------------
[3/4/2024, 2:13:08 PM] New Actor
Intelligence Test
Roll:  vs 20
Roll:  vs
SL:
SL:
Description: Impressive Failure<br/>**From**: tow.bieda<br/>foundry: 11.315<br/>wfrp4e: 7.0.3<br/>Active Modules:

**Comment by Forien** [comment]
Sanity check:

Do you have by any chance, `Manual chat cards` enabled?

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/78a45d26-16d7-456f-ad02-b01ff3615235)

**Comment by MechaP0744** [comment]
Perception check: Impressive failure 
Sigmar has finally forsaken me for I didn't find this by my self. Ofc it solves it, sorry for trouble
