### ISSUE TITLE
[Winds of Magic] Wom Academics classes in "Academic" class, not "Academics"

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1896]
as in description, its just missing an s at the end. 
as far as i can see it effects Mundane Alchemist [and tiers] and  Magister Vigilant [and Tiers]<br/>**From**: thefirst5<br/>foundry: 11.315<br/>wfrp4e: 7.0.3<br/>wfrp4e-altdorf: 4.0.1<br/>wfrp4e-archives1: 4.0.2<br/>wfrp4e-archives2: 4.0.2<br/>wfrp4e-core: 4.0.2<br/>wfrp4e-dotr: 4.0.2<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-horned-rat: 4.0.2<br/>wfrp4e-middenheim: 4.0.2<br/>wfrp4e-pbtt: 4.0.2<br/>wfrp4e-rnhd: 4.0.1<br/>wfrp4e-up-in-arms: 4.0.1<br/>wfrp4e-wom: 4.0.1<br/>wfrp4e-zoo: 4.0.1<br/>Active Modules: _chatcommands, about-face, chat-commander-wfrp4e, dd-import, drag-ruler, easy-target, fast-flip, forien-armoury, foundryvtt-simple-calendar, fxmaster, lib-wrapper, popout, quick-insert, smalltime, socketlib, stairways, times-up, token-action-hud-core, token-action-hud-wfrp4e, token-z, tokenmagic, wfrp4e-gm-toolkit, wfrp4e-night-vision, forge-vtt

**Comment by Forien** [comment]
Related / potential duplicate to: #1862
