### ISSUE TITLE
Module Incompatibilities

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#19]
- [x] Forien's Quest Log
- [x] Dungeondraft Import
- [x] Onejournal
- [ ] Custom Journal
- [ ] Tidy UI
- [x] Calendar

**Comment by manueleiria** [comment]
I'm having a few issues with GM Notes, where the notes visualization doesn't have a proper background for readability. Would it be possible to add support to it to have the same styling as regular journal pages?

![image](https://user-images.githubusercontent.com/829117/95688348-87eeb200-0c01-11eb-9474-3bd9fba7e3b4.png)

**Comment by manueleiria** [comment]
Appears to have similar behaviour on OneJournal, oddly...

![image](https://user-images.githubusercontent.com/829117/95781407-aa4a0380-0cc5-11eb-93aa-b5ed9ff1a10f.png)

**Comment by hockeyfilo** [comment]
i ahve the same problem in a whisper module

**Comment by DasSauerkraut** [comment]
On version 3.0, the 'show text', 'show image', and 'close' buttons for journal entries occlude the MINDMAP button from Moerill's Mindmap, making it impossible to open.
![image](https://user-images.githubusercontent.com/9422721/98430949-fb57d800-2076-11eb-8682-e649f4171bd6.png)
If an existing entry is a mindmap, it is impossible to close as the 'close' button does not exist
![image](https://user-images.githubusercontent.com/9422721/98430962-22160e80-2077-11eb-9d26-b0e88663269e.png)
