### ISSUE TITLE
[Winds of Magic] Suffuse with <wind> — Incorrent effects

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1902]
`Suffuse with <wind>` effects incorrectly add +1 SL Bonus to Channelling Tests, while they should add +1 **Success SL** to **Casting** Tests. 
<br/>**From**: forien<br/>foundry: 11.315<br/>wfrp4e: 7.0.3<br/>wfrp4e-altdorf: 4.0.1<br/>wfrp4e-archives1: 4.0.2<br/>wfrp4e-archives2: 4.0.2<br/>wfrp4e-core: 4.0.2<br/>wfrp4e-dotr: 4.0.2<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-middenheim: 4.0.2<br/>wfrp4e-pbtt: 4.0.2<br/>wfrp4e-rnhd: 4.0.1<br/>wfrp4e-salzenmund: 4.0.1<br/>wfrp4e-starter-set: 4.0.0<br/>wfrp4e-up-in-arms: 4.0.1<br/>wfrp4e-wom: 4.0.1<br/>wfrp4e-zoo: 4.0.1<br/>Active Modules: ATL, JB2A_DnD5e, _CodeMirror, _chatcommands, arms-reach, autoanimations, chat-commander-wfrp4e, colorsettings, custom-css, darkraven-games-soundscapes-free, dfreds-chat-pins, dfreds-effects-panel, dice-so-nice, entice-with-dice-so-nice, forien-actors-summary, forien-ammo-swapper, forien-armoury, forien-copy-environment, forien-custom-utility, forien-easy-polls, forien-quest-log, forien-unidentified-items, foundryvtt-simple-calendar, image-hover, item-piles, ivan-duch-music-packs, levels, lib-wrapper, light-switch, local-shared-compendiums, michaelghelfi, monks-hotbar-expansion, moulinette-core, moulinette-imagesearch, moulinette-scenes, moulinette-tiles, multi-token-edit, permission_viewer, polyglot, popout, quick-insert, remote-highlight-ui, sequencer, socketlib, soundfxlibrary, stairways, sweetnothings, tabletop-rpg-music, times-up, token-action-hud-core, token-action-hud-wfrp4e, token-ease, token-variants, trs-foundryvtt-dice-set, trs-metal-rainbow, update-your-password, wall-height, wfrp4e-dotr-maps, wfrp4e-gm-toolkit, wfrp4e-random-treasure, wfrp4e-unofficial-grimoire

**Comment by Forien** [comment]
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/c21398e6-d74f-4213-9b80-f0f34e038b0c)

### This is incorrect:
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/e87cc2cc-c125-4c67-bb1c-75eaa15b8de2)

### Should add here instead:
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/763c427e-1235-4468-8306-358170641673)
