### ISSUE TITLE
WFRP4e module - skill rolls broken

### ISSUE THREAD

**Issue by Lecht42** [moo-man/WFRP4e-FoundryVTT#1904]
**Describe the bug**
I'm trying to set up a game in Warhammer Fantasy Roleplay 4th edition, but I've run into an issue: every roll is 99. Every one. I can't for the life of me figure out why.

**To Reproduce**
1) Create any actor 
2) Roll any skill

**Screenshots**
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/23343666/31b86f66-e592-4fa2-8052-589e5119b812)

**Version Numbers**
Foundry: v11 b315
wfrp4e: 7.0.3
Node: 21.7.1

**Example of corrupted message roll**
`{
    "key": "IIGJHBoglsvcdqiE",
    "value": {
        "speaker": {
            "alias": "August Sokhmann",
            "actor": "q4ijmJl3gR5LbsPv",
            "scene": null,
            "token": null
        },
        "flags": {
            "img": "assets/fb/token/token_edgelord.png",
            },
            "testData": {
                "preData": {
                    "title": "Bribery Test",
                    "roll": 99,
                    "rollClass": "SkillTest",
                    "testModifier": 0,
                    "testDifficulty": 0,
                    "successBonus": 0,
                    "slBonus": 0,
                    "hitLocation": false,
                    "item": "d3VZwO4Y5JH5DXdT",
                    "options": {
                        "characteristicToUse": "fel"
                    },
                    "other": [],
                    "canReverse": false,
                    "postOpposedModifiers": {
                        "modifiers": 0,
                        "SL": 0
                    },
                    "additionalDamage": 0,
                    "selectedHitLocation": "none",
                    "hitLocationTable": {
                        "head": "Head",
                        "lArm": "Left Arm",
                        "rArm": "Right Arm",
                        "body": "Body",
                        "lLeg": "Left Leg",
                        "rLeg": "Right Leg"
                    },
                    "prefillTooltip": "Effects which affect dialog values <ul> <li></li></ul>",
                    "prefillTooltipCount": 0,
                    "skillName": "Bribery"
                },
                "result": {
                    "roll": 99,
                    "description": "Astounding Failure",
                    "tooltips": {},
                    "other": [],
                    "title": "Bribery Test",
                    "SL": -6,
                    "target": 37,
                    "rollClass": "SkillTest",
                    "testModifier": 0,
                    "testDifficulty": 0,
                    "successBonus": 0,
                    "slBonus": 0,
                    "hitLocation": false,
                    "item": "d3VZwO4Y5JH5DXdT",
                    "options": {
                        "characteristicToUse": "fel"
                    },
                    "canReverse": false,
                    "postOpposedModifiers": {
                        "modifiers": 0,
                        "SL": 0
                    },
                    "additionalDamage": 0,
                    "selectedHitLocation": "none",
                    "hitLocationTable": {
                        "head": "Head",
                        "lArm": "Left Arm",
                        "rArm": "Right Arm",
                        "body": "Body",
                        "lLeg": "Left Leg",
                        "rLeg": "Right Leg"
                    },
                    "prefillTooltip": "Effects which affect dialog values <ul> <li></li></ul>",
                    "prefillTooltipCount": 0,
                    "skillName": "Bribery",
                    "outcome": "failure"
                },
                "context": {
                    "rollMode": "publicroll",
                    "reroll": false,
                    "edited": false,
                    "speaker": {
                        "actor": "q4ijmJl3gR5LbsPv"
                    },
                    "postFunction": "basicTest",
                    "targets": [],
                    "cardOptions": {
                        "speaker": {
                            "alias": "August Sokhmann",
                            "actor": "q4ijmJl3gR5LbsPv"
                        },
                        "title": "Bribery Test",
                        "template": "systems/wfrp4e/templates/chat/roll/skill-card.hbs",
                        "flags": {
                            "img": "assets/fb/token/token_edgelord.png"
                        },
                        "user": "G17RpOAhzFBZ5PR9",
                        "sound": "sounds/dice.wav",
                        "rollMode": "publicroll",
                        "whisper": [],
                        "blind": false,
                        "content": **some HTML**
                    },
                    "messageId": "IIGJHBoglsvcdqiE",
                    "opposedMessageIds": []
                }
            }
        },
        "user": "G17RpOAhzFBZ5PR9",
        "sound": "sounds/dice.wav",
        "whisper": [],
        "blind": false,
        "content": **some HTML**,
        "_id": "IIGJHBoglsvcdqiE",
        "type": 0,
        "timestamp": 1711626797936,
        "flavor": "",
        "rolls": [],
        "emote": false
    }
}`

**Comment by moo-man** [comment]
Ensure core module is updated by reinstalling it. If that doesn't work, contact me on discord

**Comment by Lecht42** [comment]
I reinstalled the module and now it works fine! Thx
