### ISSUE TITLE
[Rough Nights & Hard Days] Emanuel Naht NPC missing stats

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1913]
When I opened Emanuele Naht caracter sheet id was a basic sheet with 20 in each characteristics and nothing besides that, plus token image was non existent when put on the map. Then it was called Knight Panther with  a black image. <br/>**From**: zaknus.<br/>foundry: 11.315<br/>wfrp4e: 7.0.3<br/>wfrp4e-core: 4.0.2<br/>wfrp4e-rnhd: 4.0.1<br/>wfrp4e-starter-set: 4.0.0<br/>Active Modules:

**Comment by Forien** [comment]
1. Emmanuelle Nacht did not get stat block in RNHD.
2. She only appears in one scenario, where she doesn't interact with PCs directly.
3. She is there undercover as "Knight Panther", a silent bodyguard to General Dabernick iirc. 

Basically, she is setup exactly how book describes her.
