### ISSUE TITLE
[WFRP4e System] FoundryVTT sidebar icons shift 6 places down when collapsing the sidebar

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1914]
Since 1 or 2 versions, the foundryVTT sidebar icons shift down 6 places when collapsing the sidebar, This makes the sidebar unusable and the situation difficult to recover from. The problem is there with no plugins enabled and in different browsers.

<br/>**From**: vincent.vanden.driessche@gmail.com<br/>foundry: 11.315<br/>wfrp4e: 7.0.3<br/>wfrp4e-altdorf: 4.0.1<br/>wfrp4e-archives1: 4.0.2<br/>wfrp4e-core: 4.0.2<br/>wfrp4e-dotr: 4.0.2<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-empire-ruins: 4.0.2<br/>wfrp4e-horned-rat: 4.0.2<br/>wfrp4e-middenheim: 4.0.2<br/>wfrp4e-pbtt: 4.0.2<br/>wfrp4e-rnhd: 4.0.1<br/>wfrp4e-salzenmund: 4.0.1<br/>wfrp4e-starter-set: 4.0.0<br/>wfrp4e-ua1: 4.0.1<br/>wfrp4e-up-in-arms: 4.0.1<br/>wfrp4e-wom: 4.0.1<br/>wfrp4e-zoo: 4.0.1<br/>Active Modules: LockView, LocknKey, MaterialDeck, _chatcommands, autorotate, background-volume, chat-commander-wfrp4e, colorsettings, combat-tracker-dock, dice-calculator, dice-so-nice, fast-flip, forge-vtt-shared-compendiums-warhammer, foundry-vtt-content-parser, foundryvtt-simple-calendar, fuzzy-foundry, fxmaster, healthEstimate, illandril-token-hud-scale, item-piles, lib-wrapper, michaelghelfi, monks-active-tiles, monks-bloodsplats, monks-combat-marker, monks-player-settings, popout, quick-insert, sequencer, smalltime, socketlib, token-action-hud-core, token-action-hud-wfrp4e, token-hud-art-button, token-mold, tokenmagic, trs-foundryvtt-dice-set, trs-housedivided-dice-set, trs-ruby-dice-set, vtta-tokenizer, wfrp4e-gm-toolkit, wfrp4e-pbth-maps, wfrp4e-unofficial-grimoire, forge-vtt

**Comment by v2d2mck** [comment]
This issues also shows up on brand new install of the system, e.g., on ForgeVTT
![Screenshot 2024-04-30 194134](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/98828154/a5438429-6fd2-4ebe-88e2-0344aa9dff47)
