### ISSUE TITLE
[WFRP4e System] WFRP4e: All successful rolls are labeled as "Marginal Failure"

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1915]
Everytime a dice roll is successful, the Description says "Marginal Failure. 'No, but...'"
Unsuccessful rolls are labeled correctly.<br/>**From**: aldarion6691<br/>foundry: 11.313<br/>wfrp4e: 7.0.3<br/>wfrp4e-core: 4.0.2<br/>wfrp4e-dotr: 4.0.2<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-horned-rat: 4.0.2<br/>wfrp4e-pbtt: 4.0.2<br/>wfrp4e-rnhd: 4.0.1<br/>wfrp4e-starter-set: 4.0.0<br/>Active Modules: 1000-fish, ATL, SharedVision, forien-armoury, foundryvtt-simple-calendar, fvtt-syrin-control, game-icons-net, give-item, item-piles, lib-wrapper, nations-of-mankind-wfrp4e, quick-insert, socketlib, the-dwarf-empire-wfrp4e, times-up, token-action-hud-core, token-action-hud-wfrp4e, wfrp4-wfrp4e-npc-generator, wfrp4e-dotr-maps, wfrp4e-eis-maps, wfrp4e-gm-toolkit, wfrp4e-laws-pet-shoppe, wfrp4e-pbth-maps, wfrp4e-random-treasure, wfrp4e-ubersreik-maps, wfrp4e-unofficial-grimoire, wfrp4e-vampires, forge-vtt, forge-vtt-optional

**Comment by Forien** [comment]
Do you have **Automatic Failure** setting set to something low?

**Comment by moo-man** [comment]
Closing until response received from discord or github
