### ISSUE TITLE
[WFRP4e System] Items with 0.01 encumbrance (like coins) sometimes give very precise Encumbrance values

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1933]
Sometimes the Encumbrance Counter gives really precise values such as "1.1400000000000001"

To reproduce:
Create a character. Give it varying amounts of odd coins (or other items with 0.1 or 0.01 encumbrance). At certain values the Encumbrance Counter will not round up or down correctly.

<br/>**From**: thefirst5<br/>foundry: 11.315<br/>wfrp4e: 7.1.2<br/>wfrp4e-core: 5.0.2<br/>Active Modules: quick-insert

**Comment by GregorHak** [comment]
I report something similar earlier:
https://github.com/moo-man/WFRP4e-FoundryVTT/issues/1751
