### ISSUE TITLE
[WFRP4e System] Token showing 

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1938]
Hello 
There is a picrture of a token when you open the token, skill menu. This is after the new, great, update. 

Thanks. <br/>**From**: tormod.robertsen@gmail.com<br/>foundry: 11.308<br/>wfrp4e: 7.1.0<br/>wfrp4e-altdorf: 5.0.1<br/>wfrp4e-archives1: 5.0.1<br/>wfrp4e-archives2: 5.0.0<br/>wfrp4e-core: 5.0.2<br/>wfrp4e-dotr: 5.0.1<br/>wfrp4e-eis: 5.0.1<br/>wfrp4e-empire-ruins: 5.0.1<br/>wfrp4e-horned-rat: 5.0.1<br/>wfrp4e-middenheim: 5.0.1<br/>wfrp4e-owb1: 5.0.1<br/>wfrp4e-pbtt: 5.0.1<br/>wfrp4e-rnhd: 5.0.1<br/>wfrp4e-salzenmund: 5.0.1<br/>wfrp4e-starter-set: 5.0.1<br/>wfrp4e-ua1: 5.0.0<br/>wfrp4e-ua2: 5.0.1<br/>wfrp4e-up-in-arms: 5.0.0<br/>wfrp4e-wom: 5.0.1<br/>wfrp4e-zoo: 5.0.0<br/>Active Modules: JB2A_DnD5e, autoanimations, colorsettings, dice-so-nice, forien-armoury, fxmaster, image-hover, jb2a_patreon, lib-wrapper, monks-active-tiles, monks-bloodsplats, monks-little-details, monks-tokenbar, monks-wall-enhancement, sequencer, socketlib, splatter, token-action-hud, token-attacher, tokenflip, tokenmagic, wfrp4e-gm-toolkit

**Comment by BiggusDixxus** [comment]
![Skjermbilde 2024-04-27 kl  16 21 30](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/168286242/0ed0ed31-3253-46a7-a988-fae8974d934d)

**Comment by moo-man** [comment]
Please ensure you have updated the system and module when troubleshooting
