### ISSUE TITLE
[WFRP4e System] Able to Collapse Container Items

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#194]
Would it be possible to collapse the containers like sling bag or pouch and not show what their content is?<br/>**From**: danil0<br/>wfrp4e: 3.1.0<br/>wfrp4e-core: 1.1<br/>wfrp4e-eis: 1.0<br/>wfrp4e-rnhd: 1.02<br/>wfrp4e-starter-set: 1.02

**Comment by Havoclivekiller** [comment]
Categories and Containers should collapsible. Image having a weapon, 20 items row below, and then a container. You are unable to put the weapon into the container as you can scroll down while dragging the item.

**Comment by moo-man** [comment]
If you hover the dragged item near the bottom it will scroll down.
