### ISSUE TITLE
[WFRP4e System] Randomize Wounds

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#196]
Would it be possible to add a randomize to wounds. So that every creature perhaps get a random number of wounds, similar to the randomize Attributes?
Perhaps a 1d6 - 3 + Max Wounds<br/>**From**: danil0<br/>wfrp4e: 3.1.0<br/>wfrp4e-core: 1.1<br/>wfrp4e-eis: 1.0<br/>wfrp4e-rnhd: 1.02<br/>wfrp4e-starter-set: 1.02

**Comment by moo-man** [comment]
This doesn't really have any basis within the system as written, which follows a formula.

**Comment by danil0man** [comment]
The idea behind is that different creeps have different hp. So the players dont get use that a goblin only have 12 hp, but more random

**Comment by moo-man** [comment]
I understand but that still isn't something that exists anywhere in the rules. Hp is derived from stats, if you want to change it, change the stats, or you can manually edit it. 

If you want randomisation of just HP, that would have to belong in a module because there are no rules for it.
