### ISSUE TITLE
[WFRP4e System] Ammunition effects with Document Actor application are never triggered

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1960]
They are supposed to be added to weapon's effects, and I would assume they would be treated same as Effects on Weapon, so with `Document Actor` they would get further transfered.

This, however, never happens because then weapon effects when transferred to actor double check the `shouldTransferEffect` method via `determineTransfer`.

This means that Ammunition Effects can never be transferred to Actor, even via Weapon. 

`Document Item` works fine as being treated as Effect directly on Weapon. 

<br/>**From**: forien<br/>foundry: 11.315<br/>wfrp4e: 7.1.3<br/>wfrp4e-core: 5.0.2<br/>wfrp4e-up-in-arms: 5.0.0<br/>wfrp4e-wom: 5.0.1<br/>Active Modules: ATL, chat-commander-wfrp4e, forien-actors-summary, forien-ammo-swapper, forien-armoury, forien-easy-polls, foundryvtt-simple-calendar, lib-wrapper, quick-insert, sidebar-macros, socketlib, times-up, token-action-hud-core, token-action-hud-wfrp4e, _chatcommands

**Comment by moo-man** [comment]
I think this is intended, as the concept doesn't make sense

**Comment by Forien** [comment]
> I think this is intended, as the concept doesn't make sense

Right, I got confused by this comment. 

https://github.com/moo-man/WFRP4e-FoundryVTT/blob/126a1c03f5bcec79b98ce1086ea74e652dc0d28a/modules/model/item/ammunition.js#L86

No big deal, I achieved what I wanted with `Item` Document, but wasn't sure if this is intended or not ;)

**Comment by moo-man** [comment]
I'll close this untill any relevant effect needs this
