### ISSUE TITLE
[Sea of Claws] New Vehicle properties 

### ISSUE THREAD

**Issue by Forien** [moo-man/WFRP4e-FoundryVTT#1961]
Vehicles in Sea of Claws should have new System Properties.

- Manoeuvre — shortened "Man", this is represented as a Success Levels Modifier, for example `–2 SL`, `+1 SL` etc. Can probably be normal integer
- Crew — object:
  - Starting — integer representing amount of Crew that vessel started voyage with
  - Current — integer representing amount of Crew still around
- Size — string, required for handling Melee Attacks against ships (SoC, page 116). Can be derived from Length (SoC, Standard Boat Characteristics table, page 96). 
  - Required for combat implementation ( #1965 )
- Morale — integer value. Initial of 75. 
  - Vehicle should also be subject to Effect that depends on the current Morale Value (SoC, page 125).
  - Morale should only be in effect if Vehicle has Crew
  - Related #1962

**Comment by moo-man** [comment]
What about the Sail / Oar characteristic on the table on page 96?

**Comment by Forien** [comment]
> What about the Sail / Oar characteristic on the table on page 96?

Right, I thought they are already implemented with DotR since boats there could have Oars/Sails, but yeah, if it's not, then it would be needed as well
