### ISSUE TITLE
[WFRP4e System] Skill Test "bypass" option not working

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1993]
Scripts can no longer use the bypass option to skip the dialog on a skill test. Formerly there was an option "bypass" that would proceed to roll the test with defined values.<br/>**From**: Discord: Eyestalk#3103<br/>foundry: 11.315<br/>wfrp4e: 7.1.4<br/>wfrp4e-altdorf: 5.0.1<br/>wfrp4e-archives1: 5.0.1<br/>wfrp4e-archives2: 5.0.0<br/>wfrp4e-core: 5.0.4<br/>wfrp4e-dotr: 5.0.2<br/>wfrp4e-eis: 5.0.1<br/>wfrp4e-empire-ruins: 5.0.2<br/>wfrp4e-horned-rat: 5.0.2<br/>wfrp4e-middenheim: 5.0.1<br/>wfrp4e-pbtt: 5.0.1<br/>wfrp4e-rnhd: 5.0.1<br/>wfrp4e-starter-set: 5.0.2<br/>wfrp4e-up-in-arms: 5.0.0<br/>wfrp4e-wom: 5.0.2<br/>Active Modules: ATL, JB2A_DnD5e, _chatcommands, autoanimations, chat-commander-wfrp4e, dice-so-nice, find-the-culprit, forien-armoury, foundry-combat-focus, foundryvtt-simple-calendar, fxmaster, item-piles, levels, lib-wrapper, multi-token-edit, random-target, sequencer, shuggaloafs-simple-npc-generator, smalltime, socketlib, theripper-premium-hub, times-up, token-action-hud-core, token-action-hud-wfrp4e, token-attacher, token-frames, tokenmagic, vtta-tokenizer, wall-height, wfrp4-wfrp4e-npc-generator, wfrp4e-character-details, wfrp4e-gm-toolkit, wfrp4e-more-subspecies

**Comment by nyoung** [comment]
I put it in as a bug, but its really a former script feature that is missing. Would be fine with an alternative.
