### ISSUE TITLE
[Core Rulebook] Add prompt for Specification to more Traits

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2010]
Traits that could use prompt for specification (similar to `Ward` trait or `Size` trait):

- Armour
- Fear
- Terror
- Venom (select dropdown?)
- Grim (Imperial Zoo)
- Spellcaster

If I find more, I will comment under this Issue

<br/>**From**: forien<br/>foundry: 11.315<br/>wfrp4e: 7.1.5<br/>wfrp4e-altdorf: 5.0.1<br/>wfrp4e-archives1: 5.0.1<br/>wfrp4e-archives2: 5.0.0<br/>wfrp4e-core: 5.0.4<br/>wfrp4e-owb2: 5.0.1<br/>wfrp4e-salzenmund: 5.0.1<br/>wfrp4e-up-in-arms: 5.0.0<br/>wfrp4e-wom: 5.0.2<br/>wfrp4e-zoo: 5.0.0<br/>Active Modules: forien-armoury, lib-wrapper, moo-dev

**Comment by Txus5012** [comment]
I would add here the Etiquette talent.
