### ISSUE TITLE
[WFRP4e System] Effect Refactor - Talent Resistance (Chaos)

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2011]
Hi!

I've followed the steps in your excellent guide concerning Effect Refactor and it seemed to work just fine.
I have two halflings in the party with Resistance (Chaos) who unfortunately sees this talent in the list in each and every skill check.
Have you noticed it yourself? Or is there something I can correct on my part?

Best regards,
gustmic<br/>**From**: gustmic (originally Emil100#8185)<br/>foundry: 11.315<br/>wfrp4e: 7.1.5<br/>wfrp4e-core: 5.0.4<br/>wfrp4e-eis: 5.0.1<br/>Active Modules: combat-utility-belt, dice-calculator, dice-so-nice, gm-notes, healthEstimate, lib-wrapper, michaelghelfi, music-d20-sampler, permission_viewer, pings, settings-extender, socketlib, torch, vtta-tokenizer, wfrp4e-actor-sheet-print, wfrp4e-eis-maps, wfrp4e-gm-toolkit

**Comment by GregorHak** [comment]
https://github.com/moo-man/WFRP4e-FoundryVTT/issues/2078
