### ISSUE TITLE
[Enemy in Shadows] Item Directory Enemy in Shadows folder is missing

### ISSUE THREAD

**Issue by PaulMarinaro** [moo-man/WFRP4e-FoundryVTT#2013]
**Describe the bug**
The Item Directory doesn't have the Enemy in Shadows folder with items from the module.  All other relevant directories have Enemy in Shadows folders.

**To Reproduce**
Lauch Game World with the following:

Add-on Modules:
WFRP4e - Enemy in Shadows: 5.0.1
WFRP4e - Core Rulebook: 5.0.4

Game Systems:
Warhammer Fantasy Roleplay 4th Edition: 7.1.5

**Screenshots**

**Version Numbers**
PLEASE PROVIDE YOUR FOUNDRY, SYSTEM, and MODULE VERSIONS (where applicable) 

Foundry: Version 11 Stable - Build 315
wfrp4e: 7.1.5 (Warhammer Fantasy Roleplay 4th Edition - Game System)
wfrp4e-core: 5.0.4 (WFRP4e - Core Rulebook - Add-on Module)
wfrp4e-starter-set:
wfrp4e-rnhd:
wfrp4e-eis: 5.0.1 (WFRP4e - Enemy in Shadows - Add-on Module)
wfrp4e-ua1:
wfrp4e-dotr:
wfrp4e-archives1:
wfrp4e-middenheim:
wfrp4e-archives1:
wfrp4e-pbtt:
wfrp4e-altdorf:
wfrp4e-ua2:
wfrp4e-owb1:
wfrp4e-horned-rat:
wfrp4e-empire-ruins:

**Comment by moo-man** [comment]
Items are not imported during initialization, have you checked the compendium?

**Comment by PaulMarinaro** [comment]
Ok, the compendium has items from the module and core rulebook.  So, there should be nothing in the Items directory after initilization?

**Comment by Forien** [comment]
> Ok, the compendium has items from the module and core rulebook. So, there should be nothing in the Items directory after initilization?

That's correct, there is usually no reason to import Items, as you can use them straight from compendium by dragging them onto Actors' Sheets

**Comment by moo-man** [comment]
You can easily bulk import them via right click, but I don't want to make that decision for you, as it could have performance impacts (though you need a great many items for it to be an issue).

**Comment by PaulMarinaro** [comment]
Got it.  Thanks!  I was watching an old YouTube tutorial.  Maybe things have changed since then.  

Thanks so much for getting back to me so quickly.  I will close this issue.

**Comment by PaulMarinaro** [comment]
Oh, you already did.  Thanks again!
