### ISSUE TITLE
[WFRP4e System] Core Malignant Influence rules do not work

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2025]
Using the core option in the wfrp4e system, ticking Malignant Influence in the casting box does not cause a miscast when the result includes an 8.<br/>**From**: thefirst5<br/>foundry: 11.315<br/>wfrp4e: 7.1.5<br/>wfrp4e-core: 5.0.4<br/>Active Modules: chat-commander-wfrp4e, drag-ruler, forien-armoury, foundryvtt-simple-calendar, lib-wrapper, quick-insert, socketlib, times-up, wfrp4e-gm-toolkit, _chatcommands

**Comment by TheFirst05** [comment]
Sorry please disregard. Failed a reading test ^^"
