### ISSUE TITLE
[WFRP4e System] Player changing advantage causes error to other players

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2041]
1. Have 2 distinct players logged in.
2. Have them both be in combat
3. Have one player edit the advantage (does not matter how/where)
4. Notice other player getting error (I will attach screen in comment), however GM will not
5. Try editing advantage as GM - notice players don't get error

I think it's related to sockets, although I'm not 100% sure

<br/>**From**: forien<br/>foundry: 11.315<br/>wfrp4e: 7.1.5<br/>wfrp4e-core: 5.0.4<br/>wfrp4e-dotr: 5.0.2<br/>wfrp4e-owb2: 5.0.1<br/>wfrp4e-up-in-arms: 5.0.0<br/>wfrp4e-wom: 5.0.2<br/>Active Modules: ATL, chat-commander-wfrp4e, forien-actors-summary, forien-ammo-swapper, forien-armoury, forien-easy-polls, foundryvtt-simple-calendar, item-piles, lib-wrapper, quick-insert, sidebar-macros, socketlib, times-up, token-action-hud-core, token-action-hud-wfrp4e, wfrp4e-gm-toolkit, _chatcommands

**Comment by Forien** [comment]
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/ed45413f-1eb2-487c-add5-b8dfac870cf8)

the `wfrp4e.js:17882` shows me this:

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/71556c9c-1713-496e-9ff5-18116aff69c0)

**Comment by Forien** [comment]
Ah, in case it wasn't obvious, we are using Group Advantage ;)
