### ISSUE TITLE
[WFRP4e System] When recieving EXP players get Error: User (name) lacks permission to update ChatMessage

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2047]
Player clicks "Recieve" -button on Experience Award -card in chat and gets the message: "User [username] lacks permission to update ChatMessage [k2azgD0BbcGxSDqf4]"

Happens with all players, but they still receive the given experience points.<br/>**From**: adenfin#6438<br/>foundry: 11.315<br/>wfrp4e: 7.1.5<br/>wfrp4e-core: 5.0.4<br/>wfrp4e-horned-rat: 5.0.2<br/>wfrp4e-pbtt: 5.0.1<br/>wfrp4e-up-in-arms: 5.0.0<br/>wfrp4e-wom: 5.0.2<br/>Active Modules: colorsettings, conversation-hud, easy-target, foundryvtt-simple-calendar, lib-wrapper, permission_viewer, pings, popout, scaleGrid, settings-extender, socketlib, token-action-hud, torch, vtta-tokenizer, wfrp4e-gm-toolkit, wfrp4e-laws-pet-shoppe, forge-vtt, forge-vtt-optional

**Comment by Forien** [comment]
Does this error appear only for _other_ players? For example there are players A, B and C and if player B clicks on the button, they don't see error but A and C get the error?

If so, then it might be related to issue below:
  - #2041
