### ISSUE TITLE
[WFRP4e System] Material desk for whrp4 doenst work

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2049]
Material desk for whrp4 doenst work<br/>**From**: justnobody789@gmail.com<br/>foundry: 11.315<br/>wfrp4e: 7.1.2<br/>wfrp4e-core: 4.0.2<br/>wfrp4e-dotr: 4.0.2<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-starter-set: 4.0.0<br/>Active Modules: babele, dice-calculator, dice-so-nice, hide-player-ui, lib-wrapper, MaterialDeck, materialdeck-wfrp4e, ru-ru, socketlib, token-action-hud-core, token-action-hud-wfrp4e, vtta-tokenizer, walls-have-ears, wfrp4e-character-details

**Comment by Forien** [comment]
First, I noticed you are on `wfrp4e` 7.1, but your official modules are on `4.0`. This is not going to work, I advise you to update your modules to `5.0` and go through Effect Refactor Update as described in the [Documentation](https://moo-man.github.io/WFRP4e-FoundryVTT/pages/effects/effect-refactor.html), or this [Discord Thread](https://discord.com/channels/170995199584108546/1242099485115420762)

**As for your issue,** if a 3rd party module doesn't work, it's not a responsibility of the system to fix it. Your first choice should be to contact dev of said module and ask them to update it, unless there is a specific reason why module can't achieve what it wants and requires changes in the system. 

In that case it would be helpful for that module's dev to either make a Pull Request with required changes, or open an Issue describing what doesn't work and what changes would be required

**Comment by moo-man** [comment]
Closing until more detail provided
