### ISSUE TITLE
[WFRP4e System] No data found after purchasing module.

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2063]
I bought the Crucible 7 Core Module for WHFR 4e and there is no species tables found, no compemiums, nothing.<br/>**From**: lolsheeps<br/>foundry: 11.315<br/>wfrp4e: 7.1.6<br/>Active Modules:

**Comment by Forien** [comment]
Install and then enable the Core module in your world.

As you can see, there are no `active modules` in your world.

**Comment by moo-man** [comment]
Please see the FAQ/documentation: https://moo-man.github.io/WFRP4e-FoundryVTT/pages/faq.html

This was also linked in the bug reporter.
