### ISSUE TITLE
[WFRP4e System] Add Spell Description to chat window

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#207]
When a player cast a spell it would be cool if the description on what the spell do is also posted on the chat window. Right now the only description I get is that the spell succeed, but not the description on what the spell actually do. Dont know if this is a bug or something that can be incorporated.
https://cdn.discordapp.com/attachments/777136739495182406/777820056007999529/unknown.png
What Would be good if displayed on chat window
https://cdn.discordapp.com/attachments/777136739495182406/777820259141812234/unknown.png<br/>**From**: danil0<br/>wfrp4e: 3.1.0<br/>wfrp4e-core: 1.1<br/>wfrp4e-eis: 1.0<br/>wfrp4e-rnhd: 1.02<br/>wfrp4e-starter-set: 1.02

**Comment by moo-man** [comment]
I disagree here, they can just post the chat card if they want to see it, if they don't, I don't want to unnecessarily flood the chat

**Comment by danil0man** [comment]
Ah, Stupid me. Totally forgot there is a button to post to chat. You are right
