### ISSUE TITLE
[WFRP4e System] Apply Blessing of protection throws exception

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2071]
rp4e.js:6513 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'applyEffect')
[Detected 1 package: system:wfrp4e]
    at ChatWFRP._onApplyTargetEffect (wfrp4e.js:6513:22)
_onApplyTargetEffect @ wfrp4e.js:6513
await in _onApplyTargetEffect (async)
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2<br/>**From**: steven.evans<br/>foundry: 11.315<br/>wfrp4e: 7.2.0<br/>wfrp4e-core: 5.0.5<br/>wfrp4e-starter-set: 5.0.3<br/>Active Modules: filepicker-plus, lib-wrapper, module-credits, socketlib

**Comment by Forien** [comment]
As player, targeting myself and one other token:

![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/925d6d05-ba1d-417f-b344-25c7f95f1154)
```
commons.js:3592 Uncaught (in promise) Error: The Set#map operation illegally modified the size of the set
    at Set.map (commons.js:3592:13)
    at ChatWFRP._onApplyTargetEffect (wfrp4e.js:6491:140)
```
