### ISSUE TITLE
[WFRP4e System] Distracting Effect apllied to often

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2102]
Hi,

we are fighting zombies with Distracting Treat. Distract should only affect living creatures (maybe if the do not have the dead effect) and should only only be applied once.
Only minor stuff maybe even not solvable.

Best regards,
Tim<br/>**From**: tantalozolot<br/>foundry: 11.315<br/>wfrp4e: 7.2.1<br/>wfrp4e-archives1: 5.0.2<br/>wfrp4e-archives2: 5.0.1<br/>wfrp4e-core: 5.0.6<br/>wfrp4e-dotr: 5.0.4<br/>wfrp4e-eis: 5.0.2<br/>wfrp4e-horned-rat: 5.0.3<br/>wfrp4e-middenheim: 5.0.2<br/>wfrp4e-pbtt: 5.0.3<br/>wfrp4e-rnhd: 5.0.2<br/>wfrp4e-starter-set: 5.0.3<br/>wfrp4e-ua1: 5.0.1<br/>wfrp4e-up-in-arms: 5.0.2<br/>wfrp4e-wom: 5.0.3<br/>wfrp4e-zoo: 5.0.1<br/>Active Modules: colorsettings, dice-calculator, dice-so-nice, effectmacro, foundryvtt-show-notes, fxmaster, image-hover, item-piles, ivan-duch-music-packs, lessfog, lib-wrapper, monks-bloodsplats, monks-combat-details, monks-combat-marker, monks-little-details, sketch-tiles, smarttarget, socketlib, theatre, times-up, token-action-hud-core, token-action-hud-wfrp4e, token-mold, wfrp4-wfrp4e-npc-generator, wfrp4e-dotr-maps, wfrp4e-eis-maps, wfrp4e-gm-toolkit, wfrp4e-pbth-maps, wfrp4e-random-treasure, wfrp4e-ubersreik-maps, wfrp4e-unofficial-grimoire

**Comment by nyoung** [comment]
I encountered the same issue where a small horde of zombies caused large numbers of overlapping distracting effects and never ending "unidentified id [xxx] does not exist in the EmbeddedCollectionDelta collection. Some zombies would retain many distracted effects even after moving away from the horde.
