### ISSUE TITLE
[Enemy In Shadows] Miscasts triggering on failed rolls despite Dhar not being used to cast

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2123]
It seems that any character that has Channelling (Dhar) as a trained Skill triggers the Dhar casting miscast rules, even when they are casting spells using a different Lore and Channelling Skill.

The example from my game is a Light Wizard (Master Heirophant) who also has some Skills and Talents relating to Necromancy (which are secret). Channelling (Hysh) is higher than Channelling (Dhar) on their sheet, and they almost exclusively cast Light spells, but each failure prompts a miscast roll.<br/>**From**: mighty_chebo<br/>foundry: 11.315<br/>wfrp4e: 7.2.2<br/>wfrp4e-altdorf: 5.0.2<br/>wfrp4e-archives1: 5.0.2<br/>wfrp4e-archives2: 5.0.1<br/>wfrp4e-core: 5.0.6<br/>wfrp4e-dotr: 5.0.4<br/>wfrp4e-eis: 5.0.2<br/>wfrp4e-empire-ruins: 5.0.3<br/>wfrp4e-horned-rat: 5.0.3<br/>wfrp4e-middenheim: 5.0.2<br/>wfrp4e-owb2: 5.0.3<br/>wfrp4e-pbtt: 5.0.4<br/>wfrp4e-up-in-arms: 5.0.2<br/>wfrp4e-wom: 5.0.3<br/>wfrp4e-zoo: 5.0.1<br/>Active Modules: combat-tracker-dock, combatbooster, dd-import, drag-ruler, foundryvtt-simple-calendar, healthEstimate, initiative-double-click, item-piles, lessfog, lib-wrapper, mcc, monks-active-tiles, nations-of-mankind-wfrp4e, permission_viewer, quick-insert, routinglib, socketlib, token-action-hud, token-attacher, token-auras, wfrp4e-gm-toolkit, wfrp4e-pbth-maps, forge-vtt

**Comment by moo-man** [comment]
Non reproducible, closing as username isn't found on Discord.

**Comment by Forien** [comment]
@mighty-chebo 

Could it have been because of `Malignant Influences` checkbox? 
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/848f94bc-48a5-4107-af7c-49b5fe2c08fa)


Or perhaps (I think this is what was happening) it was a failed Cast Test **_after_** Channelling?
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/11304207/06118910-afc2-4f6e-9090-8fc6395fabfd)

**Comment by mighty-chebo** [comment]
> @mighty-chebo
> 
> Could it have been because of `Malignant Influences` checkbox? ![image](https://private-user-images.githubusercontent.com/11304207/343803745-848f94bc-48a5-4107-af7c-49b5fe2c08fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTY2MjYsIm5iZiI6MTcxOTQ5NjMyNiwicGF0aCI6Ii8xMTMwNDIwNy8zNDM4MDM3NDUtODQ4Zjk0YmMtNDhhNS00MTA3LWFmN2MtNDliNWZlMmMwOGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzNTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZTNkYTQxZTYwZGE5NzQxZmVhMGY2ZWM0MDhmZTYxNmI3NTIwNTQyMTIzNDI5NzE1YzkyZWYwNTdmNWQ5NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.haxVYEKIp2jeuSbyhtWwCVp3UmdHTZL6DBpUULnzlqU)
> 
> Or perhaps (I think this is what was happening) it was a failed Cast Test **_after_** Channelling? ![image](https://private-user-images.githubusercontent.com/11304207/343803574-06118910-afc2-4f6e-9090-8fc6395fabfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTY2MjYsIm5iZiI6MTcxOTQ5NjMyNiwicGF0aCI6Ii8xMTMwNDIwNy8zNDM4MDM1NzQtMDYxMTg5MTAtYWZjMi00ZjZlLTkwOTAtOGZjNjM5NWZhYmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzNTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOThlMWYxMzEzYTgzZDQ4NjU2ZTRlZjc3ZmRkM2E5NmRhODFlYzI5ZGMzMTMwNWEyODhhZWU5OGNiNzcyMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z6D0mgHePjqPK7KjIJKcUCd576zfRsYsXRPYTpTQ9bY)

Sorry! My bad. It is definitely the bottom one - failed cast after channelling. Our two parties have been overlooking that rule completely.

Thank you very much for resolving!

**Comment by moo-man** [comment]
> This is me. Sorry, I just realised my Discord settings don't allow contact from people I'm not in a server with

To be clear, in this case I send a friend request, but discord said it could not find your username.

**Comment by mighty-chebo** [comment]
> To be clear, in this case I send a friend request, but discord said it could not find your username.

Strange. Sorry - don't know why. "mighty_chebo" is definitely my username. I updated the settings to allow Friend Requests from everyone, so hopefully it will work next time, if needed.

Thank you, and sorry to take up your time with a mistake.
