### ISSUE TITLE
[Starter Set] WHRP Journal Entries Have Spoilers

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#213]
Hi,
Thanks for bringing WHRP to Foundry, really enjoy it so far! This was the main reason I've bought the license. Before our group were using Roll20 and I've basically constructed the same Warhammer Starter Set in Roll20 with Ubersreik map and all pins and Journal entries.

One thing that differs from your approach, is that I've hidden all plot points in Journal Entries from players. For example if you look at Watch Barracks, it would be great to give access to this Journal entry to the players, but it has Spoilers inside. What I propose, is to basically hide all spoilers under <Secret> tag. In that case it's very easy to grant Journal Entries to the group.

Would be glad to help with Pull Requests, but as I understood you have Starter Set a private repository on GitHub.

Best regards,
Alex<br/>**From**: alex.buzdin@gmail.com<br/>wfrp4e: 3.2.0<br/>wfrp4e-core: 1.11<br/>wfrp4e-rnhd: 1.03<br/>wfrp4e-starter-set: 1.03

**Comment by mogrogh** [comment]
Like with the journal for "Cordelia's Apothecary", where the adventure seeds are hidden. Not checked all but in Cordelia's Apothecary it's hidden and most/all others it's not.

**Comment by moo-man** [comment]
My philosophy here is when you decide to give your players observer permissions is when you should decide what you want to show them. 

I'm leaning towards not deciding for the GM what is a spoiler and what isn't. Obviously some are clearly spoilers, but the GM should be cognizant of what they are giving their players access to.

**Comment by mogrogh** [comment]
![Skärmklipp 2020-12-20 08 27 16](https://user-images.githubusercontent.com/69079040/102707922-6c59f480-429f-11eb-92e7-bfbcb443782d.png)

As you can see some of the journals you have used "Secret" text Some not. I thought that was what the bug-reporter meant. I might be wrong.

**Comment by moo-man** [comment]
Going to go ahead and close this, regarding your screenshots @mogrogh, those specific journals came from the fact that I created the Starter Set module by repurposing my actual game world. Some artifacts of it remain. 

Ideally I would like to add this, but I feel like the effort and time to curate each journal entry and decide what should be Secret and what shouldn't is too high. 

I still maintain my belief that the modules are best used as a booster to get GMs past the monotony of manual entry, and they should take the time to make decisions like these for themselves as they're preparing their games.
