### ISSUE TITLE
[WFRP4e System] Dice roll doesn't work when editing weapons.

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2143]
I am unable to fill in the "dice roll" field when editing weapons. After entering a variable, e.g., 1d6, the chat does not save the change, and the field remains empty upon reopening the edit.
Before update to v12, this option worked flawlessly. 
I tested the function on another world without unofficial modules, and it still does not work. I know that this is not a core feature present in wfrp4ed, but I need help as it added depth and variety to the weapons and ammunition in my campaign.<br/>**From**: tow.bieda<br/>foundry: 12.328<br/>wfrp4e: 7.2.4<br/>Active Modules:

**Comment by MechaP0744** [comment]
![Zrzut ekranu 2024-07-10 145936](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/162724425/97f5499b-a4e8-409a-8627-d4cbfc6c3149)
