### ISSUE TITLE
[WFRP4e System] Shields Ignore Armour Piercing

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2156]
Armour Piericing is currently not bypassing shields.<br/>**From**: Bricksmarlen<br/>foundry: 11.315<br/>wfrp4e: 7.2.4<br/>wfrp4e-core: 5.0.7<br/>wfrp4e-dotr: 5.0.5<br/>wfrp4e-eis: 5.0.3<br/>wfrp4e-middenheim: 5.0.2<br/>wfrp4e-rnhd: 5.0.2<br/>wfrp4e-up-in-arms: 5.0.3<br/>Active Modules: background-scaler, dice-so-nice, forien-ammo-swapper, forien-armoury, foundryvtt-simple-calendar, item-piles, lib-wrapper, socketlib, tabletop-rpg-music, tabletop-rpg-music-cloud-streaming, times-up, token-action-hud-core, token-action-hud-wfrp4e, wfrp4e-dotr-maps, wfrp4e-eis-maps, wfrp4e-gm-toolkit, forge-vtt, forge-vtt-optional

**Comment by moo-man** [comment]
What specifically do you mean by "Armour Piercing"?

**Comment by Forien** [comment]
I believe this is about `Penetrating` Weapon Property

**Comment by moo-man** [comment]
Well as usual about this topic, there is no distinction between non-metal and metal shields in the rulebook.

**Comment by Bricksmarlen** [comment]
Thank you. Looking forward to the changes. 

    On Monday, September 30, 2024 at 12:58:24 a.m. PDT, Russell ***@***.***> wrote:  
 
 


Closed #2156 as completed.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |
