### ISSUE TITLE
Pregens from Starter Set have some errors

### ISSUE THREAD

**Issue by GregorHak** [moo-man/WFRP4e-FoundryVTT#2162]
**Describe the bug**
Molrella Brandysnap (pregen from Starter Set module) has 760 current xp due Test, I think that this is not intentional.
Also should have Secret Signs (Thief) at 0 adv
![obraz](https://github.com/user-attachments/assets/830dc4b3-2921-4bdd-85ce-1bfa5c622a48)

**Comment by Marthambles** [comment]
I'm not sure if you want another Issue opening, or simply add that Ferdinand Gruber from the starter set has a similar error.  His Current Experience is 950.

**Comment by GregorHak** [comment]
Yes, Ferdinand Gruber also has some errors.
He should not have Initial Int: 45, but instead: 40
He should not have Initial WP: 38, but instead: 33
He should not have Dodge skill Adv: 5, but instead: 0
His weapon "Scythe" should not have Enc: 1, but instead: 2
