### ISSUE TITLE
[Core Rulebook] QoL - /char rolling money

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2173]
When using /char to create a new character, when it gets to the Trappings step, the system should determine the starting money like with all the other trappings at this point. Either automatically or by rolling once a button is pushed.<br/>**From**: ninaran<br/>foundry: 11.315<br/>wfrp4e: 7.2.4<br/>wfrp4e-altdorf: 5.0.3<br/>wfrp4e-archives1: 5.0.2<br/>wfrp4e-archives2: 5.0.1<br/>wfrp4e-core: 5.0.7<br/>wfrp4e-dotr: 5.0.5<br/>wfrp4e-eis: 5.0.3<br/>wfrp4e-empire-ruins: 5.0.4<br/>wfrp4e-horned-rat: 5.0.4<br/>wfrp4e-middenheim: 5.0.2<br/>wfrp4e-owb1: 5.0.3<br/>wfrp4e-owb2: 5.0.4<br/>wfrp4e-pbtt: 5.0.5<br/>wfrp4e-rnhd: 5.0.2<br/>wfrp4e-starter-set: 5.0.3<br/>wfrp4e-up-in-arms: 5.0.3<br/>wfrp4e-wom: 5.0.4<br/>wfrp4e-zoo: 5.0.2<br/>Active Modules: ATL, _chatcommands, advanced-macros, autoanimations, chat-commander-wfrp4e, color-picker, dfreds-effects-panel, dice-calculator, dice-so-nice, drag-ruler, forien-ammo-swapper, forien-armoury, foundryvtt-simple-calendar, item-piles, jb2a_patreon, lib-wrapper, monks-active-tiles, monks-combat-details, monks-combat-marker, monks-hotbar-expansion, permission_viewer, popout, quick-insert, rolltable-requester, sequencer, settings-extender, socketlib, subfolder-indent, times-up, token-action-hud-core, token-action-hud-wfrp4e, token-z, unsnap-ruler, wfrp4e-endeavours, wfrp4e-gm-toolkit, wfrp4e-night-vision

**Comment by Jagusti** [comment]
Push a button please - need to give those players something to do! - there's something satisfying about rolling your own destitution or wealth. Of course, bonus points for a fully automated option in settings that takes button pushing and decision making out of the chargen wizard.
