### ISSUE TITLE
[Empire in Ruins] Can't find a straightforward way to implement permanent Wound loss

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2181]
This might have broader uses (such as when losing Wounds to Impale - some Wound loss should be permanent until the impaling object is removed), but I'm preparing to run the later parts of Empire in Ruins and have come across this issue: In the Chapter 11 Journal, in section 10 (Location 9 - The Prison), the text states that a character that picks up Ghal Maraz should suffer permanent Wound loss equal to their Corruption value.

I can't see a straightforward way of applying this permanent Wound loss. I don't seem to be able to edit the maximum Wound values on sheets. I've cobbled together a custom Trait to apply to characters, which seems to do the job (it reduces args.wounds by the Rating value of the Trait), but this required tinkering and the familiarity with Foundry that comes with using it for quite a long time. I think there should be a straightforward solution that anyone could use on receipt of the module, or perhaps a clear option in the system itself.<br/>**From**: mighty_chebo<br/>foundry: 11.315<br/>wfrp4e: 7.2.4<br/>wfrp4e-altdorf: 5.0.3<br/>wfrp4e-archives1: 5.0.2<br/>wfrp4e-archives2: 5.0.1<br/>wfrp4e-core: 5.0.7<br/>wfrp4e-dotr: 5.0.5<br/>wfrp4e-eis: 5.0.3<br/>wfrp4e-empire-ruins: 5.0.4<br/>wfrp4e-horned-rat: 5.0.4<br/>wfrp4e-middenheim: 5.0.2<br/>wfrp4e-owb2: 5.0.4<br/>wfrp4e-pbtt: 5.0.5<br/>wfrp4e-up-in-arms: 5.0.3<br/>wfrp4e-wom: 5.0.4<br/>wfrp4e-zoo: 5.0.2<br/>Active Modules: combat-tracker-dock, combatbooster, dd-import, drag-ruler, foundryvtt-simple-calendar, healthEstimate, initiative-double-click, item-piles, lessfog, lib-wrapper, mcc, monks-active-tiles, nations-of-mankind-wfrp4e, permission_viewer, quick-insert, routinglib, socketlib, token-action-hud, token-attacher, token-auras, wfrp4e-gm-toolkit, wfrp4e-pbth-maps, forge-vtt

**Comment by mighty-chebo** [comment]
I just remembered another module where this is a requirement. The Create Familiar Ritual in Winds of Magic requires that the caster permanently sacrifices Fate, Resilience, or 1 Wound.

I don't know how to change the labels on an issue, sorry.

**Comment by moo-man** [comment]
The straightforward non-scripting solution is to disable automatic wound calculation and change the value accordingly.

The scripting solution is a simple one, the Swarm trait has a straightforward effect that can be repurposed for this.
