### ISSUE TITLE
[WFRP4e System] Cannot access dwarven subspecies

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2185]
Hi, i noticed recently that I cannot access the dwarven sub species other than the Norse one. I have all wfrp4e modules.I have tried updating the sea of claws, AoTE1, and core rulebook modules but it hasn't helped. Any fix?
Thanks.<br/>**From**: #6165<br/>foundry: 11.315<br/>wfrp4e: 7.2.4<br/>wfrp4e-archives1: 5.0.2<br/>wfrp4e-archives2: 5.0.1<br/>wfrp4e-core: 5.0.7<br/>wfrp4e-dotr: 5.0.5<br/>wfrp4e-eis: 5.0.3<br/>wfrp4e-horned-rat: 5.0.4<br/>wfrp4e-owb1: 5.0.3<br/>wfrp4e-owb2: 5.0.4<br/>wfrp4e-pbtt: 5.0.5<br/>wfrp4e-rnhd: 5.0.2<br/>wfrp4e-soc: 5.0.1<br/>wfrp4e-starter-set: 5.0.3<br/>wfrp4e-ua1: 5.0.2<br/>wfrp4e-ua2: 5.0.2<br/>wfrp4e-up-in-arms: 5.0.3<br/>wfrp4e-wom: 5.0.4<br/>wfrp4e-zoo: 5.0.2<br/>Active Modules: arms-reach, combat-enhancements, combat-utility-belt, dice-calculator, dice-so-nice, drag-ruler, foundryvtt-show-notes, foundryvtt-simple-calendar, fvtt-wfrp4e-add-xp, image-hover, lib-wrapper, multilevel-tokens, popout, socketlib, token-action-hud-core, token-action-hud-wfrp4e, torch, wfrp4e-gm-toolkit, wfrp4e-night-vision, wfrp4e-random-treasure

**Comment by GregorHak** [comment]
what about Cragforge Clan and Grumsson Clan from Salzenmund: City of Salt and Silver page 142. But I look at this user modules enabled and do not see Salzenmund module, so I assume that despite everything he do not have all wfrp4e modules.
