### ISSUE TITLE
[WFRP4e System] Spells use WP not Channelling skill when channelling.

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2232]
I have created a Goblin Shaman with Channelling 40. Whenever I use the Channel option under Magic (i.e. hit spell and choose Channel instead of Cast) it bases the Channelling test on the Goblin's WP (35) not its Channelling (40).

I have tried adding "Little Waaagh!" to both the spell Lore and to its skills (named "Arcane Magic (Little Waaagh!)" but it has not helped. 

Below says I have non-WFRP4e moducles activiated but I don't.<br/>**From**: PrayForWar<br/>foundry: 12.331<br/>wfrp4e: 8.0.4<br/>wfrp4e-core: 6.0.0<br/>wfrp4e-dotr: 6.0.0<br/>wfrp4e-eis: 6.0.0<br/>wfrp4e-horned-rat: 6.0.0<br/>wfrp4e-owb2: 6.0.0<br/>wfrp4e-rnhd: 6.0.0<br/>wfrp4e-starter-set: 6.0.0<br/>wfrp4e-up-in-arms: 6.0.0<br/>wfrp4e-wom: 6.0.0<br/>Active Modules: warhammer-lib

**Comment by PrayForWar** [comment]
So it looks like it didn't like the default Chanelling skill, but when I changed both the Channelling Skill and the default required by the spell to Channelling (Little Waaagh!) it worked.

**Comment by moo-man** [comment]
Channelling, unspecified, is used specifically for WItchcraft, so this is intended, unless I'm misunderstanding.
