### ISSUE TITLE
Manifest warnings

### ISSUE THREAD

**Issue by grz0** [moo-man/WFRP4e-FoundryVTT#2235]
**Describe the bug**
Foundry logs multiple warnings in the Setup page:

`The system "wfrp4e" is using "gridDistance" which is deprecated in favor of "grid.distance".`

`The system "wfrp4e" is using "gridUnits" which is deprecated in favor of "grid.units".`

`System "wfrp4e" defines ChatMessage document sub-type "base" which is a reserved core type.`

`The "Warhammer Fantasy Roleplay 4th Edition" system's manifest contained the following unknown keys: "manifestPlusVersion", "templateVersion"`

**To Reproduce**
Check warnings in Setup

**Screenshots**
![image](https://github.com/user-attachments/assets/07ffaff1-006a-45fe-b6d4-548894c1bef7)

**Version Numbers**

Foundry: v12.331
wfrp4e: v8.0.4

**Comment by moo-man** [comment]
closed via #2088
