### ISSUE TITLE
Item ddint show in trappings after pay

### ISSUE THREAD

**Issue by DrunXX** [moo-man/WFRP4e-FoundryVTT#2255]
**Describe the bug**
When GM put item on chat to buy. I click buy, money goes but item didn show in trappings
**To Reproduce**
If applicable, provide steps to reproduce this issue

**Screenshots**
![image](https://github.com/user-attachments/assets/0c07d2d3-d3ee-471c-b138-e317f86de983)

**Version Numbers**
PLEASE PROVIDE YOUR FOUNDRY, SYSTEM, and MODULE VERSIONS (where applicable) 

Foundry:
wfrp4e:8,1,2
wfrp4e-core:
wfrp4e-starter-set:
wfrp4e-rnhd:
wfrp4e-eis:
wfrp4e-ua1:
wfrp4e-dotr:
wfrp4e-archives1:
wfrp4e-middenheim:
wfrp4e-archives1:
wfrp4e-pbtt:
wfrp4e-altdorf:
wfrp4e-ua2:
wfrp4e-owb1:
wfrp4e-horned-rat:
wfrp4e-empire-ruins:

**Comment by moo-man** [comment]
The intention is to drag the item from chat onto your sheet

**Comment by moo-man** [comment]
Nevermind
