### ISSUE TITLE
[WFRP4e System] Unable to Toggle Visor

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2259]
You are unable to toggle the visor from the button given by the quality. It shoots out this error.

warhammer.js:6777  
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'manualScripts')
[Detected 1 package: warhammer-lib(1.1.0)]
    at ActorSheetWFRP4eCharacterV2._onTriggerScript (warhammer.js:6777:33)

Additionally, this bug is submitted as a System bug because upon filing it under the Domain for Archives 3 it errors me:
https://aa5qja71ih.execute-api.us-east-2.amazonaws.com/Prod/grievance net::ERR_FAILED 500 (Internal Server Error)<br/>**From**: rabidcatcake<br/>foundry: 12.331<br/>wfrp4e: 8.1.3<br/>wfrp4e-altdorf: 6.0.1<br/>wfrp4e-archives1: 6.0.1<br/>wfrp4e-archives2: 6.0.1<br/>wfrp4e-archives3: 6.0.0<br/>wfrp4e-core: 6.0.1<br/>wfrp4e-dotr: 6.0.1<br/>wfrp4e-eis: 6.0.1<br/>wfrp4e-empire-ruins: 6.0.1<br/>wfrp4e-horned-rat: 6.0.1<br/>wfrp4e-middenheim: 6.0.1<br/>wfrp4e-owb1: 6.0.1<br/>wfrp4e-owb2: 6.0.1<br/>wfrp4e-pbtt: 6.0.0<br/>wfrp4e-rnhd: 6.0.1<br/>wfrp4e-salzenmund: 6.0.1<br/>wfrp4e-soc: 6.0.1<br/>wfrp4e-starter-set: 6.0.1<br/>wfrp4e-ua1: 6.0.1<br/>wfrp4e-up-in-arms: 6.0.1<br/>wfrp4e-wom: 6.0.1<br/>wfrp4e-zoo: 6.0.0<br/>Active Modules: lib-wrapper, module-credits, quick-insert, socketlib, warhammer-lib

**Comment by Forien** [comment]
The issue exists only on V1 sheet. It's possible to use the button on V2 sheet.

V1 sheet has this html for button:
```html
<a class="trigger-script" data-index="0" 
  data-uuid="Actor.Lzyf9HbmDOMlY2km.Item.uLqSVX8sU1hq0mFv.ActiveEffect."
>
  Toggle Visor
</a>
```
and V2 sheet has this html for button:
```html
<button data-action="triggerScript" data-path="system.properties.flaws.visor.effect" 
  data-type="manualScript" data-uuid="Actor.Lzyf9HbmDOMlY2km.Item.uLqSVX8sU1hq0mFv.ActiveEffect." 
  data-index="0" type="button" draggable="true"
>
  Toggle Visor
</button>
```

so I guess the v1 sheet lacks the `data-path` and maybe the `data-type`
