### ISSUE TITLE
Where is the "Ogre Characters Journal"? 

### ISSUE THREAD

**Issue by Athinar** [moo-man/WFRP4e-FoundryVTT#2261]
**Describe the bug**

**To Reproduce**
If applicable, provide steps to reproduce this issue

**Screenshots**

**Version Numbers**
PLEASE PROVIDE YOUR FOUNDRY, SYSTEM, and MODULE VERSIONS (where applicable) 

Where is the "Ogre Characters Journal"? Type in Ogre in the Foundry Warhammer journal nothing comes up
Please create a video on this request, Thanks, new to Foundry
Foundry:12.331
wfrp4e:8.1.3
wfrp4e-core:6.0.1
wfrp4e-starter-set:6.0.1
wfrp4e-desk:1.7.2
wfrp4e-cdg:1.2.0
wfrp4e-rwhlib:1.1.0
wfrp4e-rnhd:6.0.1
wfrp4e-owb1:6.0.1
wfrp4e-owb2:6.0.1
wfrp4e-wom:6.0.1
wfrp4e-ogre-kingdom: 0.2.1
die-so-nice:5.1.1
libwallpaper:1.12.2.0

I have the Gnome in the species list

**Comment by moo-man** [comment]
Please don't open Issues just to ask questions, there are plenty of other avenues for that such as Discord. This is for bug reports. 

Regardless, the journal entry detailing Ogres is in [Archives 2](https://foundryvtt.com/packages/wfrp4e-archives2)

**Comment by Athinar** [comment]
Module issues:
module "ogre-kingdom-wfrp4e" contains "system" which deprecated in favor of "relationships.system"
The module "ogre-kingdom-wfrp4e" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object
The module "ogre-kingdom-wfrp4e" module's manifest contained the following unknown keys: "author", "systems"

**Comment by Athinar** [comment]
Moo man, I looked in Discord and found nothing about "Ogre Characters Journal location

**Comment by moo-man** [comment]
You can use Discord to ask a question in either the Foundry Discord (in the `#warhammer` channel) or the Rat Catcher's Guild Discord (in the `#foundry-vtt` channel). 

Regarding the "module issues." That module is both out of date and not my responsibility, it is community made.
