### ISSUE TITLE
WFRP4E 8.1.3 update, now unable to use any actors

### ISSUE THREAD

**Issue by mdomino1066** [moo-man/WFRP4e-FoundryVTT#2263]
**Describe the bug**
Hi. I updated to WFRP4E 8.1.3. It seems all my actors are broken now. I don't have any character sheets for PCs or NPCs- just a popout box with a list of the talents, items, careers, etc.
Any advice would be greatly appreciated. I hate to lose this campaign, but could reproduce it if I was at least able to extract the 4 PCs and start a new game.

**Screenshots**

**Version Numbers**
Foundry version 12 Build 327
Hosted on The Forge at World Builder subscription level

Running The Enemy Within
WFRP4E core
Enemy in Shadows
Up In Arms
Archives of the Empire I
Altdorf
Dice so Nice
Portraitworks basic
Token Action HUD WFRP4e

Best.
Mike Domino

**Comment by moo-man** [comment]
Make sure to update the Warhammer library module, a dependency of the wfrp system

**Comment by mdomino1066** [comment]
Thank you. That did it. I appreciate the help. And absolutely awesome implementation of WFRP. I was freaking out a bit there as the campaign is quickly becoming a bucketlist game due to how much fun the players are having and how seamless the Foundry module is.
Best.
M

**Comment by moo-man** [comment]
Great! Generally if updates cause sheets to not render correctly, your data is perfectly fine, and there's some bug preventing the sheet from showing. 

Also, remember that if you need any sort of immediate troubleshooting, your best place is the Discord. See [Troubleshooting](https://moo-man.github.io/WFRP4e-FoundryVTT/pages/troubleshooting.html) (WIP)

**Comment by mdomino1066** [comment]
Got it. Thanks.
M
