### ISSUE TITLE
Cannot install Archives of the Empire Vol. III from the Forge Marketplace

### ISSUE THREAD

**Issue by mighty-chebo** [moo-man/WFRP4e-FoundryVTT#2265]
**Describe the bug**
I bought the key for AotE III from Cubicle 7, activated through my Foundry account, went to the Forge marketplace and clicked to install the module, like I have with every other module. It won't install, but keeps giving me this error:

> Failed to install module: Unable to load valid module manifest data from "https://foundry-c7-manifests.s3.us-east-2.amazonaws.com/wfrp4e-archives3/module.json" Module validation errors: documentTypes: is not a valid sub-types configuration: ChatMessage Documents do not support sub-types

**To Reproduce**
I have tried refreshing the Forge marketplace and attempted reinstallation, but the same error message keeps happening.

**Screenshots**
![image](https://github.com/user-attachments/assets/215f7bbe-3c8d-41df-94b1-492ea2107f89)

**Version Numbers**
Foundry is the default Forge version and all other modules are up-to-date.

**Comment by mighty-chebo** [comment]
One of my players just made me realise that this is because AotE III is only compatible with Foundry versions 12+, and Forge hasn't moved to v12 yet. While I realise now that the Forge marketplace entry states minimum v12, the Cubicle 7 store doesn't give any Foundry version info, so I don't think it's unreasonable for a customer to assume that this module will work with all the others they have bought (I use most of the official modules from the C7 store, through the Forge).

I accept that there might not be much that can be done about this, and that I might have to wait for the Forge to hit V12, but I think a warning should be added somewhere in the purchase process - ideally on the C7 store, seeing as I went straight there without checking the Forge Marketplace entry. It feels a bit like wasted money and it's kind of annoying, though I know I could have done more thorough checks for compatibility.

**Comment by TheFirst05** [comment]
You can update your foundry to v12 on the forge. We use Forge and we're using Foundry v12 with wfrp
