### ISSUE TITLE
[Enemy In Shadows] Uneven Horns Applying AP to All Locations

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2266]
I applied Uneven Horns mutation to character. They received +1 AP to all locations instead of just head<br/>**From**: Bricksmarlen<br/>foundry: 12.331<br/>wfrp4e: 8.1.3<br/>wfrp4e-core: 6.0.1<br/>wfrp4e-dotr: 6.0.1<br/>wfrp4e-eis: 6.0.1<br/>wfrp4e-middenheim: 6.0.1<br/>wfrp4e-rnhd: 6.0.1<br/>wfrp4e-up-in-arms: 6.0.1<br/>Active Modules: background-scaler, dice-so-nice, drag-ruler, forien-ammo-swapper, forien-armoury, foundryvtt-simple-calendar, item-piles, lib-wrapper, raise-my-hand, socketlib, tabletop-rpg-music, tabletop-rpg-music-cloud-streaming, times-up, token-action-hud-core, token-action-hud-wfrp4e, warhammer-lib, wfrp4e-character-details, wfrp4e-dotr-maps, wfrp4e-eis-maps, wfrp4e-gm-toolkit, forge-vtt, forge-vtt-optional

**Comment by GregorHak** [comment]
Yes, for some reason Uneven Horns (Enemy In Shadow) has Spiked Skin script [Script.**mBcLf11upaHS8AQq**] instead [Script.**OqxeuZfZDfm9ax6h**]. 

Also Uneven Horns (CORE) per rules has the same effects but do not share the same scripts
