### ISSUE TITLE
[WFRP4e System] Fate and Resolve have switched places in character sheet v2.

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2268]
Fate and Resolve have switched places in character sheet v2.<br/>**From**: mogrogh<br/>foundry: 12.331<br/>wfrp4e: 8.1.3<br/>wfrp4e-altdorf: 6.0.1<br/>wfrp4e-archives1: 6.0.1<br/>wfrp4e-archives2: 6.0.1<br/>wfrp4e-archives3: 6.0.0<br/>wfrp4e-core: 6.0.1<br/>wfrp4e-dotr: 6.0.1<br/>wfrp4e-eis: 6.0.1<br/>wfrp4e-empire-ruins: 6.0.1<br/>wfrp4e-horned-rat: 6.0.1<br/>wfrp4e-lustria: 6.0.1<br/>wfrp4e-middenheim: 6.0.1<br/>wfrp4e-owb1: 6.0.1<br/>wfrp4e-owb2: 6.0.1<br/>wfrp4e-pbtt: 6.0.0<br/>wfrp4e-rnhd: 6.0.1<br/>wfrp4e-salzenmund: 6.0.1<br/>wfrp4e-starter-set: 6.0.1<br/>wfrp4e-ua1: 6.0.1<br/>wfrp4e-ua2: 6.0.0<br/>wfrp4e-up-in-arms: 6.0.1<br/>wfrp4e-wom: 6.0.1<br/>wfrp4e-zoo: 6.0.0<br/>Active Modules: _chatcommands, chat-commander-wfrp4e, dice-calculator, dice-so-nice, forien-ammo-swapper, forien-armoury, item-piles, lib-wrapper, permission_viewer, socketlib, spotlight-omnisearch, times-up, token-action-hud-core, token-action-hud-wfrp4e, user-latency, warhammer-lib, wfrp4e-character-details, wfrp4e-endeavours, wfrp4e-gm-toolkit

**Comment by mogrogh** [comment]
![v2](https://github.com/user-attachments/assets/f4846860-8717-4be2-a01e-69ad25ed293f)
![v1](https://github.com/user-attachments/assets/2840bbef-ff6a-4cb4-8c9c-adc37444340d)

**Comment by mogrogh** [comment]
Double for #2249.
