### ISSUE TITLE
[WFRP4e System] Display Armour Items in V2 Combat Tab

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2277]
Currently equipped armour items do not display in the combat tab like in the old V1 sheet, where they appear under each body part's subgrouping. I think it is useful to see since you can qualities and flaws and would allow you to toggle visors on the Archives 3 helmets once they work correctly.<br/>**From**: rabidcatcake<br/>foundry: 12.331<br/>wfrp4e: 8.2.0<br/>wfrp4e-altdorf: 6.0.1<br/>wfrp4e-archives1: 6.0.1<br/>wfrp4e-archives2: 6.0.1<br/>wfrp4e-archives3: 6.0.0<br/>wfrp4e-core: 6.0.1<br/>wfrp4e-dotr: 6.0.1<br/>wfrp4e-eis: 6.0.2<br/>wfrp4e-empire-ruins: 6.0.1<br/>wfrp4e-horned-rat: 6.0.1<br/>wfrp4e-middenheim: 6.0.2<br/>wfrp4e-owb1: 6.0.1<br/>wfrp4e-owb2: 6.0.1<br/>wfrp4e-pbtt: 6.0.0<br/>wfrp4e-rnhd: 6.0.2<br/>wfrp4e-salzenmund: 6.0.1<br/>wfrp4e-soc: 6.0.2<br/>wfrp4e-starter-set: 6.0.1<br/>wfrp4e-ua1: 6.0.1<br/>wfrp4e-up-in-arms: 6.0.2<br/>wfrp4e-wom: 6.0.2<br/>wfrp4e-zoo: 6.0.0<br/>Active Modules: lib-wrapper, module-credits, quick-insert, socketlib, warhammer-lib

**Comment by Forien** [comment]
Core Armour is displayed on the Sheet V2, it's the modified Armour from Archives III that is not displayed.
I would consider it a bug
