### ISSUE TITLE
[Core Rulebook] Sigmar's Fiery Hammer

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2291]
The calculation for Sigmar's Fiery Hammer formular is missing the original weapon damage of the weapon. The script only includes SB + fellowship bonus and leaves out the original base damage of the weapon.

It currently reads like this:
args.item.system.damage.value = `SB + ${this.actor.system.characteristics.fel.bonus}`;

The rule reads like this:
"You chant benedictions of Sigmar’s might. If wielding a warhammer, it counts as Magical, deals +Fellowship Bonus Damage, and any target struck receives the Ablaze and Prone Conditions."<br/>**From**: Discord Tag: luxor0973<br/>foundry: 12.331<br/>wfrp4e: 8.2.2<br/>wfrp4e-archives1: 6.0.1<br/>wfrp4e-archives2: 6.0.1<br/>wfrp4e-archives3: 6.0.1<br/>wfrp4e-core: 6.0.1<br/>wfrp4e-dotr: 6.0.1<br/>wfrp4e-eis: 6.0.2<br/>wfrp4e-horned-rat: 6.0.1<br/>wfrp4e-pbtt: 6.0.0<br/>wfrp4e-rnhd: 6.0.2<br/>wfrp4e-starter-set: 6.0.1<br/>wfrp4e-ua1: 6.0.1<br/>wfrp4e-ua2: 6.0.0<br/>wfrp4e-up-in-arms: 6.0.2<br/>wfrp4e-wom: 6.0.2<br/>wfrp4e-zoo: 6.0.0<br/>Active Modules: backgroundless-pins, combat-tracker-dock, dice-so-nice, dragupload, foundryvtt-simple-calendar, gm-screen, lib-wrapper, pin-cushion, popout, quick-insert, simple-dice-roller, socketlib, token-frames, vtta-tokenizer, warhammer-lib, wfrp4e-character-details, wfrp4e-gm-toolkit, wfrp4e-ubersreik-maps

**Comment by Forien** [comment]
To be honest, reading it RAW, the hammer should not even get the `SB`, it should be just flat `FelB` Damage.

**Comment by Forien** [comment]
I posted it on [Discord](https://discord.com/channels/787396882875416606/787397718339223603/1302978072005447691) initially, but I think I will repost it here as well. Response from C7:
![image](https://github.com/user-attachments/assets/de7045c2-92d0-4ae7-9842-646051fc180e)
