### ISSUE TITLE
[Starter Set] Starter pack

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2293]
im not seeing the starter package in any of my journal entries or compediums. The package didnt basicly add anything<br/>**From**: MajRiker<br/>foundry: 12.331<br/>wfrp4e: 8.2.3<br/>wfrp4e-core: 6.0.1<br/>wfrp4e-ua1: 6.0.1<br/>Active Modules: dice-so-nice, warhammer-lib, wfrp4e-character-details, wfrp4e-gm-toolkit

**Comment by Forien** [comment]
You do not have the Starter Set enabled in your World.
