### ISSUE TITLE
[Core Rulebook] Can't access the Core rules on Foundry

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2296]
When I load the vtt I cannot see or access the core rules but when I load the Middenheim Mod I can access that.<br/>**From**: dagnabit911<br/>foundry: 12.331<br/>wfrp4e: 8.2.3<br/>Active Modules: warhammer-lib

**Comment by Forien** [comment]
No modules are enabled in the report. 

Make sure the modules are enabled in the world, if you still encounter an issue, provide screenshot of console errors (if there are any)
