### ISSUE TITLE
[WFRP4e System] Dialog window: Fortune

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2311]
Some groups prefer to hide some of their resources in order to avoid a metagame. If you can make an option so that after a second roll for luck, the window with the remaining luck is hidden by default, it would be very cool.<br/>**From**: mrak_x<br/>foundry: 12.331<br/>wfrp4e: 8.2.2<br/>wfrp4e-altdorf: 6.0.1<br/>wfrp4e-archives1: 6.0.1<br/>wfrp4e-archives2: 6.0.1<br/>wfrp4e-archives3: 6.0.0<br/>wfrp4e-core: 6.0.1<br/>wfrp4e-dotr: 6.0.1<br/>wfrp4e-eis: 6.0.2<br/>wfrp4e-empire-ruins: 6.0.1<br/>wfrp4e-horned-rat: 6.0.1<br/>wfrp4e-middenheim: 6.0.2<br/>wfrp4e-owb1: 6.0.1<br/>wfrp4e-owb2: 6.0.1<br/>wfrp4e-pbtt: 6.0.0<br/>wfrp4e-rnhd: 6.0.2<br/>wfrp4e-salzenmund: 6.0.1<br/>wfrp4e-soc: 6.0.2<br/>wfrp4e-starter-set: 6.0.1<br/>wfrp4e-ua1: 6.0.1<br/>wfrp4e-ua2: 6.0.0<br/>wfrp4e-up-in-arms: 6.0.2<br/>wfrp4e-wom: 6.0.2<br/>wfrp4e-zoo: 6.0.0<br/>Active Modules: about-face, babele, combat-tracker-dock, dice-calculator, easy-ruler-scale, forien-actors-summary, forien-armoury, forien-quest-log, gm-screen, lib-wrapper, ru-ru, ru-wfrp4e, sequencer, socketlib, token-attacher, warhammer-lib, wfrp4e-gm-toolkit

**Comment by Forien** [comment]
I think you mean Chat Message, not Dialog window?

I think it could ba changed to whisper all observers and owners of the actor, that way if some groups play with "open cards" they will see it, and if not, only owner and GMs will see it

**Comment by Mrak7439** [comment]
Yes, the chat window, the specifics of the translation =) Well, yes, I wish there was an option for this window to be automatically configured for Privat GM roll, for example. Now this can be achieved by rearranging the PGM Roll, making a second roll, and then rearranging it back, but you can forget about such things. It's great if there is some kind of automatic solution.
