### ISSUE TITLE
[WFRP4e System] «the wrong type of Corruption»

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2323]
When running a Corruption test, the error "the wrong type of Corruption" occurs
`@Corruption[minor], @Corruption[moderate], @Corruption[major]`<br/>**From**: mr.dengin<br/>foundry: 12.331<br/>wfrp4e: 8.2.3<br/>wfrp4e-altdorf: 6.0.1<br/>wfrp4e-archives1: 6.0.1<br/>wfrp4e-core: 6.0.1<br/>wfrp4e-dotr: 6.0.1<br/>wfrp4e-eis: 6.0.2<br/>wfrp4e-middenheim: 6.0.2<br/>wfrp4e-pbtt: 6.0.0<br/>wfrp4e-rnhd: 6.0.2<br/>wfrp4e-starter-set: 6.0.1<br/>wfrp4e-ua1: 6.0.1<br/>wfrp4e-up-in-arms: 6.0.2<br/>wfrp4e-wom: 6.0.2<br/>Active Modules: JB2A_DnD5e, ambientdoors, autoanimations, babele, chat-images, chat-portrait, colorsettings, combatbooster, dice-so-nice, drag-ruler, foundryvtt-simple-calendar, fxmaster, illandril-token-hud-scale, image-hover, lib-wrapper, monks-tokenbar, party-overview, permission_viewer, popout, ru-ru, ru-wfrp4e, scaleGrid, sequencer, simple-dice-roller, socketlib, splatter, token-action-hud, token-hud-art-button, token-variants, tokenmagic, tokenmagic-automatic-wounds, vance-sidebar-resizer, warhammer-lib, wfrp4e-gm-toolkit, forge-vtt

**Comment by moo-man** [comment]
Non reproducible, or I don't understand what this means

**Comment by Forien** [comment]
sounds like issue with translation to me

**Comment by moo-man** [comment]
Probably. Please consult the developer of the translation being used. Closing unless I need to address something.
