### ISSUE TITLE
Item Effects

### ISSUE THREAD

**Issue by Popoloolo** [moo-man/WFRP4e-FoundryVTT#2335]
Hi! Unfortunately I forgot the commands for writing effects for items. I remember there was a table or section with them =(
I need to downgrade of Dodge as effect of item/

**Comment by moo-man** [comment]
Not a bug report. 

If you have questions, the Discord channels are where you field them

**Comment by Popoloolo** [comment]
Yes, i know it but from my country the Discord is not working (

**Comment by moo-man** [comment]
You can find scripting documentation here: https://moo-man.github.io/WFRP4e-FoundryVTT/pages/effects/effects.html
