### ISSUE TITLE
[WFRP4e System] Saddlebags in browser

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#241]
I can't click on the saddlebags in the browser, and see the item-card. So I cant post to chat either so PC can buy them that way. Works for other items tested. It works to drag the saddlebags to a sheet though, and it looks OK there. <br/>**From**: mogrogh#4778<br/>wfrp4e: 3.2.0<br/>wfrp4e-core: 1.11<br/>wfrp4e-eis: 1.01<br/>wfrp4e-rnhd: 1.03<br/>wfrp4e-starter-set: 1.03

**Comment by mogrogh** [comment]
Re-initialize fixed this. Close please.
