### ISSUE TITLE
Trait damage concatenates instead of adds

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#275]
Carmello's Crew do massive damage, no error.

Below starts when I chose target (right-click and select target) and the rolls and choose unopposed:

**Comment by mogrogh** [comment]
![Skärmklipp 2020-12-20 00 30 58](https://user-images.githubusercontent.com/69079040/102701768-b79de400-425a-11eb-8529-949c495b7622.png)
