### ISSUE TITLE
[WFRP4e Core] Ranged/Size Modifiers Working Incorrectly 

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#289]
A few weird things going on here with range modifiers and size considerations:

1) Range modifiers are calculating incorrectly given target size. Range modifiers for size seem to be only adding +10 per size level larger the target is than the attacker.

Example: a clan rat with a bow shooting a basilisk should get a +40 modifier (shooting at an Enormous target per the chart on CRB p.161) plus possibly another +10 if the attacker is smaller than the target (CRP p. 341, smaller attacker bonus). Instead the clan rat is incorrectly getting a +20 bonus (assume this is happening because the basilisk is 2 sizes larger than the clan rat, so the ruleset is giving a +10 per size larger bonus to the attempt).

2) Using the above example to highlight a 2nd issue: the calculated modifier is not being taken into account to determine if the roll was successful or not. The behavior I'm seeing is as follows: If the BS roll isn't successful using the attacker's unmodified BS value then it's considered a miss, even though with modifiers it may have been a hit. If the roll is successful using the attacker's unmodified BS value then it's considered a hit (as it should) and the modifier is correctly used to calculate SL.

Example: clan rat has an unmodified BS of 30. If it targets a basilisk and the roll is 31 or higher (an unmodified miss) the test logs as a miss in chat regardless of appropriate modifiers, with no way to rectify, and chat reports the test results "vs 30". If the BS roll was 30 or lower it will then log a hit, but also apply the modifier (currently incorrectly calculated per issue #1) which results in a correct SL calculation. Basically any BS modifiers are not taken into account to determine whether the BS check was initially a hit or not.<br/>**From**: cdj0902@gmail.com<br/>wfrp4e: 3.3.3<br/>wfrp4e-core: 1.2.0<br/>wfrp4e-starter-set: 1.3.0

**Comment by ArisKrik** [comment]
Hi,

The above problem persists. However I think that the 2nd calculation above is not correct.

The WFRP Rulebook states that if the Size modifier allows you to hit when the test would have otherwise failed then you succeed but only with +0 SL.

Example: clan rat has an unmodified BS of 30. Disregarding other modifiers to the test, if it targets a basilisk (+40 due to size) and the roll is between 31 - 70 the test should log as a success with a SL of +0.

**Comment by ArisKrik** [comment]
Also just to add to the above Size should not add any modifiers in close combat. 
It is supposed to be only for ranged combat.

**Comment by moo-man** [comment]
This will be resolved in 3.5.0 where I plan on changing it to a bonus in the dialog instead of after the test, and Close/ranged is for the player to decide.

**Comment by moo-man** [comment]
@ArisKrik See my comment on your other issue. There is a +10 bonus to attacking larger creatures.

**Comment by moo-man** [comment]
@ArisKrik As I am unaware of any other way to contact you, please see my comment on the unrelated issue #387.

If I could have a discord tag or email to better contact you directly, I don't see you on either discords if you have a different name there.
