### ISSUE TITLE
[WFRP4e Core] empty "Earning Skill" for all Tiers of Aide

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#300]
All tiers of Advisor (Aide/Advisor/Counsellor/Chancellor) have not earning skill fileld in<br/>**From**: Christoph<br/>wfrp4e: 3.3.3<br/>wfrp4e-core: 1.2.0<br/>wfrp4e-rnhd: 1.3.0<br/>wfrp4e-starter-set: 1.3.0

**Comment by ChrisselS** [comment]
Christoph here again.
Just randomly clicked on some carrers and found some more empty fields for earning skill:
Custodian/Warden/Seneschal/Governor - all tiers of Warden Career.
Zealot/Flaggelant/Penitent/Prohet of Doom - all tiers of Flaggelant.

**Comment by moo-man** [comment]
Flagellant is not an error.
