### ISSUE TITLE
[WFRP4e Core] Career advancement box.

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#322]
"These advencements.." should be changed to "These advancements"<br/>**From**: @Righty#4833<br/>wfrp4e: 3.3.3<br/>wfrp4e-core: 1.2.0<br/>wfrp4e-eis: 1.1.0<br/>wfrp4e-rnhd: 1.3.0<br/>wfrp4e-starter-set: 1.3.0

**Comment by Righty-WFRP** [comment]
![image](https://user-images.githubusercontent.com/60031515/105169218-21880280-5b13-11eb-9a82-e423a7b6e0bf.png)
