### ISSUE TITLE
Request: Critical Wounds and Injuries apply penalties automatically

### ISSUE THREAD

**Issue by gravagehulk** [moo-man/WFRP4e-FoundryVTT#335]
Are there any plans to have the critical wounds and Injuries apply the effects automatically? For instance, breaking an arm would obviously depend on what arm was being used, but something like Bruised ribs COULD automatically apply a penalty to agility tests.

It's nice that the effects show on the character sheet, but they are easy to forget during gameplay.

Thanks!

**Comment by moo-man** [comment]
This is coming in the next update, which will be released soon. If you'd like to try it out (it needs testers), please contact me on discord.

**Comment by gravagehulk** [comment]
Oh, man. That's great news. Normally, I'd jump at the chance to test something like this, but I'm currently running an active game and I can't afford to compromise it.

Seriously looking forward to the release, though. Thanks for all of your hard work.

**Comment by moo-man** [comment]
Good call, I *would not* recommend using it for an actual game yet.
