### ISSUE TITLE
Mounts

### ISSUE THREAD

**Issue by gravagehulk** [moo-man/WFRP4e-FoundryVTT#339]
Am I missing something? How do Mounts work? If I drag/drop a mount (like a horse) to the area on the character sheet that says "mount" nothing seems to happen. It doesn't populate and I don't see anything changing. The "mount" area briefly highlights, but nothing else happens.

Thanks!

**Comment by moo-man** [comment]
It sounds like you did it right. Dragging the actor into the mount section should add it as a mount. Do you get any errors in console?

**Comment by moo-man** [comment]
Additionally, I recommend you join either the Foundry or Rat Catcher's Guild discords, which can provide you with answers to questions like these or your previous ones, as this isn't good for general discourse.

**Comment by gravagehulk** [comment]
Sorry, I don't really use Discord and I honestly thought I was reporting a bug as I just couldn't get it to work. Turns out that I was an idiot. I was trying to drag the horse directly from the bestiary in compendiums instead of an imported actor. I really should know better than that by now.

You can close. Thank you.
