### ISSUE TITLE
[Enemy In Shadows] Broken links in the Cult Magus of Tzeentch journal entry

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#363]
The links to the Enemy In Shadows Career and Talent items seem to be broken. Will add a screenshot.<br/>**From**: MyNameIsSean<br/>wfrp4e: 3.4.0<br/>wfrp4e-core: 1.3.0<br/>wfrp4e-eis: 1.2.0<br/>wfrp4e-rnhd: 1.4.0<br/>wfrp4e-starter-set: 1.4.0<br/>wfrp4e-ua1: 1.0.0

**Comment by SeanDarling1980** [comment]
![Capture](https://user-images.githubusercontent.com/78625042/107098967-6ba5ff00-6808-11eb-9764-7dd60df00416.PNG)
