### ISSUE TITLE
[WFRP4e System] Pure Soul puts a 1 AFTER the corruption threshold

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#369]
Pure Soul puts a 1 AFTER the corruption threshold, instead of adding it to the base number<br/>**From**: Ezek<br/>wfrp4e: 3.4.0<br/>wfrp4e-core: 1.3.0<br/>wfrp4e-rnhd: 1.4.0<br/>wfrp4e-starter-set: 1.4.0<br/>wfrp4e-ua1: 1.0.0

**Comment by siegn** [comment]
I did a temporary fix in my game by changing the Pure Soul effect code to:
args.actor.data.data.status.corruption.max = Number(args.actor.data.data.status.corruption.max) + 1

**Comment by siegn** [comment]
Actually nobody do what I did, that makes it increase by 1 each time you open the sheet!

**Comment by moo-man** [comment]
It depends on what the trigger is, what did you set the trigger to?

**Comment by siegn** [comment]
You mean Effect Type? "Prepare Data"

**Comment by moo-man** [comment]
Hm, that shouldn't happen then.
