### ISSUE TITLE
[WFRP4e System] Spelldamage calculation not working - when ch translated

### ISSUE THREAD

**Issue by StefanMasz** [moo-man/WFRP4e-FoundryVTT#391]
https://github.com/moo-man/WFRP4e-FoundryVTT/blob/6a1be03489fe470a386d3ef745179cae98645fc4/modules/actor/actor-wfrp4e.js#L3185

Hey, this line isn't working properly for me - I think because of translations. 

Would it hurt to use: 

`formula` += "+ " + actorData.data.characteristics["wp"].bonus 

instead?

**Comment by moo-man** [comment]
No I suppose not, but as this function doesn't generally work at all for translations, most translation modules override this function to recognize their language's words for characteristics

**Comment by StefanMasz** [comment]
Did that, but with only this line exchanged at the moment. Looks like the rest is working as intended.

**Comment by moo-man** [comment]
What language are you working on?

**Comment by StefanMasz** [comment]
german - primarily for my group, because I have a dyslexic group member. 
Pending anwser from translation partner if i'm allowed to publish
