### ISSUE TITLE
How to migrate to 3.4.0

### ISSUE THREAD

**Issue by gablorquet** [moo-man/WFRP4e-FoundryVTT#394]
As someone who has little to no experience on foundry in general, I am wondering how does a user migrate from <3.4 to 3.4. I've updated my modules via the menu in setup but my scenes and actors are still unupdated. Do I need to run some script to merge the new data?

**Comment by moo-man** [comment]
There is a pop up dialog that runs migration when you launch the world.

**Comment by gablorquet** [comment]
I did not get that pop up

**Comment by moo-man** [comment]
Can you verify your system is 3.4.0 then?

**Comment by gablorquet** [comment]
I'm dumb, I only had updated the submodules. Working now
