### ISSUE TITLE
[WFRP4e System] Cannot automate damage

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#398]
The program does not calculate the damage automatically. The error that the program indicates is: "Cannot automate damage (likely due to Tiring, or the weapon/trait is not setup correcly)

This only happens if I attack with NPC, including those of the official compendium<br/>**From**: manuelgonzrojas@gmail.com<br/>wfrp4e: 3.4.0<br/>wfrp4e-core: 1.3.0

**Comment by onanduk** [comment]
![image](https://user-images.githubusercontent.com/78826071/107432993-05cbb700-6b29-11eb-8f2c-edccdf763533.png)

**Comment by moo-man** [comment]
Does the trait have "Does damage" checked?

**Comment by onanduk** [comment]
Yes!, that was the problem. But it also happens with the NPCs in the compendium, is that normal?
Thank you

**Comment by moo-man** [comment]
Do you have an example? From what I've seen they have it checked.

**Comment by onanduk** [comment]
![image](https://user-images.githubusercontent.com/78826071/107435043-ebdfa380-6b2b-11eb-9a1b-36cb49870460.png)

**Comment by onanduk** [comment]
The goblin is from the official bestiary, it is not marked to do damage by default

**Comment by moo-man** [comment]
I'm not sure why you're seeing that, as it's correct for me. 
![image](https://user-images.githubusercontent.com/28637157/107436607-604a2080-6af3-11eb-8bcb-b9e86f7539b0.png)
