### ISSUE TITLE
Can't seem to migrate after skipping

### ISSUE THREAD

**Issue by EisenhornPuritus** [moo-man/WFRP4e-FoundryVTT#401]
Good evening. 
I skipped migration to back up my world, but after both refreshing and rebooting Foundry I don't get the migration message again. Is this normal? Has it migrated automatically? I'm sorry, but I'm basically code-illiterate. Trying to add an effect to a compendium item says "Can't edit propierty "effects" of "null"" Any way I could solve this?

Thank you for your time.

**Comment by moo-man** [comment]
You should've closed the dialog, not skipped.

Regardless, to migrate, open up the console (F12 -> console tab) and enter `new game.wfrp4e.migration().migrateWorld()`
