### ISSUE TITLE
Some character sheet attributes (wounds, experience, characteristics) cannot be changed

### ISSUE THREAD

**Issue by PiotrZakrzewski** [moo-man/WFRP4e-FoundryVTT#405]
Sometimes, it might be related to importing (?) characters wounds and or experience cannot be modified anymore. Characteristics can be unblocked when you trigger update to one of them by adding or removing a talent that modifies them. I can provide a character export json if you think it helps you.

Foundry 0.79
WFRP 3.4.1

**Comment by moo-man** [comment]
If you could provide that export I'd appreciate, thanks!

**Comment by PiotrZakrzewski** [comment]
[fvtt-Actor-Kostuch.json.zip](https://github.com/moo-man/WFRP4e-FoundryVTT/files/5970411/fvtt-Actor-Kostuch.json.zip)
here it goes.
If you cannot reproduce it - I will clone my Foundry server on GCP and give you access over some private channel (if you think that can be useful to you).

Thanks for looking into this, I love this module!

**Comment by PiotrZakrzewski** [comment]
Did you manage to reproduce it? Can I help in some way?

**Comment by moo-man** [comment]
Hi, sorry just getting around to this now, is this still an issue?

The file you've included seems to be corrupt or at least, not json and can't be imported.

**Comment by PiotrZakrzewski** [comment]
It is still an issue but pertains to experience only. Try this reproduction path: create a character and assign it some exp, spend it on anything then export the char, inport it and then see if the imported version still can have jts exp changed.

**Comment by PiotrZakrzewski** [comment]
is it possible that exporting a character on an older version and importing it on a newer one causes it?

**Comment by moo-man** [comment]
This works just fine for me on my current version, so it may have gotten fixed in the process. I'll mark it as non repro, but let me know if it's still an issue in 3.5.0.
