### ISSUE TITLE
[WFRP4 core] optimize coins and pay function dont work inside container

### ISSUE THREAD

**Issue by mcailleaux** [moo-man/WFRP4e-FoundryVTT#438]
When I use the optimize coins function or the pay function it dont work if the coins are inside a container on the inventory : 

![image](https://user-images.githubusercontent.com/18030833/109131345-01231780-7753-11eb-88af-e1566906c712.png)

**Comment by moo-man** [comment]
Thanks for the report but I don't think the original intention is for it to do so, and I still agree with that intention.
