### ISSUE TITLE
Cap Advantage at IB in System Settings appears to have no effect

### ISSUE THREAD

**Issue by gravagehulk** [moo-man/WFRP4e-FoundryVTT#439]
When I select the option "Cap Advantage at IB" in system Settings, I would expect it to stop me from granting advantage to a character above their Initiative bonus (i.e. 3), but that doesn't appear to be the case. The system allows me to keep giving them a bonus advantage to whatever number I desire.

Is this intended behavior? If so, what is the point of this option. I would think it would set a hard limit on the character sheet to prevent mistakes.

Thanks.

**Comment by moo-man** [comment]
Originally it was for the max value on the token advantage bar

**Comment by gravagehulk** [comment]
So it doesn't do anything now? Because I noticed that the bar fills up around 10. I was thinking about implementing that optional rule, but there's no point in using that option if it doesn't actually do anything.

Thanks!

**Comment by moo-man** [comment]
As far as I've seen it still works, I will check again

**Comment by gravagehulk** [comment]
Apologies. I just tested and you're right. Not sure where I got "10". I think I expected it to stop me from awarding advantage with the macro after I reached the character's IB.

I can work with this. Appreciate the fast response.

**Comment by moo-man** [comment]
It should probably hard cap it though, for the sheet at least

**Comment by gravagehulk** [comment]
It definitely doesn't do that. I was able to change the number to anything I wanted on the character sheet. That was the exact functionality I was hoping for.

**Comment by moo-man** [comment]
Yeah, I'm just saying the issue should probably stay open because that's what should happen
