### ISSUE TITLE
[WFRP4e Core] Two versions of An Invitation Miracle

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#444]
There are two of Ranald's Miracle 'An Invitation' in Core Content 1.3.1 Prayers compendium pack. The Descriptions are the same, but there are differences in other tabs: 

{wfrp4e-core.prayers.1MUSq1xRyHCaIuAL}
Extra Overcast Option is checked (and Label, Inital & Value/Overcast are set) but has a blank Effects tab. 

{wfrp4e-core.prayers.cTZVEgAyT9l4vx3i}
Extra Overcast Options i unchecked but Effects tab has a control to add Effects. 
<br/>**From**: Jagusti<br/>wfrp4e: 3.4.2<br/>wfrp4e-core: 1.3.1<br/>wfrp4e-eis: 1.1.0<br/>wfrp4e-rnhd: 1.3.0<br/>wfrp4e-starter-set: 1.3.0

**Comment by Jagusti** [comment]
![image](https://user-images.githubusercontent.com/521096/109532990-a1f63780-7ab1-11eb-847b-6f3c67f73add.png)
![image](https://user-images.githubusercontent.com/521096/109533016-aa4e7280-7ab1-11eb-9dc9-d74458c1a048.png)
