### ISSUE TITLE
[WFRP4e System] Can't find any way to apply an effect manually

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#445]
Enemy in Shadows, i'll try to avoid spoilers:
... all Characters must succeed at an Average (+20) Endurance Test or suffer the effects of the Nausea Symptom (see WFRP, page 189) until they leave...

The Nausea symptom seems to be implemented, but i cant find it anywhere in the Compendium part of Foundry. Nor anywhere else. I can see it the Galloping Trots for instance. In Details and then at Symptoms. But how do you apply just Nausea to a character?<br/>**From**: guus.goossens@gmail.com<br/>wfrp4e: 3.4.1<br/>wfrp4e-core: 1.3.1<br/>wfrp4e-eis: 1.2.1

**Comment by Guuz** [comment]
@moo-man The above is mine ;-) I'm on Github too.
