### ISSUE TITLE
[WFRP4e System] maestro

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#484]
I just want to say that I love what you have done with this system but one thing I thought that was unfortunate was that Item tracks from the maestro module do not work with the system. For example I tried to apply it to the trappings and managed to do so for hand weapons but when I rolled it did not apply the audio effect for the given role. I understand that it is not your module but I wanted you to know.

Thank you for your great work,
Kyle <br/>**From**: <br/>wfrp4e: 3.4.1<br/>wfrp4e-core: 1.3.1

**Comment by grz0** [comment]
The issue could probably be closed. Maestro module is not in development anymore and is not v11 compatible:
https://foundryvtt.com/packages/maestro/

**Comment by moo-man** [comment]
Closing as stale
