### ISSUE TITLE
Packs folder doesn't exists

### ISSUE THREAD

**Issue by Zan135kin200** [moo-man/WFRP4e-FoundryVTT#49]
Packs doesn't exists neither in system.json and so in game there are no bestiray, carreers, skills, talents...
Is it normal?

**Comment by moo-man** [comment]
Upon creating a world you should see a pop-up that relates to this. I removed them due to copyright reasons, but I am working with C7 officially to bring them back. In the meantime, if you need assistance in recreating content for your games, contact me on discord.
