### ISSUE TITLE
[WFRP4e System] AP doubled on Apply Damage

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#490]
When hitting "Apply Damage" after a hit, the damage calculation seems wrong when actor is wearing armor.

TB is inserted correctly, but AP is doubled.

As example:
If hit is Body and Damage is 8, and actor wears "Mail Shirt" it shows:
Damage Applied: 2 (2 TB + 4 AP)

A "Mail Shirt" however has AP 2 Body, but it shows as AP 4 in the calculation instead of 2.
A "Leather Jerkin" on Body shows AP 2 instead of 1.

In Trappings list and Character Sheet/Combat the numbers for the armor and the covered body parts do show correctly.<br/>**From**: khuri@khuris.com<br/>wfrp4e: 3.4.1<br/>wfrp4e-core: 1.3.1<br/>wfrp4e-starter-set: 1.4.1

**Comment by Khuris** [comment]
See attached image as example.

![Untitled-1](https://user-images.githubusercontent.com/77492887/113159622-0a653f80-923d-11eb-8642-671cf8fa07ac.jpg)

**Comment by moo-man** [comment]
This is because your weapon is undamaging
