### ISSUE TITLE
Add missing tables from previous WFRP4e system

### ISSUE THREAD

**Issue by wesbaker** [moo-man/WFRP4e-FoundryVTT#50]
When rolling a critical there's a button to roll on the critical table, but no critical table exists. We just need to bring over the tables from @CatoThe1stElder's repository: https://github.com/CatoThe1stElder/WFRP-4th-Edition-FoundryVTT/tree/stable/tables

**Comment by wesbaker** [comment]
Following up: I'm guessing these are currently excluded due to licensing issues (after looking at the Ratcatcher's Discord).

**Comment by moo-man** [comment]
Correct, they will be added in the official C7 module
