### ISSUE TITLE
[Starter Set] Gunnar missing Grouped & Advanced Skill Advances

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#500]
Skill Adv
Heal 5
Lore (Trolls) 10
Trade (Jeweller) 10
Evaluate 10
Lore (Giants) 7
Language (Battle Tongue) 5

He is actually also missing the Talent Read/Write.
Although it doesn't show on the Character Pack it does on Gate Fold. Dwarves get Read/Write or Relentless by default as since he has neither it must be an oversight.<br/>**From**: Simulacrum<br/>wfrp4e: 3.5.0<br/>wfrp4e-core: 1.3.2<br/>wfrp4e-eis: 1.2.2<br/>wfrp4e-rnhd: 1.4.1<br/>wfrp4e-starter-set: 1.4.2<br/>wfrp4e-ua1: 1.0.2

**Comment by simulacrum-1** [comment]
Oh while you have the character open I forget he starts as Career current on both Apprentice Artisan and Troll Slayer.
Should be Current – Giant Slayer
With Troll Slayer – Completed
Apprentice Artisan – (uncompleted)
