### ISSUE TITLE
Token Size does not stick on refresh/reload

### ISSUE THREAD

**Issue by gravagehulk** [moo-man/WFRP4e-FoundryVTT#501]
I have some encounters set up with different sized creatures (based on the "size" trait in notes) as well as some oversized icons on my landing page. Whenever I refresh or reload a scene or Foundry, the sizes of the tokens randomly change. Below is a giant spider encounter. All of the spiders are of different sizes ranging from "little" to "huge". When I reload the scene or come back to it, they all reset to something random:

![image](https://user-images.githubusercontent.com/69117052/113307385-ae48fc80-92ca-11eb-9669-21cd60c5edbd.png)

Here you can see what I have one of them set to. It will obey the setting if I disable and then enable it again, but as soon as I refresh the page, it resets to something else: 

![image](https://user-images.githubusercontent.com/69117052/113307536-dd5f6e00-92ca-11eb-9147-bf09877bac8b.png)

Then there's my landing page. I have all of the tokens set to 2X2 to cover the artwork (they are invisible so PCs can seamlessly access their character sheets from the artwork). Every time I reload, the token resets the size to 1X1.

![image](https://user-images.githubusercontent.com/69117052/113307740-1566b100-92cb-11eb-8eb5-d29523bc859f.png)

![image](https://user-images.githubusercontent.com/69117052/113307809-27485400-92cb-11eb-86a5-1c582924795f.png)

This has been really annoying. I basically spend the first 15-20 minutes of every session fixing everything before we can play.

**Comment by moo-man** [comment]
Uncheck the size calculation in the actor settings

**Comment by gravagehulk** [comment]
I may just be incompetent, but I have no idea where that is. I have looked in settings, token configuration, and the character sheet.
