### ISSUE TITLE
[WFRP4e Core] Rupture needs un-nerfing

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#522]
Core rulebook states that Rupture on the Minor Miscast table gives 1d10 Bleeding Conditions.   

Andy Leask has stated that it should be just 1 Bleeding condition: this is an oversight following a rewrite of the bleeding rules. 

Documented in Unofficial FAQ. 
https://docs.google.com/document/d/1HGKAP-IbHodpm4Cmdn98HUhJwG-J7nZg-iTliDDlZSM/edit#heading=h.usw3vn3cjtrr

(Pretty devastating as written. When combined with a Dhar miscast, well, kiss goodnight to those adventurers and probably Bogenhafen too ...)
<br/>**From**: Jagusti<br/>wfrp4e: 3.5.0<br/>wfrp4e-core: 1.3.2<br/>wfrp4e-eis: 1.2.2

**Comment by Jagusti** [comment]
Discord link: https://discord.com/channels/449845411344154634/479275054023311362/735963499544576080
