### ISSUE TITLE
[WFRP4e Core] Over Exposure

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#535]
Cold Exposure: Your first failure causes a penalty of –10 Ballistic Skill,
Agility and Dexterity. The second failure reduces all *other* Characteristics by –10.

At the moment the Cold Exposure 2 alters all stats so –20 Ballistic Skill,
Agility and Dexterity.<br/>**From**: Simulacrum<br/>wfrp4e: 3.5.1<br/>wfrp4e-core: 1.3.3<br/>wfrp4e-dotr: 1.0.0<br/>wfrp4e-eis: 1.2.2<br/>wfrp4e-rnhd: 1.4.1<br/>wfrp4e-starter-set: 1.4.3<br/>wfrp4e-ua1: 1.0.2

**Comment by simulacrum-1** [comment]
Ignore. I just realised you probablyintended them not stack and I should  remove Cold Exposure 1 rather than stack them. Doh!

**Comment by moo-man** [comment]
Right, you should only have one
