### ISSUE TITLE
[WFRP4e System] Mangled Hand: TypeError

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#542]
Specificly added Magled Hand critical to a Mutant NPC and got the following message:

Error when running effect Mangled Hand: TypeError: Cannot read property 'then' of undefined<br/>**From**: mogrogh#4778<br/>wfrp4e: 3.5.1<br/>wfrp4e-core: 1.3.3<br/>wfrp4e-dotr: 1.0.0<br/>wfrp4e-eis: 1.2.2<br/>wfrp4e-rnhd: 1.4.1<br/>wfrp4e-starter-set: 1.4.3<br/>wfrp4e-ua1: 1.0.2

**Comment by mogrogh** [comment]
I tried this again and got another error-message instead.

Error when running effect Mangled Hand: TypeError: args.actor.setupSkill(...) is undefined actor-wfrp4e.js:4651:17
Foundry VTT | Rendering ModuleManagement foundry.js:4503:15

When I add "Magled Hand" to an NPC I get above message. They don't have the Endurance skill. When I add the crit to a PC the Endurance Test comes up.

I tried to add Mangled Hand to an NPC in a brand new world and I got the above message., Only Foundry, WFRP4-system and core module activated. Didn't create a PC in this world but expect it to work.

**Comment by moo-man** [comment]
Okay, so it's specifically with an actor that doesn't have the Endurance skill, so it's not an issue with Mangled Hand itself, more that skill tests for a skill you don't have throw an error.

**Comment by mogrogh** [comment]
This new error yes. The old one can't I reproduce either.

**Comment by moo-man** [comment]
Okay, well, thanks for the testing, let me know if you come up with anything new.
