### ISSUE TITLE
[WFRP4e System] Malignant Influences miscast

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#543]
Page 236 Core Rules:
Malignant Influences
Casting close to sources of Corruption makes controlling the Winds of Magic much more difficult. When attempting a Language (Magick) or Channelling Test in the vicinity of a Corrupting Influence (see page 182), any roll of an 8 (representing the eight-pointed symbol of Chaos) on the units die results in a Minor Miscast as the Magic goes wild. If you already have a Minor Miscast on the Test for another reason, the Miscast escalates to a Major Miscast.

The text says "unit die" but I got it when an NPC got 8 on the "tens die".<br/>**From**: mogrogh#4778<br/>wfrp4e: 3.5.1<br/>wfrp4e-core: 1.3.3<br/>wfrp4e-dotr: 1.0.0<br/>wfrp4e-eis: 1.2.2<br/>wfrp4e-rnhd: 1.4.1<br/>wfrp4e-starter-set: 1.4.3<br/>wfrp4e-ua1: 1.0.2

**Comment by mogrogh** [comment]
![image](https://user-images.githubusercontent.com/69079040/115123409-30207180-9fbd-11eb-9f39-d871df212bcc.png)

**Comment by moo-man** [comment]
The Other effect is from the EIS Dhar miscast rules, is that what you're referring to?

**Comment by mogrogh** [comment]
Oops, hadn't read that book yet. See that now. You can close this then.
