### ISSUE TITLE
[WFRP4e System] Unable to load font on Firefox

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#545]
Hi, I'm getting this error while loading my wfrp world:
The stylesheet []/systems/wfrp4e/fonts/CaslonAntique.ttf was not loaded because its MIME type, "font/ttf", is not "text/css".

Everything loads fine on Edge.

Foundry v0.7.9
WFRP v3.5.1
Firefox v88.0<br/>**From**: Dennis<br/>wfrp4e: 3.5.1<br/>wfrp4e-core: 1.3.3<br/>wfrp4e-rnhd: 1.4.1<br/>wfrp4e-starter-set: 1.4.3

**Comment by grz0** [comment]
Probably fixed. Works for me on Firefox:
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/3605541/1b55e6ee-8ad9-4e35-9cbb-315c2b74307e)

**Comment by moo-man** [comment]
Closing until further issues are discovered
