### ISSUE TITLE
fetch is missing async/await and race condition brakes Tables list

### ISSUE THREAD

**Issue by silentmark** [moo-man/WFRP4e-FoundryVTT#546]
Hi, 

please correct me if i'm wrong, but for me Tables doesn't work unless i change the chained method in async/await one and add await before table file fetch. link to line as reference. 

https://github.com/moo-man/WFRP4e-FoundryVTT/blob/7c4913048d5321cd5837343ef967e597a25417e0/modules/hooks/ready.js#L46

**Comment by moo-man** [comment]
Can you post your code? I'm not sure I understand as you don't need `await` if you use `then`

**Comment by silentmark** [comment]
i left only important parts: 

```
await new Promise(async (resolve) => {
.... 
            //here async resp is needed
            await FilePicker.browse("data", modules/${m}/tables).then(async resp => {
....
            //here await is needed
                 await fetch(file).then(r => r.json()).then(async records => {
....
              }
            })
....
          }
      }
      // Load tables from world if it has a tables folder\
     // for world tables, same story
....
      resolve()
    })
    // without those async/await before fetch, below code executes before all tables from module/world is processed, and therefore list of tables is empty or incomplete.
    if (game.user.isGM)
      await game.settings.set("wfrp4e", "tables", WFRP_Utility._packageTables())
    else 
    {
      let tables = game.settings.get("wfrp4e", "tables")
      for(let table in tables)
        WFRP_Tables[table] = tables[table];
    }

    game.wfrp4e.utility.addTablesToSidebar(ui.sidebar._element.find("#tables"))
```

**Comment by moo-man** [comment]
Yeah I'm not sure why this would be needed, except I do notice the first promise might be missing a resolve.

**Comment by silentmark** [comment]
Maybe that additional resolve() solves the problem as well, when i was playing around with this, additional async/await solved problem for me.

**Comment by moo-man** [comment]
What exactly is the problem? Do the tables not show up in the sidebar?

**Comment by silentmark** [comment]
They didnt show up at all, or shown up incomplete. When i run in debug mode, i saw, that `game.wfrp4e.utility.addTablesToSidebar(ui.sidebar._element.find("#tables"))` was executing before the promise above finished. and the `fetch` method seemed to be the one that was not awiated. It's wierd though, if this only happens to me, because fetch should be asynchronous wrapper for request/response: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by silentmark** [comment]
Thanks, sorry i didn't give you a PR for this issue.

**Comment by moo-man** [comment]
No worries, I preferred to do it so I could get rid of then statements
