### ISSUE TITLE
Clicking on the button to buy advances too quickly breaks the exp calculation

### ISSUE THREAD

**Issue by depili** [moo-man/WFRP4e-FoundryVTT#575]
![image](https://user-images.githubusercontent.com/3681069/117572583-41e8c680-b0dc-11eb-934f-fe9571b1d4e2.png)

In this case was buying 5 advances for perception by clicking with the mouse on a decentish pace and after that was wondering why there was too much exp left. The log snippet above revealed that one of the purchases didn't use any exp at all.

System version 3.5.1

**Comment by moo-man** [comment]
I doubt the log is the issue here, and would break regardless

**Comment by depili** [comment]
Log might make the timing window for the glitch larger. I would suggest
disabling the button on click and then re-enabling it after the exp
transaction has been finished to prevent the issue from happening in the
first place.

**Comment by moo-man** [comment]
I've added some awaits and it seemed to improve, I will have to see, as it could be worse on a remote server.
