### ISSUE TITLE
[WFRP4e System] Regenerate Trait Active Effect

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#578]
Unsure if this is a WFRP or Foundry-bug.

When a creature regenerates everything is updated except the status-bar.

Add a troll to combat and give it some damage, like typing in -15 in the token health. Advance a few rounds and it has healed. The status bar tracking health is still as it was when you gave it damage.

Try reload the page now, F5, and after the reload the troll has the health of the status bar, not the regenerated health as it should have.

I also noticed the sheet health doesn't get updated if it's updated with the Regenerate AND the sheet is open. If you close and open the sheet, the health is updated.

Sheet does get updated if you edit the health on the token, like enter +1.

Tested with no modules activated and only WFRP system installed. No change when all my ordinary modules are installed.<br/>**From**: mogrogh #4778<br/>wfrp4e: 3.5.1

**Comment by mogrogh** [comment]
This is probably mostly unnoticed since you hopefully manage to damage a creature with regenerate and change it's health by giving it damage.
