### ISSUE TITLE
Issue with let hasDamaging / let hasImpact

### ISSUE THREAD

**Issue by silentmark** [moo-man/WFRP4e-FoundryVTT#579]
https://github.com/moo-man/WFRP4e-FoundryVTT/blob/9da8627909ee3747dd5b3e102cd1e79337eeaec0/modules/system/opposed-wfrp4e.js#L530

I believe above line of code is causing problems in: 

https://github.com/moo-man/WFRP4e-FoundryVTT/blob/9da8627909ee3747dd5b3e102cd1e79337eeaec0/modules/system/opposed-wfrp4e.js#L563

This is because you are defining with **let** keyword hasDamaging and hasImpact in inner scope, and when you are referring to them in outer scope below, those variables are unknown. Probably this should like like following: 

```
let hasDamaging = false;
let hasImpact = false;
if (opposeData.attackerTestResult.weapon) 
{
      hasDamaging = opposeData.attackerTestResult.weapon.properties.qualities.includes(game.i18n.localize("PROPERTY.Damaging"))
      hasImpact = opposeData.attackerTestResult.weapon.properties.qualities.includes(game.i18n.localize("PROPERTY.Impact"))

```

**Comment by moo-man** [comment]
Odd that this hasn't come up, do you have a process where this would produce an error and/or cause a miscalculation?

**Comment by silentmark** [comment]
![image](https://user-images.githubusercontent.com/7930626/118105464-b3768c80-b3dc-11eb-97d3-cfed6f78f975.png)

you can try here: https://kembrowski.ddns.net/game

**Comment by silentmark** [comment]
and i think it's because of how translations are working this error didnt came up - it tries to split "Error.Opposed" by ".", and since in the oroginal en.json file from foundry itself there is a translation for "Error" word, which is not an object - we dont get the notification about this failure.

**Comment by silentmark** [comment]
you can take a look into this commit:  https://github.com/silentmark/wfrp4/commit/4b545480d850df04c0457bb08dd5bc2da5a1b67f - it solves the issue for me (i didnt push it to my world yet just in case you would like to reporduce the problem)

**Comment by moo-man** [comment]
Could you submit a PR for this, seeing as you've already done it?

**Comment by silentmark** [comment]
will do that over weekend, as my version of wfrp4 system is a bit customized to handle Polish translation better, i need to read a bit how to do that correctly without breaking your repo.

**Comment by moo-man** [comment]
Ok, well if it's possible to include those changes as well, I would like them, since it might help others out.
