### ISSUE TITLE
Warhammer Browser does not open

### ISSUE THREAD

**Issue by Flogsy** [moo-man/WFRP4e-FoundryVTT#611]
When I click on the "Browser" button on the bottom of the "Compendium Packs" tab nothing happens, the Warhammer Browser does not open as it has in the past. What can I do to get the Warhammer Browser back?

**Comment by moo-man** [comment]
Hi, I can't reproduce this, what system/module versions do you have?

**Comment by Flogsy** [comment]
Hi moo-man,
thank you for you quick reply. I am using Foundry VTT version 0.7.9 and WFRP4 3.6.1. My game is hosted at The Forge.
I tried it on Firefox and Chrome, but the Browser button simply does not react at all. I think this started after the last update of the WFRP core module or the version before.
Should I try it with new game and only the WFRP core module installed?

**Comment by moo-man** [comment]
Do you get any errors in console?

**Comment by Flogsy** [comment]
Where would I see that?
Sorry, but I don´t have any experience with the console.

**Comment by Flogsy** [comment]
I just created a new WFRP4 game in Foundry with only the core module installed and the Warhammer Browser opened instantly, so obviously some module is blocking it in my other game. I will try to find out which one it is and let you know.

**Comment by Flogsy** [comment]
After a lot of switching on and off of moduls I found the on responsible for this effect: "Active Token Lighting"
When I activate this modul, then the Warhammer Browser doesn´t work, when I deactivate it then it works again. I tried it several times to make sure that it is really this modul.
Perhaps you can find out the cause of this, to prevent it from happening with other moduls.

**Comment by moo-man** [comment]
Odd, I will take a look, thanks for the troubleshooting

**Comment by moo-man** [comment]
Issue comes from the module not specifying its compendium pack as dnd5e only
