### ISSUE TITLE
[WFRP4e System] Maximum Depth Error on Rerolls

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#613]
Characters seem only able to reroll once using fortune (fine) and once using a dark deal before getting a maximum depth reached error.  If I reroll with just a dark deal I can reroll twice and then I hit the error.  If rerolling using a dark deal it adds the corruption even if the error occurs - but fails to reroll. 

Once the error has happened I can't even roll a d100 and edit the roll or the SL level.

In opposed test I will occasionally get the error after 1 reroll from any source.

I have tested this on a test world with only the wfrp system loaded & on a test world with the wfrp system, core, TEW 1&2, Archives, & middenhiem modules loaded and initialised - it makes no difference.  
<br/>**From**: Fliptop_23#5121 or alex.hunt23@gmail.com<br/>wfrp4e: 3.6.1<br/>wfrp4e-archives1: 1.0.1<br/>wfrp4e-core: 1.3.5<br/>wfrp4e-dotr: 1.0.1<br/>wfrp4e-eis: 1.2.4<br/>wfrp4e-middenheim: 1.0.1<br/>wfrp4e-rnhd: 1.4.3

**Comment by Fliptop023** [comment]
[Maximum Depth Error.log](https://github.com/moo-man/WFRP4e-FoundryVTT/files/6551311/Maximum.Depth.Error.log)
Attached Log

**Comment by Fliptop023** [comment]
[localhost-1622177258101.log](https://github.com/moo-man/WFRP4e-FoundryVTT/files/6558248/localhost-1622177258101.log)
Attached a second log from an event tonight during testing (of something different) where maximum depth was reached on the first reroll of the session

**Comment by depili** [comment]
Also ran on the same issue today
