### ISSUE TITLE
[Starter Set] Reikhartd's bullshit

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#615]
His WS is 70 but the book says 74. FIX THIS SHIT IMMEDIATELY!!!<br/>**From**: YOU FUCKING KNOW WHO#6666<br/>wfrp4e: 3.6.1<br/>wfrp4e-core: 1.3.5<br/>wfrp4e-eis: 1.2.4<br/>wfrp4e-rnhd: 1.4.3<br/>wfrp4e-starter-set: 1.4.4<br/>wfrp4e-ua1: 1.0.3

**Comment by Fliptop023** [comment]
can you set it to 74 for everyone but this person?

**Comment by moo-man** [comment]
@Fliptop023 

Lol no worries, I know this person a bit too well...

**Comment by Fliptop023** [comment]
I figured, that why I was suggesting doing programmer tricks of detecting if it is that person logged in :D
