### ISSUE TITLE
Blank string on the experience reason for change results in line in the log

### ISSUE THREAD

**Issue by depili** [moo-man/WFRP4e-FoundryVTT#634]
system version 3.6.1, foundry 0.7.10

In this context I fat-fingered the new value for the experience spent, entered a blank reason hoping it would cancel the transaction. But instead it made the change without a line in the log. Thus the correction to the experience amount makes the log look little sketchy, as the spent and received amounts don't match the totals printed anymore.
![image](https://user-images.githubusercontent.com/3681069/120904672-182cac00-c656-11eb-9c96-80788455b93e.png)

The log is missing one +200 exp event from the typo.

**Comment by depili** [comment]
A nice improvement would be to offer a cancel button on the "reason for change?" dialog. Also showing the change amount on the said dialog would be nice to confirm the numbers one entered.

**Comment by moo-man** [comment]
I'm not sure I understand, this is intentional, you can simply delete the log entry (or ask the GM to if you're the player) if it was an accidental change.

**Comment by depili** [comment]
Still I think a line with an empty reason would be better than no line at all. And being able to cancel the change on the reason box would be welcome.

**Comment by depili** [comment]
So the underlying expectation was that there would be a way to cancel the change in amount spent on the reason dialog and also that all changes (at least initiated by a player) would result in changes on the log.

**Comment by depili** [comment]
Closing the reason dialog from the X on the header seems to also commit the change and skip the log entry
