### ISSUE TITLE
Automatic Advantage Calculation

### ISSUE THREAD

**Issue by gravagehulk** [moo-man/WFRP4e-FoundryVTT#656]
I've been running a game of WFRP in Foundry for about two months. I have all of the premium modules. At one point, a few games ago, I noticed that when a player succeeded in an opposed test in combat, advantage was automatically granted to them. While it wasn't consistent (no advantage was granted on successful range tests), it was a welcome feature as it reduced some of the manual work I have to do as a GM.

Sometime after that game, it stopped working. I no longer see advantage automatically granted under any conditions. My question is: Was this an actual feature? And was it removed? Because I'm beginning to think I was crazy and that it didn't exist at all. But my players and I definitely saw advantage being automatically granted, unless it was some kind of weird glitch.

Thank you.

**Comment by moo-man** [comment]
This was never a feature, no, I know of someone who was toying with adding it with some success, but it's never been a thing in the system.

**Comment by gravagehulk** [comment]
> This was never a feature, no, I know of someone who was toying with adding it with some success, but it's never been a thing in the system.

So I am crazy? Man, I wish I knew what was happening. At the time l, I thought “oh, cool, he added this”. Oh well, thanks for confirming.

**Comment by moo-man** [comment]
Yeah dunno, maybe it was a module that stopped working, no idea what it might be though.
