### ISSUE TITLE
[Improvement] NPC Sheet: Ability to hide Ambitions (party and/or personal)

### ISSUE THREAD

**Issue by Havoclivekiller** [moo-man/WFRP4e-FoundryVTT#658]
I don't think its needed for most NPCs and being to see the GM notes at a glance without the need for scrolling is a good QoL.

**Comment by moo-man** [comment]
I don't really understand what you're requesting, can you elaborate?

**Comment by Havoclivekiller** [comment]
Ability to hide this section
![image](https://user-images.githubusercontent.com/21118924/122458301-f44f5b80-cfaf-11eb-9554-ce87aa9d7710.png)

so it looks more like this
![image](https://user-images.githubusercontent.com/21118924/122458432-147f1a80-cfb0-11eb-809c-477a114ff75b.png)
