### ISSUE TITLE
[Question] Estimate on 0.8.x compatibility?

### ISSUE THREAD

**Issue by nottsknight** [moo-man/WFRP4e-FoundryVTT#668]
Hi! Just wondering if there was any estimate on when this excellent system will be made compatible for 0.8.x? I can see you've got a `0.8` branch, just thinking that I can't roll back my Foundry because of some other worlds I've got going so am a little bit stuck for a while :) Thanks for the phenomenal amount of work you're doing!

**Comment by moo-man** [comment]
I'll open it up for testing soon but still think it'll be a while, I'd recommend getting a second installation of foundry to run both versions
