### ISSUE TITLE
[Middenheim] Career table missing wolf kin

### ISSUE THREAD

**Issue by Schnugaf** [moo-man/WFRP4e-FoundryVTT#677]
Hi,

Seems that the intended distribution from career.json in the Middenheim Module isn't applied correctly to the Career table for the Core when Middenheim module has been initialized.

Json shows following for Wolf-kin;
        {
            "range": {
                "human-middenheimer": [66,68],
                "human-middenlander": [59,60],
                "human-nordlander":   [57,58]
            },
            "name": "Wolf Kin"
        },

But wolfkin is not showing for the table on any of these sub-species, nor an option in the Character Creation section.
While I've created a ticket, I can also see that "Default" is a sub-species choice for Human, in character creation, which doesn't have any content.

I've attempted this with all official wfrp modules and with only Core and Middenheim module. Same result.
The different sub-species tables are changed, but wolf-kin is not showing on any of them.

Running on 0.7.10 and 3.6.2. No third-party modules besides official wfrp modules.

**Comment by moo-man** [comment]
Thanks, this may require a more extensive rework of the table column system.
