### ISSUE TITLE
Channelling options missing

### ISSUE THREAD

**Issue by CasiussDev** [moo-man/WFRP4e-FoundryVTT#678]
I had an actor with Channelling(Dhar) 20 and Channelling(Ulgu) 15. When trying to channel a Lore of Shadows spell such as Illusion, the options in the drop-down for "Channel Skill" were only Channelling(Dhar) and Willpower. No option for Channelling(Ulgu).

It has been reproduced with other combinations as well

https://discord.com/channels/449845411344154634/712500603250802829/860106507088297994

**Comment by moo-man** [comment]
This should be fixed in 4.0.0
