### ISSUE TITLE
Unable to open most rules

### ISSUE THREAD

**Issue by Heilemann** [moo-man/WFRP4e-FoundryVTT#68]
See attached recording. This is true for most rules, but not all.

![Untitled2](https://user-images.githubusercontent.com/203049/98295426-92416900-1f7f-11eb-9944-34530ed43413.gif)

**Comment by moo-man** [comment]
Any errors in console?

**Comment by Heilemann** [comment]
Turns out I had to update everything, and now it works. I have a follow up question I'll DM you about.
