### ISSUE TITLE
[Death on the Reik] Resolve is not a function

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#684]
Error when trying to sell cargo via trade tool. 
FWIW Availability dropdown has no options. <br/>**From**: Jagusti#3610<br/>wfrp4e: 3.6.2<br/>wfrp4e-core: 1.3.6<br/>wfrp4e-dotr: 1.0.2<br/>wfrp4e-eis: 1.2.4

**Comment by Jagusti** [comment]
See video in Discord: https://discord.com/channels/170995199584108546/697845419593695362/861541382996492288 ... happens even if quantity is not blank.
