### ISSUE TITLE
[WFRP4e System] Status is not clearing

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#69]
In Actor is not status clearing if you remove your current career.<br/>**From**: GaniGhost<br/>wfrp4e: 3.0.0<br/>wfrp4e-core: 1.0<br/>wfrp4e-rnhd: 1.0<br/>wfrp4e-starter-set: 1.0

**Comment by kacperjdrzewicz** [comment]
![second_a](https://user-images.githubusercontent.com/29116668/98295690-2e846380-1fb2-11eb-97a8-f89c429aaead.png)
![second_b](https://user-images.githubusercontent.com/29116668/98295695-2fb59080-1fb2-11eb-97e9-e3946bb3649d.png)
