### ISSUE TITLE
[WFRP4e System]  Ammunition Qualities without the skill

### ISSUE THREAD

**Issue by Txus5012** [moo-man/WFRP4e-FoundryVTT#717]
When using a weapon without advances in the right skill, the qualities are correctly removed. But the qualities of the ammunition are not removed. This is mainly an issue for crossbows, as they are the only ranged weapons with ammunition that can be used without the skill.

![Ammunition](https://user-images.githubusercontent.com/87753744/126624719-f7f2bf2e-97c3-4959-a1fd-fdcfa448442c.jpg)

P.S. I know that bows can't be used without advances in Ranged (Bow), just showing how it looks.

**Comment by moo-man** [comment]
This is intentional
