### ISSUE TITLE
[WFRP4e Core] Weapon trait

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#729]
An error message appears when using a creature's Weapon rating to attack.

"Something went wrong with applying weapon modifiers: TypeError: Cannot read property 'bands' of undefined"

It seems to work well when defending.<br/>**From**: Txus#5021<br/>wfrp4e: 4.0.4<br/>wfrp4e-core: 2.0.2

**Comment by Txus5012** [comment]
This happens with all attack traits, like Horns, Vomit, Tentacles, etc.
