### ISSUE TITLE
[WFRP4e Core] Importing All Content not working

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#73]
When I click the Bestiary and Import All Content. It creates an empty files and dont Import the creatures to a folder. Getting this error in the console.
https://cdn.discordapp.com/attachments/614126366442651679/774017859893329930/Capture.PNG<br/>**From**: danil0<br/>wfrp4e: 3.0.0<br/>wfrp4e-core: 1.0

**Comment by Kelliak** [comment]
Appears to happen for all the actor compendiums.
