### ISSUE TITLE
[WFRP4e System] [Bug] Cannot add a mount to a character when using non-English translation

### ISSUE THREAD

**Issue by Phenomen** [moo-man/WFRP4e-FoundryVTT#740]
1. Change language to non-English
2. Drag-and-drop mount to the character sheet

Result: error "You can only mount creatures of a larger size".

![image](https://user-images.githubusercontent.com/138311/126916101-d88536c6-a433-45d8-990e-3050199386af.png)

_Note: There is no such issue when I switch to English. Translation does not change any scripts (e.g. Babele), it's only translating en.json so it should not interfere with logic_

**Comment by moo-man** [comment]
I'm confused as to the issue here, is it not translatable?

**Comment by Phenomen** [comment]
The issue is that I get an error that I should not get at all. Horse should be added to the mount section on drag-and-drop. When I switch to English, I can add it just fine.

![FoundryVTT_wHkhaTht36](https://user-images.githubusercontent.com/138311/126916458-06892417-df04-4b53-98df-1fa740d6455a.png)
