### ISSUE TITLE
[WFRP4e Core] issue with fresh installation

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#743]
Hi, 

Brand new world, brand new foundry instance failes to initialize (only core modeule, without any other paid modules):

initialization.js:130 Uncaught (in promise) TypeError: packList is not iterable
    at WFRP4eContentInitialization.initializeEntities (initialization.js:130)
    at initialization.js:119

this.data.module.data.flags is empty object, while method tries to process: this.data.module.data.flags.initializationPacks<br/>**From**: marek.kembrowski@gmail.com<br/>wfrp4e: 4.0.5<br/>wfrp4e-core: 2.0.0

**Comment by silentmark** [comment]
after doublechecking - issue can be closed. Something broke in the manifest and flags were missing. After full reinstal - works fine. Sorry for confusion
