### ISSUE TITLE
[WFRP4e System] Possible error in the cracked ribs critical injury

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#774]
Dragging the injury from chat to the character sheet. The reductions to S and Ag seem to be working correctly but the halving of Movement results in some strange fractions appearing in the entry. If you then go and enter the normal move (3 for a human) it halves it properly and all works.  <br/>**From**: @Dipnotz<br/>wfrp4e: 4.0.6<br/>wfrp4e-core: 2.0.4<br/>wfrp4e-dotr: 2.0.3<br/>wfrp4e-eis: 2.0.3<br/>wfrp4e-rnhd: 2.0.2

**Comment by Dipnotz** [comment]
Little more detail on this - it looks like it recalculates the .5 movement every time the character sheet is opened rather than just once when the effect is applied.  So if a player opens/closes 3 times his 3 Movement gets pretty small!

**Comment by moo-man** [comment]
Fixed via https://github.com/moo-man/WFRP4e-FoundryVTT/commit/7cc231033cffd75d5f5d28fb3dd242d125c2537d
