### ISSUE TITLE
[WFRP4e Core] Character Creation - Career button not working

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#781]
When creating a character the Career button no longer works. <br/>**From**: dillon@wolftracks.com.au<br/>wfrp4e: 4.1.0<br/>wfrp4e-archives1: 2.1.0<br/>wfrp4e-core: 2.1.0<br/>wfrp4e-dotr: 2.0.4<br/>wfrp4e-eis: 2.0.4<br/>wfrp4e-middenheim: 2.1.0<br/>wfrp4e-rnhd: 2.1.0<br/>wfrp4e-starter-set: 2.0.2

**Comment by Hyperwolf** [comment]
Fixed by disabling "Nations of Man" thanks.
