### ISSUE TITLE
Translation for the official core module

### ISSUE THREAD

**Issue by guillaumecd15** [moo-man/WFRP4e-FoundryVTT#79]
Hi 
i ve bought ( i already had the boot btw) on C7 the module core rules.
I am wondering if it's still possible to get it translate in french ?
for me , it's fine in english, but not for most of my players.

Is there a way to get the previous French translation module compliant? or a way to adapt it

Thanks in advance

**Comment by sladecraven** [comment]
Check on Discord FR https://discord.gg/pPSDNJk

**Comment by moo-man** [comment]
I'm going to go ahead and close this as it's not really something I can work on myself.
