### ISSUE TITLE
[WFRP4e System] Blast with 0 SL = no AoE

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#800]
If I cast blast and I don't get any overcasts, the game doesn't offer me the possibility to place a zone.
It would be nice in general even without overcast to display the elements of the spell (AoE, Range, Target ...)<br/>**From**: gauche.c@gmail.com<br/>wfrp4e: 4.1.0<br/>wfrp4e-core: 2.1.0

**Comment by cgauche** [comment]
![blast](https://user-images.githubusercontent.com/6978081/130759945-bdd075c2-3ad9-4317-bf7c-5a8ad7c1570f.JPG)

**Comment by moo-man** [comment]
The AOE is available in the dropdown of the spell on the sheet

**Comment by cgauche** [comment]
All right. Would it be a problem to put them in the chat room too?
It would avoid having to look for the elements in different places in the case of an overcast or not.

**Comment by moo-man** [comment]
I'm going to say "maybe" on this
