### ISSUE TITLE
Toggle for trappings not carried, that discounts them from encumbrance

### ISSUE THREAD

**Issue by RKnowlesLeak** [moo-man/WFRP4e-FoundryVTT#840]
**Is your feature request related to a problem? Please describe.**
No, not related to a problem.

**Describe the solution you'd like**
A toggleable tickbox that indicates whether a trapping is carried or not.
This would allow players to keep track of possessions that they have accumulated, but only need on occasion, perhaps usually leaving them at home or onboard their barge.
If an item is not carried, it does not count toward encumbrance, now can it be equipped.

**Additional context**
None

**Comment by RKnowlesLeak** [comment]
That last bit should have read "nor can it be equipped".

**Comment by moo-man** [comment]
So why does the existing solution of containers not work here?

**Comment by RKnowlesLeak** [comment]
Perhaps I have misunderstood how containers work and am not
using them correctly. As I understand it, they have an encumbrance
themselves (which is reduced by one if they are worn) and have a capacity
measured in encumbrance too. So the system works as I expect it to for the
common use case. I can carry two encumbrance worth of stuff in a sling bag
which weighs only one, and if worn reduces by one counting as nothing.
But let's say I have a sea chest at the base of my bunk. Make it the size
of a barrel (Enc 6 Carry 12) and fill it with 12 enc of assorted stuff I
have picked up along my travels. It still counts as either 5 enc if
ticked as worn or 6 if not. (Not that it could be worn, but you get my
drift I am sure.) So my character is perpetually over encumbered.
I guess I could edit it to have Enc zero, but that is a workaround.
I hope that makes sense.

Thank you for responding,
Kind regards,
Rob

**Comment by moo-man** [comment]
Containers have a specific option for containers that are "never worn", such as carts. You click this 

![image](https://user-images.githubusercontent.com/28637157/133487543-7dce716f-4387-466f-9d22-cc6b79eafcdb.png)

**Comment by RKnowlesLeak** [comment]
That will provide me with the solution that I am looking for.
Thank you for letting me know about it. I had not noticed that feature
before.

Issue closed!
Thanks again and keep up the awesome work.
Rob

**Comment by moo-man** [comment]
Glad to hear that'll work
