### ISSUE TITLE
New WFRP Cursor

### ISSUE THREAD

**Issue by simulacrum-1** [moo-man/WFRP4e-FoundryVTT#842]
**Is your feature request related to a problem? Please describe.**
There isn't a WFRP cursor for the link state, this is probably new to the Foundry update I guess. So rather than having Mickey Mouses hand show up it would be nice to have something more WFRPy. Low priority
https://user-images.githubusercontent.com/68729767/133468975-dd8aaa6a-0152-46a7-be15-0ea44c5fea14.mov

**Describe the solution you'd like**
Something more like (below) perhaps? You know best it's your ui.

**Additional context**
![link](https://user-images.githubusercontent.com/68729767/133469073-de0da18a-b239-4566-b471-4d56d6765dc6.png)
![gauntlet-gold](https://user-images.githubusercontent.com/68729767/133469085-750bab7b-d7ea-4233-9499-197795ea07e6.png)

**Comment by moo-man** [comment]
There is already a cursor for the "pointer" state, it's an issue with it being rather complicated to get it working with PIXI (tokens)
