### ISSUE TITLE
[WFRP4e Core] Black Eye

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#846]
Apply 'Black Eye' condition. Target and attack. Error running Blinded Effect.<br/>**From**: simulacrum #7888<br/>wfrp4e: 4.2.1<br/>wfrp4e-core: 2.1.2<br/>wfrp4e-dotr: 2.0.6<br/>wfrp4e-eis: 2.0.5<br/>wfrp4e-rnhd: 2.1.2<br/>wfrp4e-starter-set: 2.0.3<br/>wfrp4e-ua1: 2.0.2

**Comment by simulacrum-1** [comment]
![Screenshot 2021-09-16 at 18 35 03](https://user-images.githubusercontent.com/68729767/133662365-925563f3-9f9b-4e51-aafb-822866203500.jpg)
