### ISSUE TITLE
Link in journals appear broken

### ISSUE THREAD

**Issue by Drdagost** [moo-man/WFRP4e-FoundryVTT#860]
While reading over the Starter Set Adventure Summary I noticed the links are broken.
![image](https://user-images.githubusercontent.com/45475240/134268671-6afc3916-c245-4b85-b46d-46b035d99e8d.png)

**Comment by moo-man** [comment]
You haven't initialized the Starter Set yet. Once initialized, the journal entry in the world will have links that work.
