### ISSUE TITLE
Automatic granting/removing of Advantage

### ISSUE THREAD

**Issue by gravagehulk** [moo-man/WFRP4e-FoundryVTT#865]
**Is your feature request related to a problem? Please describe.**
Managing Advantage is a real pain

**Describe the solution you'd like**
Ideally, granting and removing advantage would be somewhat automated. When a PC or NPC wins an opposed test, 1 advantage is granted automatically. When they lose or take damage, all advantage is cleared.

**Additional context**
I know this isn't a problem with the System so much as a core feature that annoys me, but as a GM, managing the advantage, even with a macro, is tedious. If there was any way to automate the granting/removing of advantage, it would make my job a lot easier. I considered just eliminating it all together, but there are other mechanics that depend on it and then you're almost just playing WFRP 2e again.

**Comment by moo-man** [comment]
Leaving this for GM toolkit
