### ISSUE TITLE
[WFRP4e System] In game "Edit World" is unusable.

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#897]
Set it as enhancement since I believe most edit their worlds outside the game. Will check what it looks like on my empty test-world also.<br/>**From**: mogrogh#4778<br/>wfrp4e: 4.2.1<br/>wfrp4e-archives1: 2.1.1<br/>wfrp4e-core: 2.1.2<br/>wfrp4e-dotr: 2.0.6<br/>wfrp4e-eis: 2.0.5<br/>wfrp4e-middenheim: 2.1.2<br/>wfrp4e-rnhd: 2.1.2<br/>wfrp4e-starter-set: 2.0.3<br/>wfrp4e-ua1: 2.0.2

**Comment by mogrogh** [comment]
Yes, testworld with no modules active had the same problem.
![image](https://user-images.githubusercontent.com/69079040/139842370-a3647835-8fb4-4b0c-a24d-d71b424a9d5f.png)
