### ISSUE TITLE
Compendium ??

### ISSUE THREAD

**Issue by guillaumecd15** [moo-man/WFRP4e-FoundryVTT#9]
Hi since i ve updated the version of Warhammer in VTT , all compendum are gone.
is it plan to get them back ?

**Comment by moo-man** [comment]
The popup should've described the situation. Contact me on discord if you need help recreating content or have questions.

**Comment by guillaumecd15** [comment]
I recovered an ancien version 1.6.2.
Enough for me as i can customize it.

Thx anyway

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>

________________________________
