### ISSUE TITLE
[WFRP4e System] Ability to share actor art from actor sheet

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#900]
Actors can be open directly from a journal, and you have yourself added many such links. Sometimes, I have zero idea where the actor is located (in term of folder), and frankly dont even need the token, but I'd like to share the art.<br/>**From**: Ceodryn#2537<br/>wfrp4e: 4.2.1<br/>wfrp4e-archives1: 2.1.1<br/>wfrp4e-core: 2.1.2<br/>wfrp4e-dotr: 2.0.6<br/>wfrp4e-eis: 2.0.5<br/>wfrp4e-middenheim: 2.1.2<br/>wfrp4e-rnhd: 2.1.2<br/>wfrp4e-starter-set: 2.0.3<br/>wfrp4e-ua1: 2.0.2

**Comment by StevenEvans1966** [comment]
Have you tried Show Art & Show Artwork Modules

**Comment by moo-man** [comment]
Closing as out of scope
