### ISSUE TITLE
[WFRP4e System] Custom Status Icons

### ISSUE THREAD

**Issue by Havoclivekiller** [moo-man/WFRP4e-FoundryVTT#916]
**Is your feature request related to a problem? Please describe.**
Add some custom icons, like colors or the ability to have the default status icons. In other systems, you can use the default icons (DnD5e, Shadowrun, etc.) to mark tokens. Right now, you as the GM don't have the ability to mark tokens - "this one has a bow", "this one holds the item you want", "this guy is Channeling", "this guy is limping due to a critical" etc. You would need to create a new token for every version of the token or something else.

**Describe the solution you'd like**
Either add these default status icons FoundryVTT has:
![image](https://user-images.githubusercontent.com/21118924/142459098-2f543d00-dbec-4df6-b7d5-03029030343f.png)
or add different ones, let's call them markers. Here are some I've made for my worlds:
![image](https://user-images.githubusercontent.com/21118924/142459195-2891dd54-b18d-4611-b592-cb814bde1bc1.png)

P.S. I've tried to add this to the system once before but failed.

**Comment by moo-man** [comment]
I think this should be in module territory. The system provides the system defined icons, users can add others via modules or scripts. If you need help, just let me know.
