### ISSUE TITLE
[WFRP4e System] Cursor not applied

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#925]
All of the cursors mechanism aren't supporting non root foundryvtt path. 

I'm behind a proxy and I've added the pointer file at the right place. Then this error appear in the console: 

Refused to apply style from 'https://www.url/systems/wfrp4e/css/cursor.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.<br/>**From**: Fneuch#5019<br/>wfrp4e: 4.3.0<br/>wfrp4e-archives1: 2.2.0<br/>wfrp4e-core: 2.2.0<br/>wfrp4e-eis: 2.1.0<br/>wfrp4e-rnhd: 2.2.0<br/>wfrp4e-starter-set: 2.1.0<br/>wfrp4e-ua1: 2.1.0

**Comment by Fneuch** [comment]
Oups, forgot to remove my path link. :sweat:
