### ISSUE TITLE
[WFRP4e Core] Broken journal links

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#93]
The links in the Politics journal entry are broken<br/>**From**: hrafnagud314<br/>wfrp4e: 3.0.0<br/>wfrp4e-core: 1.0<br/>wfrp4e-rnhd: 1.0<br/>wfrp4e-starter-set: 1.0

**Comment by Kelliak** [comment]
Broken link in 

Between Adventures -> Endeavors -> Endeavors

The link to "Income" Endeavor

**Comment by Kelliak** [comment]
Actually lots of the Endeavor Journal links are broken

**Comment by Kelliak** [comment]
Additionally

Magic -> The Aethyr

Journal links to the eight lores
