### ISSUE TITLE
[WFRP 4e Core] NPC randomizer is not working

### ISSUE THREAD

**Issue by Wolenard** [moo-man/WFRP4e-FoundryVTT#955]
NPC randomizer is not working when click on buttons in an NPC sheet; entering species does not activate an offer from the game to apply the characteristics (human, elf etc).

Creating NPC sheet, trying to click on randomizer button

![image](https://user-images.githubusercontent.com/96601011/147301006-ea26ab13-06d4-47dc-b98e-739897b93eb3.png)
![NPC randomizer bug](https://user-images.githubusercontent.com/96601011/147301397-fe9a0388-adfb-427f-9629-80130cf67876.png)

Foundry: 9. Build 238
wfrp4e:
wfrp4e-core: 2.3.1.
wfrp4e-starter-set: 2.2.0
wfrp4e-rnhd: 2.3..0
wfrp4e-eis: 2.2.0.
wfrp4e-ua1: 2.2.0
wfrp4e-dotr: 2.2.0.
wfrp4e-archives1: 2.3.0
wfrp4e-middenheim: 2.3.0
wfrp4e-power-behind-the-throne: 2.1.0

Console listing:

When clicking "C" in randomizer
wfrp4e | Could not randomize: TypeError: Cannot read properties of undefined (reading 'value')

When clicking "S"
actor-wfrp4e.js:2333 Uncaught (in promise) TypeError: skillSelector.reroll is not a function
[Detected 1 package: system:wfrp4e]
    at ActorWfrp4e._advanceSpeciesSkills (actor-wfrp4e.js:2333)
    at ActorSheetWfrp4eNPC._onRandomizeClicked (actor-sheet.js:1389)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)

When clicking "T"
foundry.js:6695 Roll#evaluate is becoming asynchronous. In the short term you may pass async=true or async=false to evaluation options to nominate your preferred behavior.
evaluate @ foundry.js:6695
roll @ foundry.js:6798
rollTable @ tables-wfrp4e.js:41
_advanceSpeciesTalents @ actor-wfrp4e.js:2377
async function (async)
_advanceSpeciesTalents @ actor-wfrp4e.js:2394
_onRandomizeClicked @ actor-sheet.js:1392
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
actor-wfrp4e.js:2456 Something went wrong when adding talent undefined: TypeError: Cannot read properties of undefined (reading 'trim')
_advanceTalent @ actor-wfrp4e.js:2456
async function (async)
_advanceTalent @ actor-wfrp4e.js:2452
_advanceSpeciesTalents @ actor-wfrp4e.js:2378
async function (async)
_advanceSpeciesTalents @ actor-wfrp4e.js:2394
_onRandomizeClicked @ actor-sheet.js:1392
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:6695 Roll#evaluate is becoming asynchronous. In the short term you may pass async=true or async=false to evaluation options to nominate your preferred behavior.
evaluate @ foundry.js:6695
roll @ foundry.js:6798
rollTable @ tables-wfrp4e.js:41
_advanceSpeciesTalents @ actor-wfrp4e.js:2377
async function (async)
_advanceSpeciesTalents @ actor-wfrp4e.js:2394
_onRandomizeClicked @ actor-sheet.js:1392
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
actor-wfrp4e.js:2456 Something went wrong when adding talent undefined: TypeError: Cannot read properties of undefined (reading 'trim')
_advanceTalent @ actor-wfrp4e.js:2456
async function (async)
_advanceTalent @ actor-wfrp4e.js:2452
_advanceSpeciesTalents @ actor-wfrp4e.js:2378
async function (async)
_advanceSpeciesTalents @ actor-wfrp4e.js:2394
_onRandomizeClicked @ actor-sheet.js:1392
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:6695 Roll#evaluate is becoming asynchronous. In the short term you may pass async=true or async=false to evaluation options to nominate your preferred behavior.
evaluate @ foundry.js:6695
roll @ foundry.js:6798
rollTable @ tables-wfrp4e.js:41
_advanceSpeciesTalents @ actor-wfrp4e.js:2377
async function (async)
_advanceSpeciesTalents @ actor-wfrp4e.js:2394
_onRandomizeClicked @ actor-sheet.js:1392
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
actor-wfrp4e.js:2456 Something went wrong when adding talent undefined: TypeError: Cannot read properties of undefined (reading 'trim')

**Comment by Txus5012** [comment]
This may be related: When filling the species name, the dialog to apply the species' characteristics doesn't appear.
![Species](https://user-images.githubusercontent.com/87753744/147350070-fb31613c-a9fb-418d-99fb-7b246c13cddb.jpg)
Nothing happens, there isn't even a console message.

But it recognizes when a wrong name is typed, it just does nothing when a right species is typed:
![Species 2](https://user-images.githubusercontent.com/87753744/147350396-55f87eca-0bef-42aa-9877-102a8d1ba720.jpg)

Foundry v9
WFRP4e system 5.0.2
WFRP4e Core Content Module 2.3.1
