### ISSUE TITLE
[WFRP4e System] GM Screen Module Incompatible

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#957]
The GM Screen, a super useful module, nows display the text in grey over the parchment background, which is impossible to read.<br/>**From**: Ceodryn#2537<br/>wfrp4e: 5.0.2<br/>wfrp4e-archives1: 2.3.0<br/>wfrp4e-core: 2.3.1<br/>wfrp4e-dotr: 2.2.0<br/>wfrp4e-eis: 2.2.0<br/>wfrp4e-middenheim: 2.3.0<br/>wfrp4e-pbtt: 2.1.0<br/>wfrp4e-rnhd: 2.3.0<br/>wfrp4e-starter-set: 2.2.0<br/>wfrp4e-ua1: 2.2.0

**Comment by mogrogh** [comment]
![image](https://user-images.githubusercontent.com/69079040/149578388-164a173e-7ff9-429f-aee0-2ff8debb6319.png)
