### ISSUE TITLE
[WFRP4e System] WFRP4e Tables in popout

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#967]
The old "WFRP4e Tables" button is still available in the popout and it throws an error when used<br/>**From**: Fneuch#5019<br/>wfrp4e: 5.0.3<br/>wfrp4e-archives1: 2.3.0<br/>wfrp4e-core: 2.3.2<br/>wfrp4e-eis: 2.2.1<br/>wfrp4e-rnhd: 2.3.1<br/>wfrp4e-starter-set: 2.2.1<br/>wfrp4e-ua1: 2.2.1

**Comment by Fneuch** [comment]
Taken some screenshot...
![wfrp-tables](https://user-images.githubusercontent.com/9579799/147671700-2ba652ad-12dd-416e-a492-0048ebdac45c.png)
![wfrp-tables-chat](https://user-images.githubusercontent.com/9579799/147671711-2f20cc95-d869-46c2-88ea-458e976f4f96.png)
![wfrp-tables-error](https://user-images.githubusercontent.com/9579799/147671718-ebbd86c2-d0e7-4820-96fb-86c58c625cd3.png)

**Comment by Fneuch** [comment]
And they are still visible:
![section-available](https://user-images.githubusercontent.com/9579799/147672413-e4687b09-cfbb-4537-90f5-47543ddb897a.png)
