### ISSUE TITLE
[WFRP4e Core] Random Char Gen

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#969]
So our weekly game is in two hours and we have a new player joining us. In past versions of WFRP on Foundry you could /char and build a char by the book that way. It is no longer possible. What gives?  Pretty much cripples a group that has to play online due to the pandemic.  It comes up with Species but when I hit Roll it says "Table Not Found". Help!<br/>**From**: holmes79@gmail.com<br/>wfrp4e: 5.0.3<br/>wfrp4e-archives1: 2.3.0<br/>wfrp4e-core: 2.3.2<br/>wfrp4e-eis: 2.2.1<br/>wfrp4e-middenheim: 2.3.1<br/>wfrp4e-rnhd: 2.3.1<br/>wfrp4e-starter-set: 2.2.1<br/>wfrp4e-ua1: 2.2.1

**Comment by TrickyDUK** [comment]
I think that you have to import all tables from the Compendium first.
