### ISSUE TITLE
[WFRP4e System] GM Toolkit (WFRP4e)

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#970]
The GM Toolkit "configure" buttons in the Configure Game Settings do not open anything. <br/>**From**: Ceodryn#2537<br/>wfrp4e: 5.0.3<br/>wfrp4e-archives1: 2.3.0<br/>wfrp4e-core: 2.3.2<br/>wfrp4e-dotr: 2.2.1<br/>wfrp4e-eis: 2.2.1<br/>wfrp4e-middenheim: 2.3.1<br/>wfrp4e-pbtt: 2.1.1<br/>wfrp4e-rnhd: 2.3.1<br/>wfrp4e-starter-set: 2.2.1<br/>wfrp4e-ua1: 2.2.1

**Comment by Jagusti** [comment]
In case anyone follows this trail ... It leads to https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/issues/70
