### ISSUE TITLE
Missing cursor folder in system/ui

### ISSUE THREAD

**Issue by hobeika** [moo-man/WFRP4e-FoundryVTT#991]
**Describe the bug**

On a fresh install of the WFRP4e system with only the core module installed I can see the following error.
`http://localhost:30000/systems/wfrp4e/ui/cursors/pointer.png 404 (Not Found)`
After looking at the systems/wfrp4e/ui I can see the cursors folder is missing.

```
http.mjs:26 HEAD http://localhost:30000/systems/wfrp4e/ui/cursors/pointer.png 404 (Not Found)
fetchWithTimeout @ http.mjs:26
srcExists @ foundry.js:23115
(anonymous) @ ready.js:62
async function (async)
(anonymous) @ ready.js:31
_call @ foundry.js:294
callAll @ foundry.js:253
setupGame @ foundry.js:5547
async function (async)
setupGame @ foundry.js:5513
_initializeGameView @ foundry.js:6479
_initializeView @ foundry.js:6455
initialize @ foundry.js:5415
async function (async)
initialize @ foundry.js:5409
window.addEventListener.once @ foundry.js:62282
async function (async)
window.addEventListener.once @ foundry.js:62281
ready.js:71 wfrp4e | No custom cursor found
(anonymous) @ ready.js:71
async function (async)
(anonymous) @ ready.js:31
_call @ foundry.js:294
callAll @ foundry.js:253
setupGame @ foundry.js:5547
async function (async)
setupGame @ foundry.js:5513
_initializeGameView @ foundry.js:6479
_initializeView @ foundry.js:6455
initialize @ foundry.js:5415
async function (async)
initialize @ foundry.js:5409
window.addEventListener.once @ foundry.js:62282
async function (async)
window.addEventListener.once @ foundry.js:62281
```

**To Reproduce**
Vanilla installation of foundryvtt + wfrp4e system + core module for wfrp4e
Login (either as a player or gamemaster), check the console.
Also you can notice the absence of a custom mouse cursor.

**Screenshots**
![image](https://user-images.githubusercontent.com/1174140/149322156-4d898e24-a04f-450a-9051-659b51bb6545.png)

**Version Numbers**
PLEASE PROVIDE YOUR FOUNDRY, SYSTEM, and MODULE VERSIONS (where applicable) 

Foundry:
wfrp4e:5.0.5
wfrp4e-core:2.3.3
wfrp4e-starter-set:
wfrp4e-rnhd:
wfrp4e-eis:
wfrp4e-ua1:
wfrp4e-dotr:
wfrp4e-archives1:
wfrp4e-middenheim:

**Comment by moo-man** [comment]
It was removed due to copyright

**Comment by moo-man** [comment]
I left the code there in case anyone wants to put the cursor back, I'm fine with a default pointer, provided it has an open license to use.

**Comment by hobeika** [comment]
Thanks. I'll look into it and reopen this with a PR when ready, if that works for you.
